### ISSUE TITLE
Bower erroring on lstat

### ISSUE THREAD

**Issue by wesleycho** [bower/bower#1019]
Here is the set of error messages:

```
bower ENOENT        ENOENT, lstat '/home/wcho/.cache/bower/packages/ef2188def21eb1bbd1f1792311942a53/1.2.7-build.2021%2Bsha.df2b88e/README.md'

Stack trace:
/usr/lib/node_modules/bower/node_modules/fstream/lib/writer.js:284:26
Object.oncomplete (fs.js:107:15)

Console trace:
Trace
    at StandardRenderer.error (/usr/lib/node_modules/bower/lib/renderers/StandardRenderer.js:74:17)
    at Logger.updateNotifier.packageName (/usr/lib/node_modules/bower/bin/bower:109:18)
    at Logger.EventEmitter.emit (events.js:95:17)
    at Logger.emit (/usr/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/lib/node_modules/bower/lib/commands/install.js:27:16
    at _rejected (/usr/lib/node_modules/bower/node_modules/q/q.js:808:24)
    at /usr/lib/node_modules/bower/node_modules/q/q.js:834:30
    at Promise.when (/usr/lib/node_modules/bower/node_modules/q/q.js:1079:31)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/bower/node_modules/q/q.js:752:41)
    at /usr/lib/node_modules/bower/node_modules/q/q.js:574:44

System info:
Bower version: 1.2.8
Node version: 0.10.23
OS: Linux 3.8.0-33-generic x64
```

This occured while running `bower install`, with some dependency specifying `"angular": ">=1.1.5"`, which caused it to fetch the latest build of angular.

**Comment by drvanhalen** [comment]
Still seeing this on 1.3.12, quite regularly. Jenkins job stack trace:
```
bower                                        ENOENT ENOENT, lstat '/var/lib/jenkins/.cache/bower/packages/f3b72beceafaab79b3b463cf7c52211d/2.0.10'

Stack trace:
statCb (/var/lib/jenkins/workspace/Frontend - Branches/node_modules/bower/node_modules/fstream/lib/reader.js:152:23)
Object.oncomplete (evalmachine.<anonymous>:107:15)

Console trace:
Trace
    at StandardRenderer.error (/var/lib/jenkins/workspace/Frontend - Branches/node_modules/bower/lib/renderers/StandardRenderer.js:82:17)
    at Logger.<anonymous> (/var/lib/jenkins/workspace/Frontend - Branches/node_modules/bower/bin/bower:110:22)
    at Logger.emit (events.js:95:17)
    at Logger.emit (/var/lib/jenkins/workspace/Frontend - Branches/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /var/lib/jenkins/workspace/Frontend - Branches/node_modules/bower/lib/commands/index.js:40:20
    at _rejected (/var/lib/jenkins/workspace/Frontend - Branches/node_modules/bower/node_modules/q/q.js:797:24)
    at /var/lib/jenkins/workspace/Frontend - Branches/node_modules/bower/node_modules/q/q.js:823:30
    at Promise.when (/var/lib/jenkins/workspace/Frontend - Branches/node_modules/bower/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch (/var/lib/jenkins/workspace/Frontend - Branches/node_modules/bower/node_modules/q/q.js:741:41)
    at /var/lib/jenkins/workspace/Frontend - Branches/node_modules/bower/node_modules/q/q.js:557:44

System info:
Bower version: 1.3.12
Node version: 0.10.33
OS: Linux 3.2.0-4-amd64 x64
```

@sheerun any ideas? Don't really want to have to add `--force` if possible.

**Comment by knalli** [comment]
I can see some issues on the underlaying herukoapp like 

```
bower                                                              retry Request to https://bower.herokuapp.com/packages/requirejs failed with ECONNRESET, retrying in 1.9s
bower                                                              retry Request to https://bower.herokuapp.com/packages/requirejs-domready failed with ECONNRESET, retrying in 1.2s
bower                                                              retry Request to https://bower.herokuapp.com/packages/jcrop failed with ECONNRESET, retrying in 1.9s
bower                                                              retry Request to https://bower.herokuapp.com/packages/json3 failed with ECONNRESET, retrying in 1.8s
```

and that'd be "only" network and not part of this issue.

**Comment by Jiri-Kremser** [comment]
Running from the maven frontend plugin that runs the bower.

```
[ERROR] bower angular-truncate#master                error key must be a string or number. undefined
[ERROR] 
[ERROR] Stack trace:
[ERROR] TypeError: key must be a string or number. undefined
[ERROR]     at typeCheckKey (/home/jkremser/workspace/hawkular/hawkular/console/target/gulp-build/node_modules/bower/node_modules/lru-cache/lib/lru-cache.js:18:11)
[ERROR]     at LRUCache.get (/home/jkremser/workspace/hawkular/hawkular/console/target/gulp-build/node_modules/bower/node_modules/lru-cache/lib/lru-cache.js:227:3)
[ERROR]     at /home/jkremser/workspace/hawkular/hawkular/console/target/gulp-build/node_modules/bower/lib/core/resolvers/GitRemoteResolver.js:122:70
[ERROR]     at _fulfilled (/home/jkremser/workspace/hawkular/hawkular/console/target/gulp-build/node_modules/bower/node_modules/q/q.js:834:54)
[ERROR]     at self.promiseDispatch.done (/home/jkremser/workspace/hawkular/hawkular/console/target/gulp-build/node_modules/bower/node_modules/q/q.js:863:30)
[ERROR]     at Promise.promise.promiseDispatch (/home/jkremser/workspace/hawkular/hawkular/console/target/gulp-build/node_modules/bower/node_modules/q/q.js:796:13)
[ERROR]     at /home/jkremser/workspace/hawkular/hawkular/console/target/gulp-build/node_modules/bower/node_modules/q/q.js:857:14
[ERROR]     at runSingle (/home/jkremser/workspace/hawkular/hawkular/console/target/gulp-build/node_modules/bower/node_modules/q/q.js:137:13)
[ERROR]     at flush (/home/jkremser/workspace/hawkular/hawkular/console/target/gulp-build/node_modules/bower/node_modules/q/q.js:125:13)
[ERROR]     at doNTCallback0 (node.js:419:9)
[ERROR] 
[ERROR] Console trace:
[ERROR] Error
[ERROR]     at StandardRenderer.error (/home/jkremser/workspace/hawkular/hawkular/console/target/gulp-build/node_modules/bower/lib/renderers/StandardRenderer.js:82:37)
[ERROR]     at Logger.<anonymous> (/home/jkremser/workspace/hawkular/hawkular/console/target/gulp-build/node_modules/bower/bin/bower:110:22)
[ERROR]     at emitOne (events.js:77:13)
[ERROR]     at Logger.emit (events.js:169:7)
[ERROR]     at Logger.emit (/home/jkremser/workspace/hawkular/hawkular/console/target/gulp-build/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
[ERROR]     at /home/jkremser/workspace/hawkular/hawkular/console/target/gulp-build/node_modules/bower/lib/commands/index.js:45:20
[ERROR]     at _rejected (/home/jkremser/workspace/hawkular/hawkular/console/target/gulp-build/node_modules/bower/node_modules/q/q.js:844:24)
[ERROR]     at /home/jkremser/workspace/hawkular/hawkular/console/target/gulp-build/node_modules/bower/node_modules/q/q.js:870:30
[ERROR]     at Promise.when (/home/jkremser/workspace/hawkular/hawkular/console/target/gulp-build/node_modules/bower/node_modules/q/q.js:1122:31)
[ERROR]     at Promise.promise.promiseDispatch (/home/jkremser/workspace/hawkular/hawkular/console/target/gulp-build/node_modules/bower/node_modules/q/q.js:788:41)
[ERROR] System info:
[ERROR] Bower version: 1.4.1
[ERROR] Node version: 4.2.2
[ERROR] OS: Linux 4.2.6-300.fc23.x86_64 x64

```
