### ISSUE TITLE
Bower failed to install with NPM

### ISSUE THREAD

**Issue by slavafomin** [bower/bower#1022]
Hey there!

I'm trying to install `bower` on a clean Ubuntu 13.10 machine.

I'm doing `sudo apt-get install git nodejs npm` then `sudo npm install -g bower`.

I'm getting the following output:

```
npm http GET https://registry.npmjs.org/bower
npm http 304 https://registry.npmjs.org/bower
npm http GET https://registry.npmjs.org/abbrev
npm http GET https://registry.npmjs.org/bower-config
npm http GET https://registry.npmjs.org/archy/0.0.2
npm http GET https://registry.npmjs.org/bower-endpoint-parser
npm http GET https://registry.npmjs.org/bower-json
npm http GET https://registry.npmjs.org/bower-logger
npm http GET https://registry.npmjs.org/bower-registry-client
npm http GET https://registry.npmjs.org/cardinal
npm http GET https://registry.npmjs.org/chalk
npm http GET https://registry.npmjs.org/chmodr
npm http GET https://registry.npmjs.org/decompress-zip
npm http GET https://registry.npmjs.org/fstream
npm http GET https://registry.npmjs.org/fstream-ignore
npm http GET https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/graceful-fs
npm http GET https://registry.npmjs.org/inquirer
npm http GET https://registry.npmjs.org/junk
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/mout
npm http GET https://registry.npmjs.org/nopt
npm http GET https://registry.npmjs.org/lru-cache
npm http GET https://registry.npmjs.org/open
npm http GET https://registry.npmjs.org/osenv/0.0.3
npm http GET https://registry.npmjs.org/promptly
npm http GET https://registry.npmjs.org/q
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/request-progress
npm http GET https://registry.npmjs.org/retry
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/semver
npm http GET https://registry.npmjs.org/stringify-object
npm http GET https://registry.npmjs.org/sudo-block
npm http GET https://registry.npmjs.org/tar
npm http GET https://registry.npmjs.org/tmp
npm http GET https://registry.npmjs.org/update-notifier
npm http GET https://registry.npmjs.org/which
npm http GET https://registry.npmjs.org/p-throttler
npm http GET https://registry.npmjs.org/handlebars
npm http 304 https://registry.npmjs.org/archy/0.0.2
npm http 304 https://registry.npmjs.org/bower-json
npm http 304 https://registry.npmjs.org/bower-logger
npm http 304 https://registry.npmjs.org/bower-registry-client
npm http 304 https://registry.npmjs.org/cardinal
npm http 304 https://registry.npmjs.org/chalk
npm http 304 https://registry.npmjs.org/chmodr
npm http 304 https://registry.npmjs.org/decompress-zip
npm http 304 https://registry.npmjs.org/fstream
npm http 304 https://registry.npmjs.org/glob
npm http 304 https://registry.npmjs.org/graceful-fs
npm http 304 https://registry.npmjs.org/fstream-ignore
npm http 304 https://registry.npmjs.org/inquirer
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/junk
npm http 304 https://registry.npmjs.org/nopt
npm http 304 https://registry.npmjs.org/mout
npm http 304 https://registry.npmjs.org/lru-cache
npm http 304 https://registry.npmjs.org/open
npm http 304 https://registry.npmjs.org/osenv/0.0.3
npm http 304 https://registry.npmjs.org/promptly
npm http 304 https://registry.npmjs.org/q
npm http 304 https://registry.npmjs.org/request
npm http 304 https://registry.npmjs.org/request-progress
npm http 304 https://registry.npmjs.org/retry
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/semver
npm http 304 https://registry.npmjs.org/stringify-object
npm http 304 https://registry.npmjs.org/sudo-block
npm http 304 https://registry.npmjs.org/tar
npm http 304 https://registry.npmjs.org/tmp
npm http 304 https://registry.npmjs.org/which
npm http 304 https://registry.npmjs.org/update-notifier
npm http 304 https://registry.npmjs.org/p-throttler
npm http 304 https://registry.npmjs.org/handlebars
npm ERR! TypeError: Invalid Version: 1.0.2beta
npm ERR!     at new SemVer (/usr/lib/nodejs/semver/semver.js:271:11)
npm ERR!     at compare (/usr/lib/nodejs/semver/semver.js:424:10)
npm ERR!     at gte (/usr/lib/nodejs/semver/semver.js:473:10)
npm ERR!     at cmp (/usr/lib/nodejs/semver/semver.js:490:22)
npm ERR!     at Comparator.test (/usr/lib/nodejs/semver/semver.js:560:10)
npm ERR!     at testSet (/usr/lib/nodejs/semver/semver.js:885:17)
npm ERR!     at Range.test (/usr/lib/nodejs/semver/semver.js:877:9)
npm ERR!     at satisfies (/usr/lib/nodejs/semver/semver.js:898:16)
npm ERR!     at /usr/lib/nodejs/semver/semver.js:904:12
npm ERR!     at Array.filter (native)
npm ERR!     at Function.maxSatisfying (/usr/lib/nodejs/semver/semver.js:903:19)
npm ERR!     at next (/usr/share/npm/lib/cache.js:662:21)
npm ERR!     at /usr/share/npm/lib/cache.js:644:5
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /home/vagrant/npm-debug.log npm

npm ERR! System Linux 3.11.0-14-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "bower"
npm ERR! cwd /home/vagrant
npm ERR! node -v v0.10.15
npm ERR! npm -v 1.2.18
npm http 304 https://registry.npmjs.org/abbrev
npm http 304 https://registry.npmjs.org/bower-config
npm http 304 https://registry.npmjs.org/bower-endpoint-parser
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/vagrant/npm-debug.log
npm ERR! not ok code 0
```

```
git --version
git version 1.8.3.2
```

```
nodejs --version
v0.10.15
```

```
npm --version
1.2.18
```

Please advise. Thank you.

Here's the debug log file:
https://gist.github.com/slavafomin/08f7fc6b338582c3c391

**Comment by daniloichaves** [comment]
@slavafomin  hi we are with the same problema what's is the solution? whoul you help us?

**Comment by slavafomin** [comment]
@daniloichaves I would recommend to use `npm` or even better `yarn`.
