### ISSUE TITLE
Error installing Bower (ERR! tar.unpack untar error)

### ISSUE THREAD

**Issue by marlun78** [bower/bower#1244]
I get this error when trying to install Bower. Is this a bug or am I doing it wrong? 
I also have 4707 lines of npm-debug.log file if needed... 

Thanks!

``` bash
npm install bower
npm http GET https://registry.npmjs.org/bower
npm http 304 https://registry.npmjs.org/bower
npm http GET https://registry.npmjs.org/abbrev
npm http GET https://registry.npmjs.org/archy/0.0.2
npm http GET https://registry.npmjs.org/bower-config
npm http GET https://registry.npmjs.org/bower-endpoint-parser
npm http GET https://registry.npmjs.org/bower-json
npm http GET https://registry.npmjs.org/bower-logger
npm http GET https://registry.npmjs.org/bower-registry-client
npm http GET https://registry.npmjs.org/cardinal
npm http GET https://registry.npmjs.org/chalk
npm http GET https://registry.npmjs.org/chmodr
npm http GET https://registry.npmjs.org/decompress-zip
npm http GET https://registry.npmjs.org/fstream-ignore
npm http GET https://registry.npmjs.org/fstream
npm http GET https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/graceful-fs
npm http GET https://registry.npmjs.org/handlebars
npm http GET https://registry.npmjs.org/inquirer
npm http GET https://registry.npmjs.org/junk
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/mout
npm http GET https://registry.npmjs.org/nopt
npm http GET https://registry.npmjs.org/lru-cache
npm http GET https://registry.npmjs.org/open
npm http GET https://registry.npmjs.org/osenv
npm http GET https://registry.npmjs.org/promptly
npm http GET https://registry.npmjs.org/q
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/request-progress
npm http GET https://registry.npmjs.org/retry
npm http GET https://registry.npmjs.org/stringify-object
npm http GET https://registry.npmjs.org/tar
npm http GET https://registry.npmjs.org/semver
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/tmp
npm http GET https://registry.npmjs.org/update-notifier
npm http GET https://registry.npmjs.org/p-throttler
npm http GET https://registry.npmjs.org/is-root
npm http GET https://registry.npmjs.org/insight
npm http GET https://registry.npmjs.org/which
npm http GET https://registry.npmjs.org/shell-quote
npm http GET https://registry.npmjs.org/lockfile
npm http 304 https://registry.npmjs.org/abbrev
npm http 304 https://registry.npmjs.org/bower-config
npm http 304 https://registry.npmjs.org/archy/0.0.2
npm http 304 https://registry.npmjs.org/bower-json
npm http 304 https://registry.npmjs.org/bower-endpoint-parser
npm http 304 https://registry.npmjs.org/bower-registry-client
npm http 304 https://registry.npmjs.org/cardinal
npm http 304 https://registry.npmjs.org/chalk
npm http 304 https://registry.npmjs.org/bower-logger
npm http 304 https://registry.npmjs.org/chmodr
npm http 304 https://registry.npmjs.org/decompress-zip
npm http 304 https://registry.npmjs.org/fstream
npm http 304 https://registry.npmjs.org/glob
npm http 304 https://registry.npmjs.org/graceful-fs
npm http 304 https://registry.npmjs.org/fstream-ignore
npm http 304 https://registry.npmjs.org/handlebars
npm http 304 https://registry.npmjs.org/inquirer
npm http 304 https://registry.npmjs.org/junk
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/nopt
npm http 304 https://registry.npmjs.org/open
npm http 304 https://registry.npmjs.org/lru-cache
npm http 304 https://registry.npmjs.org/mout
npm http 304 https://registry.npmjs.org/osenv
npm http 304 https://registry.npmjs.org/request
npm http 304 https://registry.npmjs.org/promptly
npm http 304 https://registry.npmjs.org/q
npm http 304 https://registry.npmjs.org/request-progress
npm http 304 https://registry.npmjs.org/stringify-object
npm http 304 https://registry.npmjs.org/retry
npm http 304 https://registry.npmjs.org/tar
npm http 304 https://registry.npmjs.org/semver
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/update-notifier
npm http 304 https://registry.npmjs.org/p-throttler
npm http 304 https://registry.npmjs.org/is-root
npm http 304 https://registry.npmjs.org/tmp
npm http 304 https://registry.npmjs.org/insight
npm http 304 https://registry.npmjs.org/which
npm http 304 https://registry.npmjs.org/shell-quote
npm http 304 https://registry.npmjs.org/lockfile
npm http GET https://registry.npmjs.org/has-color
npm http GET https://registry.npmjs.org/ansi-styles
npm http GET https://registry.npmjs.org/strip-ansi
npm http GET https://registry.npmjs.org/configstore
npm http GET https://registry.npmjs.org/configstore
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/object-assign
npm http GET https://registry.npmjs.org/lodash.debounce
npm http GET https://registry.npmjs.org/throttleit
npm http GET https://registry.npmjs.org/read
npm http GET https://registry.npmjs.org/jsonify
npm http GET https://registry.npmjs.org/array-filter
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/array-map
npm http GET https://registry.npmjs.org/array-reduce
npm http GET https://registry.npmjs.org/deep-extend
npm http GET https://registry.npmjs.org/intersect
npm http GET https://registry.npmjs.org/mkpath
npm http GET https://registry.npmjs.org/binary
npm http GET https://registry.npmjs.org/touch/0.0.2
npm http GET https://registry.npmjs.org/readable-stream
npm http GET https://registry.npmjs.org/qs
npm http GET https://registry.npmjs.org/json-stringify-safe
npm http GET https://registry.npmjs.org/forever-agent
npm http GET https://registry.npmjs.org/mime
npm http GET https://registry.npmjs.org/node-uuid
npm http GET https://registry.npmjs.org/tunnel-agent
npm http GET https://registry.npmjs.org/tough-cookie
npm http GET https://registry.npmjs.org/form-data
npm http GET https://registry.npmjs.org/http-signature
npm http GET https://registry.npmjs.org/oauth-sign
npm http GET https://registry.npmjs.org/hawk
npm http GET https://registry.npmjs.org/aws-sign2
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/cli-color
npm http GET https://registry.npmjs.org/through
npm http GET https://registry.npmjs.org/mute-stream/0.0.4
npm http GET https://registry.npmjs.org/readline2
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/request-replay
npm http GET https://registry.npmjs.org/redeyed
npm http GET https://registry.npmjs.org/ansicolors
npm http GET https://registry.npmjs.org/block-stream
npm http 304 https://registry.npmjs.org/configstore
npm http 304 https://registry.npmjs.org/configstore
npm http 304 https://registry.npmjs.org/has-color
npm http GET https://registry.npmjs.org/js-yaml
npm http GET https://registry.npmjs.org/uuid
npm http GET https://registry.npmjs.org/object-assign
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/uglify-js
npm ERR! tar.unpack untar error /Users/[user]/.npm/mout/0.6.0/package.tgz
npm ERR! EEXIST, mkdir '/Users/[user]/[project]/node_modules/bower/node_modules/bower-config/node_modules/mout/doc'
File exists: /Users/[user]/[project]/node_modules/bower/node_modules/bower-config/node_modules/mout/doc
Move it away, and try again.

npm ERR! System Darwin 13.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "bower"
npm ERR! cwd /Users/[user]/[project]
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.4.6
npm ERR! path /Users/[user]/[project]/node_modules/bower/node_modules/bower-config/node_modules/mout/doc
npm ERR! fstream_path /Users/[user]/[project]/node_modules/bower/node_modules/bower-config/node_modules/mout/doc/string.md
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code EEXIST
npm ERR! errno 47
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:171:23
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:37:53
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http 304 https://registry.npmjs.org/lodash.debounce
npm http 304 https://registry.npmjs.org/object-assign
npm http 304 https://registry.npmjs.org/async
npm ERR! Error: ENOENT, lstat '/Users/[user]/[project]/node_modules/bower/node_modules/mout/src/array.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 13.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "bower"
npm ERR! cwd /Users/[user]/[project]
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.4.6
npm ERR! path /Users/[user]/[project]/node_modules/bower/node_modules/mout/src/array.js
npm ERR! fstream_path /Users/[user]/[project]/node_modules/bower/node_modules/mout/src/array.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: unexpected eof
npm ERR!     at decorate (/usr/local/lib/node_modules/npm/node_modules/fstream/lib/abstract.js:67:36)
npm ERR!     at Extract.Abstract.error (/usr/local/lib/node_modules/npm/node_modules/fstream/lib/abstract.js:61:12)
npm ERR!     at Extract._streamEnd (/usr/local/lib/node_modules/npm/node_modules/tar/lib/extract.js:75:22)
npm ERR!     at BlockStream.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:50:8)
npm ERR!     at BlockStream.EventEmitter.emit (events.js:92:17)
npm ERR!     at BlockStream._emitChunk (/usr/local/lib/node_modules/npm/node_modules/block-stream/block-stream.js:203:10)
npm ERR!     at BlockStream.resume (/usr/local/lib/node_modules/npm/node_modules/block-stream/block-stream.js:58:15)
npm ERR!     at Extract.Reader.resume (/usr/local/lib/node_modules/npm/node_modules/fstream/lib/reader.js:253:34)
npm ERR!     at Entry.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:256:8)
npm ERR!     at Entry.EventEmitter.emit (events.js:92:17)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 13.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "bower"
npm ERR! cwd /Users/[user]/[project]
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.4.6
npm ERR! fstream_class Extract
npm ERR! fstream_stack Extract._streamEnd (/usr/local/lib/node_modules/npm/node_modules/tar/lib/extract.js:75:22)
npm ERR! fstream_stack BlockStream.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:50:8)
npm ERR! fstream_stack BlockStream.EventEmitter.emit (events.js:92:17)
npm ERR! fstream_stack BlockStream._emitChunk (/usr/local/lib/node_modules/npm/node_modules/block-stream/block-stream.js:203:10)
npm ERR! fstream_stack BlockStream.resume (/usr/local/lib/node_modules/npm/node_modules/block-stream/block-stream.js:58:15)
npm ERR! fstream_stack Extract.Reader.resume (/usr/local/lib/node_modules/npm/node_modules/fstream/lib/reader.js:253:34)
npm ERR! fstream_stack Entry.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:256:8)
npm ERR! fstream_stack Entry.EventEmitter.emit (events.js:92:17)
npm http GET https://registry.npmjs.org/lodash.isfunction
npm http GET https://registry.npmjs.org/lodash.isobject
npm http GET https://registry.npmjs.org/lodash.now
npm http GET https://registry.npmjs.org/aws-sign
npm http GET https://registry.npmjs.org/cookie-jar
npm http 304 https://registry.npmjs.org/strip-ansi
npm http 304 https://registry.npmjs.org/throttleit
npm http 304 https://registry.npmjs.org/read
npm http 304 https://registry.npmjs.org/jsonify
npm http GET https://registry.npmjs.org/mute-stream
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/array-filter
npm http 304 https://registry.npmjs.org/array-reduce
npm http 304 https://registry.npmjs.org/array-map
npm http 304 https://registry.npmjs.org/deep-extend
npm http 304 https://registry.npmjs.org/intersect
npm http 200 https://registry.npmjs.org/minimatch
npm http 304 https://registry.npmjs.org/mkpath
npm http GET https://registry.npmjs.org/sigmund
npm http 304 https://registry.npmjs.org/binary
npm http 304 https://registry.npmjs.org/touch/0.0.2
npm http 304 https://registry.npmjs.org/ansi-styles
npm http 304 https://registry.npmjs.org/qs
npm http 304 https://registry.npmjs.org/json-stringify-safe
npm http 304 https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/forever-agent
npm http 304 https://registry.npmjs.org/mime
npm http 304 https://registry.npmjs.org/tunnel-agent
npm http GET https://registry.npmjs.org/core-util-is
npm http GET https://registry.npmjs.org/isarray/0.0.1
npm http GET https://registry.npmjs.org/string_decoder
npm http 304 https://registry.npmjs.org/form-data
npm http GET https://registry.npmjs.org/chainsaw
npm http GET https://registry.npmjs.org/buffers
npm http 304 https://registry.npmjs.org/tough-cookie
npm http 200 https://registry.npmjs.org/node-uuid
npm http 304 https://registry.npmjs.org/oauth-sign
npm http 304 https://registry.npmjs.org/hawk
npm http 304 https://registry.npmjs.org/aws-sign2
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/through
npm http 304 https://registry.npmjs.org/cli-color
npm http 304 https://registry.npmjs.org/readline2
npm http 304 https://registry.npmjs.org/inherits
npm http 200 https://registry.npmjs.org/http-signature
npm http GET https://registry.npmjs.org/combined-stream
npm http GET https://registry.npmjs.org/assert-plus/0.1.2
npm http GET https://registry.npmjs.org/asn1/0.1.11
npm http GET https://registry.npmjs.org/ctype/0.5.2
npm http GET https://registry.npmjs.org/punycode
npm http GET https://registry.npmjs.org/hoek
npm http GET https://registry.npmjs.org/boom
npm http GET https://registry.npmjs.org/cryptiles
npm http GET https://registry.npmjs.org/sntp
npm http 304 https://registry.npmjs.org/ansicolors
npm http 304 https://registry.npmjs.org/mute-stream/0.0.4
npm http 200 https://registry.npmjs.org/minimatch
npm http 304 https://registry.npmjs.org/block-stream
npm http GET https://registry.npmjs.org/es5-ext
npm http GET https://registry.npmjs.org/memoizee
npm http 304 https://registry.npmjs.org/redeyed
npm http 304 https://registry.npmjs.org/request-replay
npm http 304 https://registry.npmjs.org/js-yaml
npm http GET https://registry.npmjs.org/esprima
npm http 304 https://registry.npmjs.org/optimist
npm http 304 https://registry.npmjs.org/uuid
npm http 304 https://registry.npmjs.org/uglify-js
npm http 304 https://registry.npmjs.org/object-assign
npm http GET https://registry.npmjs.org/wordwrap
npm http 304 https://registry.npmjs.org/lodash.isfunction
npm http GET https://registry.npmjs.org/argparse
npm http GET https://registry.npmjs.org/esprima
npm http 304 https://registry.npmjs.org/lodash.now
npm http 304 https://registry.npmjs.org/lodash.isobject
npm http 304 https://registry.npmjs.org/aws-sign
npm http GET https://registry.npmjs.org/lodash._isnative
npm http GET https://registry.npmjs.org/lodash._objecttypes
npm http GET https://registry.npmjs.org/source-map
npm http 304 https://registry.npmjs.org/cookie-jar
npm http 304 https://registry.npmjs.org/sigmund
npm http 304 https://registry.npmjs.org/core-util-is
npm http 304 https://registry.npmjs.org/mute-stream
npm http 304 https://registry.npmjs.org/isarray/0.0.1
npm http 304 https://registry.npmjs.org/string_decoder
npm http 304 https://registry.npmjs.org/combined-stream
npm ERR! tar.unpack untar error /Users/[user]/.npm/mout/0.6.0/package.tgz
npm http 304 https://registry.npmjs.org/assert-plus/0.1.2
npm http 304 https://registry.npmjs.org/chainsaw
npm ERR! Error: ENOENT, utime '/Users/[user]/[project]/node_modules/bower/node_modules/bower-registry-client/node_modules/bower-config/node_modules/mout/doc/random.md'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 13.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "bower"
npm ERR! cwd /Users/[user]/[project]
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.4.6
npm ERR! path /Users/[user]/[project]/node_modules/bower/node_modules/bower-registry-client/node_modules/bower-config/node_modules/mout/doc/random.md
npm ERR! fstream_path /Users/[user]/[project]/node_modules/bower/node_modules/bower-registry-client/node_modules/bower-config/node_modules/mout/doc/random.md
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! fstream_finish_call utimes
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:305:19
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http 304 https://registry.npmjs.org/asn1/0.1.11
npm http 304 https://registry.npmjs.org/buffers
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/Users/[user]/[project]/node_modules/bower/node_modules/bower-registry-client/node_modules/request/node_modules/mime'
npm ERR! error rolling back  bower-registry-client@0.1.6 { [Error: ENOTEMPTY, rmdir '/Users/[user]/[project]/node_modules/bower/node_modules/bower-registry-client/node_modules/request/node_modules/mime']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/Users/[user]/[project]/node_modules/bower/node_modules/bower-registry-client/node_modules/request/node_modules/mime' }
npm ERR! Error: ENOENT, open '/Users/[user]/[project]/node_modules/bower/node_modules/bower-registry-client/node_modules/request/node_modules/http-signature/lib/parser.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 13.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "bower"
npm ERR! cwd /Users/[user]/[project]
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.4.6
npm ERR! path /Users/[user]/[project]/node_modules/bower/node_modules/bower-registry-client/node_modules/request/node_modules/http-signature/lib/parser.js
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! Error: ENOENT, lstat '/Users/[user]/[project]/node_modules/bower/node_modules/bower-registry-client/node_modules/request/node_modules/node-uuid/benchmark/benchmark.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 13.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "bower"
npm ERR! cwd /Users/[user]/[project]
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.4.6
npm ERR! path /Users/[user]/[project]/node_modules/bower/node_modules/bower-registry-client/node_modules/request/node_modules/node-uuid/benchmark/benchmark.js
npm ERR! fstream_path /Users/[user]/[project]/node_modules/bower/node_modules/bower-registry-client/node_modules/request/node_modules/node-uuid/benchmark/benchmark.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http 304 https://registry.npmjs.org/ctype/0.5.2
npm http 304 https://registry.npmjs.org/hoek
npm http 304 https://registry.npmjs.org/boom
npm http 304 https://registry.npmjs.org/cryptiles
npm http GET https://registry.npmjs.org/traverse
npm http 304 https://registry.npmjs.org/sntp
npm http GET https://registry.npmjs.org/delayed-stream/0.0.5
npm http 304 https://registry.npmjs.org/punycode
npm http 304 https://registry.npmjs.org/esprima
npm http 304 https://registry.npmjs.org/wordwrap
npm http 304 https://registry.npmjs.org/es5-ext
npm http 304 https://registry.npmjs.org/memoizee
npm http 304 https://registry.npmjs.org/argparse
npm http 304 https://registry.npmjs.org/esprima
npm http 304 https://registry.npmjs.org/delayed-stream/0.0.5
npm http 304 https://registry.npmjs.org/lodash._isnative
npm http 304 https://registry.npmjs.org/lodash._objecttypes
npm http 304 https://registry.npmjs.org/source-map
npm http 304 https://registry.npmjs.org/traverse
npm http GET https://registry.npmjs.org/event-emitter
npm http GET https://registry.npmjs.org/next-tick
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/underscore.string
npm http GET https://registry.npmjs.org/amdefine
npm http 200 https://registry.npmjs.org/next-tick
npm http 304 https://registry.npmjs.org/event-emitter
npm http 304 https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/underscore.string
npm http 304 https://registry.npmjs.org/amdefine
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/[user]/[project]/npm-debug.log
npm ERR! not ok code 0
```

**Comment by ejaz-ahmed** [comment]
I have encountered same issue and cache clean did not work for me.

**Comment by gregoryderner** [comment]
For me it does not work

**Comment by faceleg** [comment]
This is not a bower error.
