### ISSUE TITLE
Packages of the same name but different text case

### ISSUE THREAD

**Issue by CNSKnight** [bower/bower#1422]
```bash
bower datatables#1_9           install datatables#ca12924904
bower                            error Unexpected token t

Stack trace:
SyntaxError: Unexpected token t
    at Object.parse (native)
    at C:\Users\swb8429\AppData\Roaming\npm\node_modules\bower\lib\core\Manager.js:154:37
    at _fulfilled (C:\Users\swb8429\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\swb8429\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\swb8429\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:749:13)
    at C:\Users\swb8429\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:557:44
    at flush (C:\Users\swb8429\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:108:17)
    at process._tickCallback (node.js:415:13)

Console trace:
. . .

System info:
Bower version: 1.3.8
Node version: 0.10.23
OS: Windows_NT 6.1.7601 ia32
```

```json
{
  "name": "DataTables",
  "main": [
    "./media/js/jquery.dataTables.js",
    "./media/css/jquery.dataTables.css"
  ],
  "dependencies": {
    "jquery": ">=1.7.0"
  },
  "homepage": "https://github.com/DataTables/DataTables",
  "_release": "ca12924904",
  "_resolution": {
    "type": "branch",
    "branch": "1_9",
    "commit": "ca129249048a492db441b50355901b3b606d5f0c"
  },
  "_source": "git://github.com/DataTables/DataTables.git",
  "_target": "1_9"
}target": "*"
}
```

**Comment by schmunk42** [comment]
How come that there are packages with uppercase chars in the registry?
Eg. we're having issues with `eventEmitter` and `eventemitter` - is this for legacy reasons?

Would be nice if someone could shed some light on this.

**Comment by ceoaliongroo** [comment]
I thinks this will be resolve with this PR
https://github.com/bower/json/pull/30

I'll close for now.
