### ISSUE TITLE
bower cache clean fails

### ISSUE THREAD

**Issue by eggers** [bower/bower#1423]
```
bower error         Invalid Version: 2.2

Stack trace:
TypeError: Invalid Version: 2.2
    at new SemVer (C:\Users\wfcfjira\AppData\Roaming\npm\node_modules\bower\node_modules\semver\semver.js:271:11)
    at Object.compare (C:\Users\wfcfjira\AppData\Roaming\npm\node_modules\bower\node_modules\semver\semver.js:424:10)
    at C:\Users\wfcfjira\AppData\Roaming\npm\node_modules\bower\lib\core\ResolveCache.js:284:31
    at Array.sort (native)
    at C:\Users\wfcfjira\AppData\Roaming\npm\node_modules\bower\lib\core\ResolveCache.js:272:24
    at _fulfilled (C:\Users\wfcfjira\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:798:54)
    at self.promiseDispatch.done (C:\Users\wfcfjira\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:827:30)
    at Promise.promise.promiseDispatch (C:\Users\wfcfjira\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:760
:13)
    at C:\Users\wfcfjira\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:574:44
    at flush (C:\Users\wfcfjira\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:108:17)

Console trace:
Trace
    at StandardRenderer.error (C:\Users\wfcfjira\AppData\Roaming\npm\node_modules\bower\lib\renderers\StandardRenderer.j
s:74:17)
    at Logger.updateNotifier.packageName (C:\Users\wfcfjira\AppData\Roaming\npm\node_modules\bower\bin\bower:109:18)
    at Logger.EventEmitter.emit (events.js:95:17)
    at Logger.emit (C:\Users\wfcfjira\AppData\Roaming\npm\node_modules\bower\node_modules\bower-logger\lib\Logger.js:29:
39)
    at C:\Users\wfcfjira\AppData\Roaming\npm\node_modules\bower\lib\commands\cache\clean.js:45:16
    at _rejected (C:\Users\wfcfjira\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:808:24)
    at C:\Users\wfcfjira\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:834:30
    at Promise.when (C:\Users\wfcfjira\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:1079:31)
    at Promise.promise.promiseDispatch (C:\Users\wfcfjira\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:752
:41)
    at C:\Users\wfcfjira\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:574:44

System info:
Bower version: 1.2.6
Node version: 0.10.26
OS: Windows_NT 6.1.7601 x64
```

**Comment by sheerun** [comment]
@eggers I added Windows CI support for bower. I encourage you to create failing test.

**Comment by sheerun** [comment]
Bower 1.6.2 got improved supports for removing files (it tries to chmod 777 them as a fallback). Maybe it helps.
