### ISSUE TITLE
EPERM, unlink ....\AppData\...\bower\...tar.gz

### ISSUE THREAD

**Issue by adam-lynch** [bower/bower#1446]
I keep getting errors like `Error: EPERM, unlink 'C:\Users\Adam\AppData\Local\Temp\ID100322-Adam\bower\knockoutjs-5212-xRP6VW\archive.tar.gz'` when trying to `bower i`. I upgraded to version 1.3.8, if that makes a difference.

``` shell
>bower i       
bower emoji-images#*        not-cached git://github.com/HenrikJoreteg/emoji-images.git#*
bower emoji-images#*           resolve git://github.com/HenrikJoreteg/emoji-images.git#*
bower cornify#*             not-cached git://github.com/cornify/cornify.git#*
bower cornify#*                resolve git://github.com/cornify/cornify.git#*
bower momentjs#~2.5.1       not-cached git://github.com/moment/moment.git#~2.5.1
bower momentjs#~2.5.1          resolve git://github.com/moment/moment.git#~2.5.1
bower mousetrap#~1.4.6      not-cached git://github.com/ccampbell/mousetrap.git#~1.4.6
bower mousetrap#~1.4.6         resolve git://github.com/ccampbell/mousetrap.git#~1.4.6
bower jquery-autosize#~1.18.7       not-cached git://github.com/jackmoore/autosize.git#~1.18.7
bower jquery-autosize#~1.18.7          resolve git://github.com/jackmoore/autosize.git#~1.18.7
bower knockoutjs#*                  not-cached git://github.com/knockout/knockout.git#*
bower knockoutjs#*                     resolve git://github.com/knockout/knockout.git#*
bower blueimp-file-upload#~9.5.7    not-cached git://github.com/blueimp/jQuery-File-Upload.git#~9.5.7
bower blueimp-file-upload#~9.5.7       resolve git://github.com/blueimp/jQuery-File-Upload.git#~9.5.7
bower pretty-bytes#~0.1.1           not-cached git://github.com/sindresorhus/pretty-bytes.git#~0.1.1
bower pretty-bytes#~0.1.1              resolve git://github.com/sindresorhus/pretty-bytes.git#~0.1.1
bower ladda#~0.9.3                  not-cached git://github.com/hakimel/Ladda.git#~0.9.3
bower ladda#~0.9.3                     resolve git://github.com/hakimel/Ladda.git#~0.9.3
bower jquery-typing#~0.2.0              cached https://github.com/narfdotpl/jquery-typing.git#0.2.0
bower jquery-typing#~0.2.0            validate 0.2.0 against https://github.com/narfdotpl/jquery-typing.git#~0.2.0
bower jquery#~2.1.0                     cached git://github.com/jquery/jquery.git#2.1.1
bower jquery#~2.1.0                   validate 2.1.1 against git://github.com/jquery/jquery.git#~2.1.0
bower marked#~0.3.2                     cached git://github.com/chjj/marked.git#0.3.2
bower marked#~0.3.2                   validate 0.3.2 against git://github.com/chjj/marked.git#~0.3.2
bower jade#~1.3.1                       cached git://github.com/visionmedia/jade.git#1.3.1
bower jade#~1.3.1                     validate 1.3.1 against git://github.com/visionmedia/jade.git#~1.3.1
bower imagesloaded#~3.1.5               cached git://github.com/desandro/imagesloaded.git#3.1.8
bower imagesloaded#~3.1.5             validate 3.1.8 against git://github.com/desandro/imagesloaded.git#~3.1.5
bower Steady.js#~1.1.0                  cached git://github.com/lafikl/steady.js.git#1.1.0
bower Steady.js#~1.1.0                validate 1.1.0 against git://github.com/lafikl/steady.js.git#~1.1.0
bower jquery.atwho#~0.5.0               cached git://github.com/ichord/At.js.git#0.5.0
bower jquery.atwho#~0.5.0             validate 0.5.0 against git://github.com/ichord/At.js.git#~0.5.0
bower pretty-bytes#~0.1.1             download https://github.com/sindresorhus/pretty-bytes/archive/0.1.2.tar.gz
bower emoji-images#*                  checkout master
bower cornify#*                       checkout master
bower Caret.js#>= 0.1.0             not-cached git://github.com/ichord/Caret.js.git#>= 0.1.0
bower Caret.js#>= 0.1.0                resolve git://github.com/ichord/Caret.js.git#>= 0.1.0
bower jquery#>=1.7.0                    cached git://github.com/jquery/jquery.git#2.1.1
bower jquery#>=1.7.0                  validate 2.1.1 against git://github.com/jquery/jquery.git#>=1.7.0
bower blueimp-file-upload#~9.5.7      download https://github.com/blueimp/jQuery-File-Upload/archive/9.5.8.tar.gz
bower mousetrap#~1.4.6                download https://github.com/ccampbell/mousetrap/archive/1.4.6.tar.gz
bower Caret.js#>= 0.1.0               download https://github.com/ichord/Caret.js/archive/v0.1.0.tar.gz
bower ladda#~0.9.3                    download https://github.com/hakimel/Ladda/archive/0.9.4.tar.gz
bower eventEmitter#4.x              not-cached git://github.com/Wolfy87/EventEmitter.git#4.x
bower eventEmitter#4.x                 resolve git://github.com/Wolfy87/EventEmitter.git#4.x
bower eventie#>=1.0.4 <2            not-cached git://github.com/desandro/eventie.git#>=1.0.4 <2
bower eventie#>=1.0.4 <2               resolve git://github.com/desandro/eventie.git#>=1.0.4 <2
bower knockoutjs#*                    download https://github.com/knockout/knockout/archive/v3.1.0.tar.gz
bower momentjs#~2.5.1                 download https://github.com/moment/moment/archive/2.5.1.tar.gz
bower eventie#>=1.0.4 <2              download https://github.com/desandro/eventie/archive/v1.0.5.tar.gz
bower eventEmitter#4.x                download https://github.com/Wolfy87/EventEmitter/archive/v4.2.7.tar.gz
bower pretty-bytes#~0.1.1                retry Download of https://github.com/sindresorhus/pretty-bytes/archive/0.1.2.tar.gz failed with ECONNRESET, retrying in 1.8s
bower knockoutjs#*                       retry Download of https://github.com/knockout/knockout/archive/v3.1.0.tar.gz failed with EHTTP, trying with git..
bower cornify#*                   invalid-meta cornify is missing "main" entry in bower.json
bower cornify#*                   invalid-meta cornify is missing "ignore" entry in bower.json
bower cornify#*                       resolved git://github.com/cornify/cornify.git#e56b3e978c
bower momentjs#~2.5.1                    retry Download of https://github.com/moment/moment/archive/2.5.1.tar.gz failed with ECONNRESET, retrying in 1.8s
bower Caret.js#>= 0.1.0                  retry Download of https://github.com/ichord/Caret.js/archive/v0.1.0.tar.gz failed with EHTTP, trying with git..
bower eventie#>=1.0.4 <2                 retry Download of https://github.com/desandro/eventie/archive/v1.0.5.tar.gz failed with ECONNRESET, retrying in 1.1s
bower eventEmitter#4.x                   retry Download of https://github.com/Wolfy87/EventEmitter/archive/v4.2.7.tar.gz failed with EHTTP, trying with git..
bower ladda#~0.9.3                       retry Download of https://github.com/hakimel/Ladda/archive/0.9.4.tar.gz failed with EHTTP, trying with git..
bower blueimp-file-upload#~9.5.7         retry Download of https://github.com/blueimp/jQuery-File-Upload/archive/9.5.8.tar.gz failed with EHTTP, trying with git..
bower jquery-autosize#~1.18.7         download https://github.com/jackmoore/autosize/archive/1.18.9.tar.gz
bower eventie#>=1.0.4 <2                 retry Download of https://github.com/desandro/eventie/archive/v1.0.5.tar.gz failed with EHTTP, trying with git..
bower mousetrap#~1.4.6                   retry Download of https://github.com/ccampbell/mousetrap/archive/1.4.6.tar.gz failed with EHTTP, trying with git..
bower emoji-images#*              invalid-meta emoji-images is missing "main" entry in bower.json
bower emoji-images#*              invalid-meta emoji-images is missing "ignore" entry in bower.json
bower emoji-images#*                  resolved git://github.com/HenrikJoreteg/emoji-images.git#154d7641a7
bower pretty-bytes#~0.1.1                retry Download of https://github.com/sindresorhus/pretty-bytes/archive/0.1.2.tar.gz failed with ECONNRESET, retrying in 2.3s
bower jquery-autosize#~1.18.7            retry Download of https://github.com/jackmoore/autosize/archive/1.18.9.tar.gz failed with ECONNRESET, retrying in 1.3s
bower knockoutjs#*                       EPERM EPERM, unlink 'C:\Users\Adam\AppData\Local\Temp\ID100322-Adam\bower\knockoutjs-5212-xRP6VW\archive.tar.gz'

Stack trace:
Error: EPERM, unlink 'C:\Users\Adam\AppData\Local\Temp\ID100322-Adam\bower\knockoutjs-5212-xRP6VW\archive.tar.gz'

Console trace:
Trace
    at StandardRenderer.error (C:\Users\Adam\AppData\Roaming\npm\node_modules\bower\lib\renderers\StandardRenderer.js:72:17)
    at Logger.<anonymous> (C:\Users\Adam\AppData\Roaming\npm\node_modules\bower\bin\bower:111:22)
    at Logger.EventEmitter.emit (events.js:95:17)
    at Logger.emit (C:\Users\Adam\AppData\Roaming\npm\node_modules\bower\node_modules\bower-logger\lib\Logger.js:29:39)
    at C:\Users\Adam\AppData\Roaming\npm\node_modules\bower\lib\commands\index.js:40:20
    at _rejected (C:\Users\Adam\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:797:24)
    at C:\Users\Adam\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:823:30
    at Promise.when (C:\Users\Adam\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:1035:31)
    at Promise.promise.promiseDispatch (C:\Users\Adam\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:741:41)
    at C:\Users\Adam\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:557:44

System info:
Bower version: 1.3.8
Node version: 0.10.26
OS: Windows_NT 6.2.9200 x64
```

**Comment by lljxx1** [comment]
I got this error too, maybe you "C:/" disk don't have enough space
