### ISSUE TITLE
unexpected end of input on install/update

### ISSUE THREAD

**Issue by ain** [bower/bower#1551]
Time to time `bower install` and `bower update` throw up with `Unexpected end of input` error. On local and remote CI machine, both running different versions of OS X Maverick.

`bower.json` is not malformatted, but there is a dependency to a private Git repository on HTTPS which authenticates with `.netrc` file. The error is rare and is not always reproducible.

Example trace:

```
bower                                     error Unexpected end of input

Stack trace:
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /Users/ain/.nvm/v0.10.31/lib/node_modules/bower/lib/core/Manager.js:185:37
    at _fulfilled (/Users/ain/.nvm/v0.10.31/lib/node_modules/bower/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/ain/.nvm/v0.10.31/lib/node_modules/bower/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/ain/.nvm/v0.10.31/lib/node_modules/bower/node_modules/q/q.js:749:13)
    at /Users/ain/.nvm/v0.10.31/lib/node_modules/bower/node_modules/q/q.js:557:44
    at flush (/Users/ain/.nvm/v0.10.31/lib/node_modules/bower/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:419:13)

Console trace:
Trace
    at StandardRenderer.error (/Users/ain/.nvm/v0.10.31/lib/node_modules/bower/lib/renderers/StandardRenderer.js:82:17)
    at Logger.<anonymous> (/Users/ain/.nvm/v0.10.31/lib/node_modules/bower/bin/bower:110:22)
    at Logger.emit (events.js:95:17)
    at Logger.emit (/Users/ain/.nvm/v0.10.31/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /Users/ain/.nvm/v0.10.31/lib/node_modules/bower/lib/commands/index.js:40:20
    at _rejected (/Users/ain/.nvm/v0.10.31/lib/node_modules/bower/node_modules/q/q.js:797:24)
    at /Users/ain/.nvm/v0.10.31/lib/node_modules/bower/node_modules/q/q.js:823:30
    at Promise.when (/Users/ain/.nvm/v0.10.31/lib/node_modules/bower/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch (/Users/ain/.nvm/v0.10.31/lib/node_modules/bower/node_modules/q/q.js:741:41)
    at /Users/ain/.nvm/v0.10.31/lib/node_modules/bower/node_modules/q/q.js:557:44

System info:
Bower version: 1.3.11
Node version: 0.10.31
OS: Darwin 13.4.0 x64

shell returned 1
```

**Comment by 0r1g** [comment]
Me too.

```
bower datatables#>=1.8.0                      install datatables#1.10.4
bower es5-shim#2.3.0                          install es5-shim#2.3.0
bower                                           error Unexpected end of input

Stack trace:
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /Users/tokenlabdev/.nvm/v0.10.35/lib/node_modules/bower/lib/core/Manager.js:185:37
    at _fulfilled (/Users/tokenlabdev/.nvm/v0.10.35/lib/node_modules/bower/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/tokenlabdev/.nvm/v0.10.35/lib/node_modules/bower/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/tokenlabdev/.nvm/v0.10.35/lib/node_modules/bower/node_modules/q/q.js:749:13)
    at /Users/tokenlabdev/.nvm/v0.10.35/lib/node_modules/bower/node_modules/q/q.js:557:44
    at flush (/Users/tokenlabdev/.nvm/v0.10.35/lib/node_modules/bower/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:442:13)

Console trace:
Trace
    at StandardRenderer.error (/Users/tokenlabdev/.nvm/v0.10.35/lib/node_modules/bower/lib/renderers/StandardRenderer.js:82:17)
    at Logger.<anonymous> (/Users/tokenlabdev/.nvm/v0.10.35/lib/node_modules/bower/bin/bower:110:22)
    at Logger.emit (events.js:95:17)
    at Logger.emit (/Users/tokenlabdev/.nvm/v0.10.35/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /Users/tokenlabdev/.nvm/v0.10.35/lib/node_modules/bower/lib/commands/index.js:40:20
    at _rejected (/Users/tokenlabdev/.nvm/v0.10.35/lib/node_modules/bower/node_modules/q/q.js:797:24)
    at /Users/tokenlabdev/.nvm/v0.10.35/lib/node_modules/bower/node_modules/q/q.js:823:30
    at Promise.when (/Users/tokenlabdev/.nvm/v0.10.35/lib/node_modules/bower/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch (/Users/tokenlabdev/.nvm/v0.10.35/lib/node_modules/bower/node_modules/q/q.js:741:41)
    at /Users/tokenlabdev/.nvm/v0.10.35/lib/node_modules/bower/node_modules/q/q.js:557:44

System info:
Bower version: 1.3.12
Node version: 0.10.35
OS: Darwin 14.0.0 x64
Build step 'Executar shell' marked build as failure
Finished: FAILURE
```

**Comment by christracey** [comment]
Same...

```
bower                                                       error Unexpected end of input
Stack trace:
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /usr/lib/node_modules/bower/lib/core/Manager.js:185:37
    at _fulfilled (/usr/lib/node_modules/bower/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/lib/node_modules/bower/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/bower/node_modules/q/q.js:796:13)
    at /usr/lib/node_modules/bower/node_modules/q/q.js:604:44
    at runSingle (/usr/lib/node_modules/bower/node_modules/q/q.js:137:13)
    at flush (/usr/lib/node_modules/bower/node_modules/q/q.js:125:13)
    at process._tickCallback (node.js:419:13)

Console trace:
Error
    at StandardRenderer.error (/usr/lib/node_modules/bower/lib/renderers/StandardRenderer.js:82:37)
    at Logger.<anonymous> (/usr/lib/node_modules/bower/bin/bower:110:22)
    at Logger.emit (events.js:95:17)
    at Logger.emit (/usr/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/lib/node_modules/bower/lib/commands/index.js:45:20
    at _rejected (/usr/lib/node_modules/bower/node_modules/q/q.js:844:24)
    at /usr/lib/node_modules/bower/node_modules/q/q.js:870:30
    at Promise.when (/usr/lib/node_modules/bower/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/bower/node_modules/q/q.js:788:41)
    at /usr/lib/node_modules/bower/node_modules/q/q.js:604:44
System info:
Bower version: 1.4.1
Node version: 0.10.31
OS: Linux 3.13.0-30-generic x64
```

**Comment by okjake** [comment]
I've been looking at this, and can see where the problem is arising, but I don't have enough knowledge of Bower internals to be confident of a fix.

This line is the culprit https://github.com/bower/bower/blob/master/lib/core/Manager.js#L185
Sometimes `contents` is an empty buffer, which triggers this error. This seems to happen sometimes when install is called multiple times for the same package - perhaps an issue with fs.writeFile and fs.readFile overlapping.

It's easy to catch the empty buffer and return early - and this fixes the issue for me - but what are the implications of ._target and ._originalSource not being set in .bower.json sometimes?

**Comment by jacopotarantino** [comment]
Ping. This has been breaking my builds really badly and the inconsistent presentation of the bug has cost a few developers about 2 days of time so far. Would really love to see a fix.

**Comment by ain** [comment]
Reproduced in `1.7.9`, current latest stable.

**Comment by ain** [comment]
The issues seems to relate to defining semver's `>=` range for jQuery. As soon as this is removed, the error can not be reproduced.

**Comment by ain** [comment]
*Correction*: semver `>=` range removed, but reproduced nevertheless. Happens at random, but seems to retain it's false behaviour once it has happened, which brought me to cache.

Currently, for a clean install, I'm using the following:

```sh
rm -rf bower_components/ && bower cache clean && bower i
```

and so far it has delivered a dozen of times I've tested it.

**Comment by ain** [comment]
__Steps to reproduce__:

1. Create a private Git project so it complies with following `bower.json`:

  ```json
 {
    "name": "private-component",
    "private": true,
    "dependencies": {
      "modernizr": "~3.3.1",
      "jquery": ">=1.11.1 <3.0.0",
      "jqueryui": ">=1.11.1 <2.0.0",
      "accounting.js": "~0.4.1",
      "moment": "~2.11.2"
    },
    "devDependencies": {
      "chai": "~3.5.0",
      "mocha": "~2.4.5"
    },
    "main": "src/component.js",
    "ignore": [
      "**/.*",
      "test/",
      "Gruntfile.js"
    ],
    "authors": [
      "Your Email <email@email.com>"
    ],
    "repository": {
      "type": "git",
      "url": "<private repo>.git"
    },
    "license": "MIT"
  }
```
2. Tag a release on `private-repo`
2. Create another project that uses the private project complying with following `bower.json`:
  
  ```json
 {
    "name": "private-project",
    "version": "1.7.1",
    "dependencies": {
      "modernizr": "~3.3.1",
      "jQuery": "~2.1.1",
      "hammerjs": "2.0.1",
      "csswizardry-grids": "~2.2.0",
      "slick-carousel": "~1.3.7",
      "private-component": "<private repo>#<tag>"
    },
    "devDependencies": {
      "Cortana": "1.2.6"
    }
  }
```

__What happens__:  installation breaks at moment.js:

  ```
bower moment#~2.11.2                    install moment#2.11.2
bower                                     error Unexpected token e

Stack trace:
SyntaxError: Unexpected token e
    at Object.parse (native)
    at /Users/ain/.nvm/versions/node/v5.10.1/lib/node_modules/bower/lib/core/Manager.js:209:37
    at _fulfilled (/Users/ain/.nvm/versions/node/v5.10.1/lib/node_modules/bower/lib/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/ain/.nvm/versions/node/v5.10.1/lib/node_modules/bower/lib/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/ain/.nvm/versions/node/v5.10.1/lib/node_modules/bower/lib/node_modules/q/q.js:796:13)
    at /Users/ain/.nvm/versions/node/v5.10.1/lib/node_modules/bower/lib/node_modules/q/q.js:604:44
    at runSingle (/Users/ain/.nvm/versions/node/v5.10.1/lib/node_modules/bower/lib/node_modules/q/q.js:137:13)
    at flush (/Users/ain/.nvm/versions/node/v5.10.1/lib/node_modules/bower/lib/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Console trace:
Error
    at StandardRenderer.error (/Users/ain/.nvm/versions/node/v5.10.1/lib/node_modules/bower/lib/renderers/StandardRenderer.js:81:37)
    at Logger.<anonymous> (/Users/ain/.nvm/versions/node/v5.10.1/lib/node_modules/bower/lib/bin/bower.js:110:26)
    at emitOne (events.js:90:13)
    at Logger.emit (events.js:182:7)
    at Logger.emit (/Users/ain/.nvm/versions/node/v5.10.1/lib/node_modules/bower/lib/node_modules/bower-logger/lib/Logger.js:29:39)
    at /Users/ain/.nvm/versions/node/v5.10.1/lib/node_modules/bower/lib/commands/index.js:48:20
    at _rejected (/Users/ain/.nvm/versions/node/v5.10.1/lib/node_modules/bower/lib/node_modules/q/q.js:844:24)
    at /Users/ain/.nvm/versions/node/v5.10.1/lib/node_modules/bower/lib/node_modules/q/q.js:870:30
    at Promise.when (/Users/ain/.nvm/versions/node/v5.10.1/lib/node_modules/bower/lib/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/Users/ain/.nvm/versions/node/v5.10.1/lib/node_modules/bower/lib/node_modules/q/q.js:788:41)
System info:
Bower version: 1.7.9
Node version: 5.10.1
OS: Darwin 15.4.0 x64
```

__What should happen__:  installation should not break, valid version ranges should work.

**Comment by ain** [comment]
So the cause here is that the `private-component` accepts jQuery higher than the `private-project`, causing the failure.

**Comment by golokeshpatra45** [comment]
@ain 
I am on a Debian VM Machine
I used to get similar problem, (not the same though),  

I just copied the whole repo to my desktop where I didn't require any kind of access issues and voila, it works . 

bower install worked successfully, 

The problem I was facing previously was  - 

**Stack trace:
/usr/lib/node_modules/bower/lib/node_modules/fstream/lib/dir-writer.js:35:25
/usr/lib/node_modules/bower/lib/node_modules/mkdirp/index.js:46:53
FSReqWrap.oncomplete (fs.js:114:15)

Console trace:
Error
    at StandardRenderer.error (/usr/lib/node_modules/bower/lib/renderers/StandardRenderer.js:81:37)
    at Logger.<anonymous> (/usr/lib/node_modules/bower/lib/bin/bower.js:110:26)
    at emitOne (events.js:96:13)
    at Logger.emit (events.js:191:7)
    at Logger.emit (/usr/lib/node_modules/bower/lib/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/lib/node_modules/bower/lib/commands/index.js:48:20
    at _rejected (/usr/lib/node_modules/bower/lib/node_modules/q/q.js:844:24)
    at /usr/lib/node_modules/bower/lib/node_modules/q/q.js:870:30
    at Promise.when (/usr/lib/node_modules/bower/lib/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/bower/lib/node_modules/q/q.js:788:41)
System info:
Bower version: 1.8.0
Node version: 7.10.0
OS: Linux 3.16.0-4-amd64 x64**

--------------------------------------------------------------------------------------------------------------

I hope it solves the issue, else we will have to look for some other solution.

**Comment by matmiz** [comment]
Hey, sorry to bring this up again. 
We're using version 1.4.1 ,and experiencing the exact same thing. 
It's very intermittent, but sometimes we need to build the code 4 times before it actually passes. 

we're getting the SyntaxError: Unexpected end of JSON input from the Manager.js file. 
Has anyone managed to find a way around it?

**Comment by meranamvarun** [comment]
I am facing the same issue

**Comment by sheerun** [comment]
This issue got stale. If it still bothers someone, please create another one
