### ISSUE TITLE
Artifactory resolver

### ISSUE THREAD

**Issue by jbaruch** [bower/bower#1635]
Hi guys,
we (JFrog) would like to contribute a resolver that allows download packages from Artifactory.
What do you say? Will you be interested in such a contribution?

**Comment by sheerun** [comment]
I'd pass for now. Every resolver requires huge maintenance from bower team. GitHub in current version & Bitbucket in next version should be enough.

What we need is some kind of plug-in system for resolvers. If you'd manage to implement it, you could maintain Artifactory resolver as bower plugin.

If you'll decide to implement it, please post first an issue with preliminary API ideas, so we can discuss it.

I can also support you with planning, just ping me on gitter.

**Comment by kryptt** [comment]
I'm trying to use bower with artifactory myself, and with the current http resolver, I'm forced to store username + password in my bower.json  which is terrible practice.. :/

**Comment by liorhson** [comment]
Hi @kryptt,
This days we are working on adding a dedicated Artifactory resolver in Bower, together with the Bower team.

I hope it will be soon.

**Comment by brunano21** [comment]
Hi all,

I have Artifactory Pro and I have configured the bower repo as explained here, https://www.jfrog.com/confluence/display/RTF/Bower+Repositories
However I'm not able to get any package, always getting `Package not found`

    $ bower-art install bootstrap --verbose
    bower bootstrap#*           not-cached art://twbs/bootstrap#*
    bower bootstrap#*              resolve art://twbs/bootstrap#*
    bower bootstrap#*             response Package not found

    Additional error details:
    Package not found

    Stack trace:
    Error: Package not found
        at createError (C:\Users\<User>\AppData\Roaming\npm\node_modules\bower-art\lib\util\createError.js:4:15)
        at C:\Users\<User>\AppData\Roaming\npm\node_modules\bower-art-resolver\lib\index.js:110:39
        at _rejected (C:\Users\<User>\AppData\Roaming\npm\node_modules\bower-art-resolver\node_modules\q\q.js:797:24)
        at C:\Users\<User>\AppData\Roaming\npm\node_modules\bower-art-resolver\node_modules\q\q.js:823:30
        at Promise.when (C:\Users\<User>\AppData\Roaming\npm\node_modules\bower-art-resolver\node_modules\q\q.js:1035:31)
        at Promise.promise.promiseDispatch (C:\Users\<User>\AppData\Roaming\npm\node_modules\bower-art-resolver\node_modules\q\q.js:741:41)
        at C:\Users\<User>\AppData\Roaming\npm\node_modules\bower-art-resolver\node_modules\q\q.js:557:44
        at flush (C:\Users\<User>\AppData\Roaming\npm\node_modules\bower-art-resolver\node_modules\q\q.js:108:17)
    From previous event:
        at ArtifactoryResolver.Resolver.resolve (C:\Users\<User>\AppData\Roaming\npm\node_modules\bower-art\lib\core\resolvers\Resolver.js:100:6)
        at PackageRepository._resolve (C:\Users\<User>\AppData\Roaming\npm\node_modules\bower-art\lib\core\PackageRepository.js:175:21)
        at C:\Users\<User>\AppData\Roaming\npm\node_modules\bower-art\lib\core\PackageRepository.js:77:29

    Console trace:
    Error
        at StandardRenderer.error (C:\Users\<User>\AppData\Roaming\npm\node_modules\bower-    art\lib\renderers\StandardRenderer.js:82:37)
        at Logger.<anonymous> (C:\Users\<User>\AppData\Roaming\npm\node_modules\bower-art\bin\bower-art:110:22)
        at Logger.emit (events.js:107:17)
        at Logger.emit (C:\Users\<User>\AppData\Roaming\npm\node_modules\bower-art\node_modules\bower-logger\lib\Logger.js:29:39)
        at C:\Users\<User>\AppData\Roaming\npm\node_modules\bower-art\lib\commands\index.js:45:20
        at _rejected (C:\Users\<User>\AppData\Roaming\npm\node_modules\bower-art\node_modules\q\q.js:844:24)
        at C:\Users\<User>\AppData\Roaming\npm\node_modules\bower-art\node_modules\q\q.js:870:30
        at Promise.when (C:\Users\<User>\AppData\Roaming\npm\node_modules\bower-art\node_modules\q\q.    js:1122:31)
        at Promise.promise.promiseDispatch (C:\Users\<User>\AppData\Roaming\npm\node_modules\bower-art\node_modules\q\q.js:788:41)
    at C:\Users\<User>\AppData\Roaming\npm\node_modules\bower-art\node_modules\q\q.js:604:44
    System info:
    Bower version: 1.0.5-beta
    Node version: 0.12.2
    OS: Windows_NT 6.1.7601 x64

And this is my `.bowerrc`:

    {
        "directory": "app/components/",
        "analytics": false,
        "timeout": 120000,
        "registry": "http://<my.server.address>/api/bower/my-bower-repo"
    }


Any suggestion? 
Thanks

**Comment by liorhson** [comment]
Hey,
I could not reproduce your issue, it`s probable related to Artifactory configuration. The best way to figure out the problem will be to look at Artifactory logs, specially the "request" log.
You can contact me via my email, and send me the logs also

Cheers

**Comment by nvellon** [comment]
Hey guys,

I've been looking at the jfrog implementation and it seems "very beta". Do you guys have any plans on moving forward on a proper resolver that works into mainstream bower? 

I mean, it seems to work only with bower's fork and therefore loosing every new feature and/or bugfixing from the mainstream bower... just for mentioning one problem. Another example of missing features: lack of version range resolution.

It is a not bad idea having an Artifactory Resolver as a bower plugin and I would be happy to contribute to a more "serious" aproach if you guys are willing to do so.

**Comment by Rorkal** [comment]
Hi !
I have the same error as @brunano21 :

```bash
bower-art install --verbose

[...]
bower oclazyload#1.0.2          cached art://ocombe/ocLazyLoad#e-tag:fb7a86886b
bower oclazyload#1.0.2        validate e-tag:fb7a86886b against art://ocombe/ocLazyLoad#1.0.2
[...]
bower angular#>=1.2.x <=1.4.x               response Unexpected end of input

Additional error details:
Unexpected end of input

Stack trace:
Error: Unexpected end of input
    at createError (C:\Users\alexandre.hamon\AppData\Roaming\npm\node_modules\bower-art\lib\util\createError.js:4:15)
    at C:\Users\alexandre.hamon\AppData\Roaming\npm\node_modules\bower-art-resolver\lib\index.js:110:39
    at _rejected (C:\Users\alexandre.hamon\AppData\Roaming\npm\node_modules\bower-art-resolver\node_modules\q\q.js:797:24)
    at C:\Users\alexandre.hamon\AppData\Roaming\npm\node_modules\bower-art-resolver\node_modules\q\q.js:823:30
    at Promise.when (C:\Users\alexandre.hamon\AppData\Roaming\npm\node_modules\bower-art-resolver\node_modules\q\q.js:1035:31)
    at Promise.promise.promiseDispatch (C:\Users\alexandre.hamon\AppData\Roaming\npm\node_modules\bower-art-resolver\node_modules\q\q.js:741:41)
    at C:\Users\alexandre.hamon\AppData\Roaming\npm\node_modules\bower-art-resolver\node_modules\q\q.js:557:44
    at flush (C:\Users\alexandre.hamon\AppData\Roaming\npm\node_modules\bower-art-resolver\node_modules\q\q.js:108:17)
From previous event:
    at ArtifactoryResolver.Resolver.resolve (C:\Users\alexandre.hamon\AppData\Roaming\npm\node_modules\bower-art\lib\core\resolvers\Resolver.js:100:6)
    at PackageRepository._resolve (C:\Users\alexandre.hamon\AppData\Roaming\npm\node_modules\bower-art\lib\core\PackageRepository.js:175:21)
    at C:\Users\alexandre.hamon\AppData\Roaming\npm\node_modules\bower-art\lib\core\PackageRepository.js:106:29
    at _fulfilled (C:\Users\alexandre.hamon\AppData\Roaming\npm\node_modules\bower-art-resolver\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\alexandre.hamon\AppData\Roaming\npm\node_modules\bower-art-resolver\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\alexandre.hamon\AppData\Roaming\npm\node_modules\bower-art-resolver\node_modules\q\q.js:749:13)
    at C:\Users\alexandre.hamon\AppData\Roaming\npm\node_modules\bower-art-resolver\node_modules\q\q.js:557:44
    at flush (C:\Users\alexandre.hamon\AppData\Roaming\npm\node_modules\bower-art-resolver\node_modules\q\q.js:108:17)

Console trace:
Error
    at StandardRenderer.error (C:\Users\alexandre.hamon\AppData\Roaming\npm\node_modules\bower-art\lib\renderers\StandardRenderer.js:82:37)
    at Logger.<anonymous> (C:\Users\alexandre.hamon\AppData\Roaming\npm\node_modules\bower-art\bin\bower-art:110:22)
    at Logger.emit (events.js:107:17)
    at Logger.emit (C:\Users\alexandre.hamon\AppData\Roaming\npm\node_modules\bower-art\node_modules\bower-logger\lib\Logger.js:29:39)
    at C:\Users\alexandre.hamon\AppData\Roaming\npm\node_modules\bower-art\lib\commands\index.js:45:20
    at _rejected (C:\Users\alexandre.hamon\AppData\Roaming\npm\node_modules\bower-art\node_modules\q\q.js:844:24)
    at C:\Users\alexandre.hamon\AppData\Roaming\npm\node_modules\bower-art\node_modules\q\q.js:870:30
    at Promise.when (C:\Users\alexandre.hamon\AppData\Roaming\npm\node_modules\bower-art\node_modules\q\q.js:1122:31)
    at Promise.promise.promiseDispatch (C:\Users\alexandre.hamon\AppData\Roaming\npm\node_modules\bower-art\node_modules\q\q.js:788:41)
    at C:\Users\alexandre.hamon\AppData\Roaming\npm\node_modules\bower-art\node_modules\q\q.js:604:44
System info:
Bower version: 1.0.5-beta
Node version: 0.12.7
OS: Windows_NT 6.1.7601 x64
```
When looking at artifactory's logs, i can see that some request are responding 404 errors

```
20150825152831|752|REQUEST|192.168.247.185|angular_rw|HEAD|/api/bower/bower-repository/binaries/angular/bower-angular.git/%3E%3D1.2.x%20%3C%3D1.4.x|HTTP/1.1|404|0
20150825152831|803|REQUEST|192.168.247.185|angular_rw|HEAD|/api/bower/bower-repository/binaries/angular/bower-angular.git/%3E%3D1.2.16%20%3C%3D1.3.16|HTTP/1.1|404|0
20150825152831|814|REQUEST|192.168.247.185|angular_rw|HEAD|/api/bower/bower-repository/binaries/angular/bower-angular.git/~1.3.x|HTTP/1.1|404|0
20150825152831|545|REQUEST|192.168.247.185|angular_rw|GET|/api/bower/bower-repository/binaries/angular/bower-angular.git/%3E%3D1.2.x%20%3C%3D1.4.x|HTTP/1.1|404|0
20150825152831|500|REQUEST|192.168.247.185|angular_rw|GET|/api/bower/bower-repository/binaries/angular/bower-angular.git/~1.3.x|HTTP/1.1|404|0
20150825152831|531|REQUEST|192.168.247.185|angular_rw|GET|/api/bower/bower-repository/binaries/angular/bower-angular.git/%3E%3D1.2.16%20%3C%3D1.3.16|HTTP/1.1|404|0
20150825152832|368|REQUEST|192.168.247.185|angular_rw|GET|/api/bower/bower-repository/binaries/angular/bower-angular.git/~1.3.x|HTTP/1.1|404|0
20150825152832|400|REQUEST|192.168.247.185|angular_rw|GET|/api/bower/bower-repository/binaries/angular/bower-angular.git/%3E%3D1.2.x%20%3C%3D1.4.x|HTTP/1.1|404|0
20150825152832|381|REQUEST|192.168.247.185|angular_rw|GET|/api/bower/bower-repository/binaries/angular/bower-angular.git/%3E%3D1.2.16%20%3C%3D1.3.16|HTTP/1.1|404|0
```

Seems like bower-art doesn't handle syntax as angular#>=1.2.x <=1.4.x, angular#~1.3.x or angular#>=1.2.16 <=1.3.16 ?

Some test shows me that GET on /api/bower/bower-repository/binaries/angular/bower-angular.git/~1.3.2 works fine when GET on /api/bower/bower-repository/binaries/angular/bower-angular.git/~1.3.x does not work and since these are dependencies of dependencies, there is no way i can change these version.

Does anyone ever had this problem?

**Comment by liorhson** [comment]
Hey,
Has from version 1.5.1 Bower supports [pluggable resolvers](http://bower.io/docs/pluggable-resolvers/), so in the next few weeks we'll publish a new version of Artifactory resolver, compatible with the new Bower version. 
Regarding your issue, the next Artifactory resolver will support range (ex. >=1.2.16 <=1.3.16) in versions.

Stay tuned

**Comment by Rorkal** [comment]
Hi @liorhson,
I hope next version will correct theses bug.

I did a dirty correction locally in order to make it work while waiting the next version.

Resolver.js:
```javascript
Resolver.prototype.resolve = function () {
    var that = this;

    // If already working, error out
    if (this._working) {
        return Q.reject(createError('Already working', 'EWORKING'));
    }

    this._working = true;
	
	that._logger.warn('INFO', 'Target is ' + this._target);
	this._target = this._target.replace('.x', '.1');
	if (this._target.indexOf("<=") != -1){
	this._target = this._target.substring(0, this._target.indexOf("<="));
	}
	that._logger.warn('INFO', 'Target changed to ' + this._target);
	[...]
```

**Comment by liorhson** [comment]
For now you can try to use the unoffical Bower Artifactory resolver version.
Steps to use Bower Artifactory resolver (until it will be published to npm) : 
1) Clone the resolver from git: git@github.com:JFrogDev/bower-art-resolver.git 
2) Install it on your local npm: "npm install -g" 
3) Make sure the Bower version is at least 1.5.0 

Info from Bower: http://bower.io/docs/pluggable-resolvers/

**Comment by Rorkal** [comment]
Thanks @liorhson, i tried your solution with bower 1.5.2, works great!

**Comment by cschuller** [comment]
Thanks @liorhson.

No need for a clone any more. How to setup is well documented in the README from JFrogDev/bower-art-resolver 

see: https://github.com/JFrogDev/bower-art-resolver
