### ISSUE TITLE
Bower Cache Commands return error

### ISSUE THREAD

**Issue by smithjw1** [bower/bower#1658]
Running bower cache <clean/list> returns the following error:

bower error         Invalid Version: 0.7.7.3

Stack trace:
TypeError: Invalid Version: 0.7.7.3
    at new SemVer (/usr/local/lib/node_modules/bower/node_modules/semver/semver.js:273:11)
    at Object.compare (/usr/local/lib/node_modules/bower/node_modules/semver/semver.js:460:10)
    at /usr/local/lib/node_modules/bower/lib/core/ResolveCache.js:294:31
    at Array.sort (native)
    at /usr/local/lib/node_modules/bower/lib/core/ResolveCache.js:282:24
    at _fulfilled (/usr/local/lib/node_modules/bower/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/bower/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/bower/node_modules/q/q.js:108:17)

Console trace:
Trace
    at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:82:17)
    at Logger.<anonymous> (/usr/local/lib/node_modules/bower/bin/bower:110:22)
    at Logger.emit (events.js:95:17)
    at Logger.emit (/usr/local/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/local/lib/node_modules/bower/lib/commands/index.js:40:20
    at _rejected (/usr/local/lib/node_modules/bower/node_modules/q/q.js:797:24)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:823:30
    at Promise.when (/usr/local/lib/node_modules/bower/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/node_modules/q/q.js:741:41)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:557:44

System info:
Bower version: 1.3.12
Node version: 0.10.33
OS: Darwin 14.0.0 x64

Node and bower installed via homebrew

**Comment by sheerun** [comment]
It's actually invalid semver :)

**Comment by samccone** [comment]
yep, closing as a non issue :+1:

**Comment by DOrlov77** [comment]
Yep - that is indeed issue. To fix you need to clean the bower cache manually. For Windows - just remove a folder: ```c:\Users\<your-name>\AppData\Local\bower\cache```
