### ISSUE TITLE
Define ~/.config location

### ISSUE THREAD

**Issue by iWader** [bower/bower#1695]
I have a user who does not have permissions to create directories in their home directory. 

I'm getting some errors when trying to bower install, is it possible for me to define the location of the .config directory from say `/.bowerrc` or something? As you can with the cache directory and such.

Ideally a solution that will apply to all users on the system.

```
$ bower install

Error: EACCES, permission denied '<snip>/.config'
    at Object.fs.mkdirSync (fs.js:647:18)
    at sync (/usr/local/lib/node_modules/bower/node_modules/mkdirp/index.js:70:13)
    at Function.sync (/usr/local/lib/node_modules/bower/node_modules/mkdirp/index.js:76:24)
    at Object.create.all.get (/usr/local/lib/node_modules/bower/node_modules/insight/node_modules/configstore/index.js:41:13)
    at Object.Configstore (/usr/local/lib/node_modules/bower/node_modules/insight/node_modules/configstore/index.js:27:44)
    at new Insight (/usr/local/lib/node_modules/bower/node_modules/insight/lib/index.js:26:34)
    at ensureInsight (/usr/local/lib/node_modules/bower/lib/util/analytics.js:26:19)
    at Object.setup (/usr/local/lib/node_modules/bower/lib/util/analytics.js:43:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/bower/bin/bower:72:11)
    at Module._compile (module.js:456:26)
```

**Comment by iWader** [comment]
I was able to solve this by setting the XDG_CONFIG_HOME environment variable.

See http://superuser.com/questions/365847/where-should-the-xdg-config-home-variable-be-defined
