### ISSUE TITLE
Error: EPERM, unlink with Jasmine after bower install

### ISSUE THREAD

**Issue by inane** [bower/bower#1710]
Hello,

I am having the next error trying to install Jasmine

Stack trace:
Error: EPERM, unlink 'C:\Users\ADMYUS~1\AppData\Local\Temp\SE.BSHG.COM-admYuste-ext\bower\jasmine-10416-TIurOd\archive.tar.gz'

Console trace:
Trace
    at StandardRenderer.error (C:\Users\admYuste-ext\AppData\Roaming\npm\node_modules\bower\lib\renderers\StandardRenderer.js:82:17)
    at Logger.<anonymous> (C:\Users\admYuste-ext\AppData\Roaming\npm\node_modules\bower\bin\bower:110:22)
    at Logger.emit (events.js:95:17)
    at Logger.emit (C:\Users\admYuste-ext\AppData\Roaming\npm\node_modules\bower\node_modules\bower-logger\lib\Logger.js:29:39)
    at C:\Users\admYuste-ext\AppData\Roaming\npm\node_modules\bower\lib\commands\index.js:40:20
    at _rejected (C:\Users\admYuste-ext\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:797:24)
    at C:\Users\admYuste-ext\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:823:30
    at Promise.when (C:\Users\admYuste-ext\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:1035:31)
    at Promise.promise.promiseDispatch (C:\Users\admYuste-ext\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:741:41)
    at C:\Users\admYuste-ext\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:557:44

System info:
Bower version: 1.3.12
Node version: 0.10.33
OS: Windows_NT 6.1.7601 ia32

Any clue??

Thank you in advance.

**Comment by sheerun** [comment]
Support questions are best asked on StackOverflow.

**Comment by ImanMh** [comment]
@sheerun it's seems to be in the right place, why did you closed the issue? isn't that an issue with bower?!

**Comment by sheerun** [comment]
@ImanMh It doesn't seem so. But if you have a way to reproduce, please write so.

**Comment by ImanMh** [comment]
ThanX @sheerun sure. 
@inane My problem was because my bower target directory permissions were changed, if you are using Mac or Linux try running bower as administrator to test if this is the cause of your problem: 
```
sudo bower install
```
If you are under windows just run your terminal as administrator. If that solved your problem (just like it did for me) this has nothing to do with bower and you need to fix your directory permission.
