### ISSUE TITLE
how to solve this problem .help me.

### ISSUE THREAD

**Issue by saran110313** [bower/bower#1718]
[36minfo  -[39m socket.io started
Matisse server listening on port 8000 in development mode
SyntaxError: Unexpected token (474:0)
    at raise (/home/local/IGSTDEV/saravanan_k/newworkspace/whiteBoard/WebContent/matisse-master/node_modules/jade/node_modules/with/node_modules/acorn/acorn.js:298:15)
    at unexpected (/home/local/IGSTDEV/saravanan_k/newworkspace/whiteBoard/WebContent/matisse-master/node_modules/jade/node_modules/with/node_modules/acorn/acorn.js:1284:5)
    at parseExprAtom (/home/local/IGSTDEV/saravanan_k/newworkspace/whiteBoard/WebContent/matisse-master/node_modules/jade/node_modules/with/node_modules/acorn/acorn.js:2049:7)
    at parseExprSubscripts (/home/local/IGSTDEV/saravanan_k/newworkspace/whiteBoard/WebContent/matisse-master/node_modules/jade/node_modules/with/node_modules/acorn/acorn.js:1912:28)
    at parseMaybeUnary (/home/local/IGSTDEV/saravanan_k/newworkspace/whiteBoard/WebContent/matisse-master/node_modules/jade/node_modules/with/node_modules/acorn/acorn.js:1896:16)
    at parseExprOps (/home/local/IGSTDEV/saravanan_k/newworkspace/whiteBoard/WebContent/matisse-master/node_modules/jade/node_modules/with/node_modules/acorn/acorn.js:1854:24)
    at parseMaybeConditional (/home/local/IGSTDEV/saravanan_k/newworkspace/whiteBoard/WebContent/matisse-master/node_modules/jade/node_modules/with/node_modules/acorn/acorn.js:1839:16)
    at parseMaybeAssign (/home/local/IGSTDEV/saravanan_k/newworkspace/whiteBoard/WebContent/matisse-master/node_modules/jade/node_modules/with/node_modules/acorn/acorn.js:1823:16)
    at parseExpression (/home/local/IGSTDEV/saravanan_k/newworkspace/whiteBoard/WebContent/matisse-master/node_modules/jade/node_modules/with/node_modules/acorn/acorn.js:1809:16)
    at parseStatement (/home/local/IGSTDEV/saravanan_k/newworkspace/whiteBoard/WebContent/matisse-master/node_modules/jade/node_modules/with/node_modules/acorn/acorn.js:1501:38)
    at parseBlock (/home/local/IGSTDEV/saravanan_k/newworkspace/whiteBoard/WebContent/matisse-master/node_modules/jade/node_modules/with/node_modules/acorn/acorn.js:1738:18)
    at parseStatement (/home/local/IGSTDEV/saravanan_k/newworkspace/whiteBoard/WebContent/matisse-master/node_modules/jade/node_modules/with/node_modules/acorn/acorn.js:1490:26)

path.js:360
        throw new TypeError('Arguments to path.join must be strings');
              ^
TypeError: Arguments to path.join must be strings
    at path.js:360:15
    at Array.filter (native)
    at exports.join (path.js:358:36)
    at exports.send (/home/local/IGSTDEV/saravanan_k/newworkspace/whiteBoard/WebContent/matisse-master/node_modules/express/node_modules/connect/lib/middleware/static.js:129:20)
    at pass (/home/local/IGSTDEV/saravanan_k/newworkspace/whiteBoard/WebContent/matisse-master/node_modules/gzippo/lib/staticGzip.js:106:4)
    at /home/local/IGSTDEV/saravanan_k/newworkspace/whiteBoard/WebContent/matisse-master/node_modules/gzippo/lib/staticGzip.js:160:12
    at Object.oncomplete (fs.js:107:15)

**Comment by sheerun** [comment]
Support questions are best asked on StackOverflow.
