### ISSUE TITLE
Storage location ignored

### ISSUE THREAD

**Issue by ByroRedux** [bower/bower#1728]
Can someone tell me why is bower insisting on using the ~/.cache when I clearly pointed out where the cache should be? Tried with CLI arguments, also does not work. Ubuntu 14.04 server
```
web1@vienna:~/web/packages/tpl_default$ cat .bowerrc 
{
  "directory": "ext/",
  "analytics": false,
  "storage": {
    "cache" : "~/private/.bower/cache",
    "registry" : "~/private/.bower/registry"
  }
}
web1@vienna:~/web/packages/tpl_default$ bower install
bower                           EACCES EACCES, permission denied '/var/www/clients/client1/web1/.cache'

Stack trace:
Error: EACCES, permission denied '/var/www/clients/client1/web1/.cache'
    at Object.fs.mkdirSync (fs.js:647:18)
    at sync (/usr/local/lib/node_modules/bower/node_modules/mkdirp/index.js:70:13)
    at sync (/usr/local/lib/node_modules/bower/node_modules/mkdirp/index.js:76:24)
    at Function.sync (/usr/local/lib/node_modules/bower/node_modules/mkdirp/index.js:76:24)
    at new ResolveCache (/usr/local/lib/node_modules/bower/lib/core/ResolveCache.js:24:12)
    at new PackageRepository (/usr/local/lib/node_modules/bower/lib/core/PackageRepository.js:20:26)
    at new Manager (/usr/local/lib/node_modules/bower/lib/core/Manager.js:17:24)
    at new Project (/usr/local/lib/node_modules/bower/lib/core/Project.js:25:21)
    at install (/usr/local/lib/node_modules/bower/lib/commands/install.js:17:15)
    at install.line (/usr/local/lib/node_modules/bower/lib/commands/install.js:34:12)

Console trace:
Trace
    at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:82:17)
    at Logger.<anonymous> (/usr/local/lib/node_modules/bower/bin/bower:110:22)
    at Logger.EventEmitter.emit (events.js:95:17)
    at Logger.emit (/usr/local/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/local/lib/node_modules/bower/lib/commands/index.js:40:20
    at _rejected (/usr/local/lib/node_modules/bower/node_modules/q/q.js:797:24)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:823:30
    at Promise.when (/usr/local/lib/node_modules/bower/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/node_modules/q/q.js:741:41)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:509:49

System info:
Bower version: 1.3.12
Node version: 0.10.25
OS: Linux 2.6.32-042stab093.5 x64

```

**Comment by RQuadling** [comment]
Can you try using an absolute path? I think the issue lies in the fact that bower/npm calls/runs scripts as a user different to the one that ~ relates to.

**Comment by ByroRedux** [comment]
Tried with:
```
{
  "directory": "ext/",
  "analytics": false,
  "storage": {
    "cache" : "/var/www/clients/client1/web1/private/.bower/cache",
    "registry" : "/var/www/clients/client1/web1/private/.bower/registry"
  }
}
```
The same error was printed :(

**Comment by RQuadling** [comment]
I don't know the user that npm uses (I'm a windows based user for bower), but can you try creating a directory that everyone has access to? An EACCESS issue is pretty much going to be a permissions issue somewhere along the way.

**Comment by ByroRedux** [comment]
Tried it, with /tmp/ and /var/www/bowertest (chmoded to 777), still the same. I think if there was a problem with the path, it would be reflected in the error message, instead it always prints `permission denied '/var/www/clients/client1/web1/.cache'` as if my directives are simply being ignored.
BTW this is a ISPConfig machine setup

**Comment by sheerun** [comment]
It was documented wrong. The key should be "packages", not "cache". Proper config is:

```
{
  "directory": "ext/",
  "storage": {
    "packages" : "~/private/.bower/packages",
    "registry" : "~/private/.bower/registry",
    "links" : "~/private/.bower/links"
  }
}
```

Also, analytics is now not present in bower.
