### ISSUE TITLE
Error: Cannot find module 'rx'

### ISSUE THREAD

**Issue by davidbenhaim** [bower/bower#1736]
```
bower install

module.js:340
    throw err;
          ^
Error: Cannot find module 'rx'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/ubuntu/nvm/v0.10.29/lib/node_modules/bower/node_modules/insight/node_modules/inquirer/lib/utils/utils.js:8:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

bower install returned exit code 8

at Module.require (module.js:364:17) Action failed: bower install
```

The culprit (I believe) is https://github.com/Reactive-Extensions/RxJS/issues/619

insight and inquirer do not fix their required version of rx - so when rx updated (broken) it broke bower for me.

**Comment by davidbenhaim** [comment]
they just pulled the version of rx - this may be a no issue

**Comment by sheerun** [comment]
yup

**Comment by tjwudi** [comment]
So what is the walk around here?
