### ISSUE TITLE
bower info still using git:// protocol so it fails behind company proxies

### ISSUE THREAD

**Issue by hansgru** [bower/bower#1741]
The ```bower info``` command is still using the ```git:// ``` protocol so bower fails when behind company proxies:
```
C:\xxxx>bower info jquery
bower cached        https://github.com/jquery/jquery.git#2.1.3
bower validate      2.1.3 against https://github.com/jquery/jquery.git#*
bower ECMDERR       Failed to execute "git ls-remote --tags --heads git://github.com/jquery/jquery.git", exit
code of #128

Additional error details:
fatal: Unable to look up github.com (port 9418) (This is usually a temporary error during hostname resolution
and means that the local server did not receive a response from an authoritative server. )
```
This happens with windows 7 and 8.
The trick with setting in git ``` url.https://.insteadof=git:// ``` recommended in some of the closed tickets does not work.

``` bower search``` and ``` bower install``` seems to work however (so they use correctly the https:// protocol)

**Comment by samccone** [comment]
interesting @hansgru and you followed the instructions here and are still able to reproduce?
https://github.com/bower/bower/commit/9141b3020fed08817dae418de80c3defa7c40c2d#diff-4d9db09214cdd3741142579dc6c224c5R153

**Comment by hansgru** [comment]
> interesting @hansgru and you followed the instructions here and are still able to reproduce?

Yes. As I mentioned, this happens with the ```bower info``` command.

I also have an actual version of bower:
```
c:\Downloads>bower --version
1.3.12
```

and the url git trick is set:
```
c:\Downloads>git config --list
core.symlinks=false
core.autocrlf=input
color.diff=auto
color.status=auto
color.branch=auto
color.interactive=true
pack.packsizelimit=2g
help.format=html
http.sslcainfo=/bin/curl-ca-bundle.crt
sendemail.smtpserver=/bin/msmtp.exe
diff.astextplain.textconv=astextplain
rebase.autosquash=true
http.proxy=http://xxxxx:8080
http.sslverify=false
https.proxy=http://xxxxx:8080
user.name=xxxxxx
user.email=xxxxxx
branch.autosetuprebase=always
url.https://.insteadof=git://
```

**Comment by samccone** [comment]
very interesting, thanks for the detailed research we will dig in, any help is more than welcomed.

**Comment by hansgru** [comment]
Here is a verbose output with a stacktrace:
```
c:\Downloads>bower info jquery --verbose
bower cached        https://github.com/jquery/jquery.git#2.1.3
bower validate      2.1.3 against https://github.com/jquery/jquery.git#*
bower ECMDERR       Failed to execute "git ls-remote --tags --heads git://github.com/jquery/jquery.git", exit
code of #128

Additional error details:
fatal: Unable to look up github.com (port 9418) (This is usually a temporary error during hostname resolution
and means that the local server did not receive a response from an authoritative server. )

Stack trace:
Error: Failed to execute "git ls-remote --tags --heads git://github.com/jquery/jquery.git", exit code of #128
    at createError (C:\Users\USRXXXX\AppData\Roaming\npm\node_modules\bower\lib\util\createError.js:4:15)
    at ChildProcess.<anonymous> (C:\Users\USRXXXX\AppData\Roaming\npm\node_modules\bower\lib\util\cmd.js:102:21)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
From previous event:
    at executeCmd (C:\Users\USRXXXX\AppData\Roaming\npm\node_modules\bower\lib\util\cmd.js:61:22)
    at PThrottler._processEntry (C:\Users\USRXXXX\AppData\Roaming\npm\node_modules\bower\node_modules\p-throttler\index.js:89:25)
    at Promise.apply (C:\Users\USRXXXX\AppData\Roaming\npm\node_modules\bower\node_modules\p-throttler\node_modules\q\q.js:1122:26)
    at Promise.promise.promiseDispatch (C:\Users\USRXXXX\AppData\Roaming\npm\node_modules\bower\node_modules\p-throttler\node_modules\q\q.js:752:41)
    at C:\Users\USRXXXX\AppData\Roaming\npm\node_modules\bower\node_modules\p-throttler\node_modules\q\q.js:1337:14
    at flush (C:\Users\USRXXXX\AppData\Roaming\npm\node_modules\bower\node_modules\p-throttler\node_modules\q\q.js:108:17)

Console trace:
Trace
    at StandardRenderer.error (C:\Users\USRXXXX\AppData\Roaming\npm\node_modules\bower\lib\renderers\StandardRenderer.js:82:17)
    at Logger.<anonymous> (C:\Users\USRXXXX\AppData\Roaming\npm\node_modules\bower\bin\bower:110:22)
    at Logger.emit (events.js:107:17)
    at Logger.emit (C:\Users\USRXXXX\AppData\Roaming\npm\node_modules\bower\node_modules\bower-logger\lib\Logger.js:29:39)
    at C:\Users\USRXXXX\AppData\Roaming\npm\node_modules\bower\lib\commands\index.js:40:20
    at _rejected (C:\Users\USRXXXX\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:797:24)
    at C:\Users\USRXXXX\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:823:30
    at Promise.when (C:\Users\USRXXXX\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:1035:31)
    at Promise.promise.promiseDispatch (C:\Users\USRXXXX\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:741:41)
    at C:\Users\USRXXXX\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:557:44

System info:
Bower version: 1.3.12
Node version: 0.12.0
OS: Windows_NT 6.1.7601 ia32
```

**Comment by pjmolina** [comment]
My two cents. `bower install` fails for me with the same error code in Windows 8. 
In different execution runs it fails in different packages (non-deterministic). 
Availability issue on github, or a protection measure against DOS attacks?

Repro info: bower.json file: 
```
{
    "name": "SampleBackend",
    "description": "SampleBackend description",
    "version": "0.0.1",
    "private": true,
    "dependencies": {
        "angular": "1.3.14",
        "angular-route": "1.3.14",
        "angular-loader": "1.3.14",
        "angular-mocks": "1.3.14",
        "angular-animate": "1.3.14",
        "angular-cookies": "1.3.14",
        "angular-sanitize": "1.3.14",
        "angular-bootstrap": "0.12.1",
        "textAngular": "~1.3.7",
        "angular-translate": "~2.6.1",
        "angular-translate-loader-static-files": "~2.6.1",
        "angular-translate-loader-partial": "~2.6.1"
    },
    "resolutions": {
        "angular": "1.3.14"
    }
}
```
Attached log:

```
>bower install
bower angular#1.3.14            cached git://github.com/angular/bower-angular.git#1.3.14
bower angular#1.3.14          validate 1.3.14 against git://github.com/angular/bower-angular.git#1.3.14
bower angular-animate#1.3.14    cached git://github.com/angular/bower-angular-animate.git#1.3.14
bower angular-animate#1.3.14  validate 1.3.14 against git://github.com/angular/bower-angular-animate.git#1.3.14
bower angular-loader#1.3.14     cached git://github.com/angular/bower-angular-loader.git#1.3.14
bower angular-loader#1.3.14   validate 1.3.14 against git://github.com/angular/bower-angular-loader.git#1.3.14
bower angular-route#1.3.14      cached git://github.com/angular/bower-angular-route.git#1.3.14
bower angular-route#1.3.14    validate 1.3.14 against git://github.com/angular/bower-angular-route.git#1.3.14
bower angular-mocks#1.3.14      cached git://github.com/angular/bower-angular-mocks.git#1.3.14
bower angular-mocks#1.3.14    validate 1.3.14 against git://github.com/angular/bower-angular-mocks.git#1.3.14
bower angular-bootstrap#0.12.1  cached git://github.com/angular-ui/bootstrap-bower.git#0.12.1
bower angular-bootstrap#0.12.1         validate 0.12.1 against git://github.com/angular-ui/bootstrap-bower.git#0.12.1
bower angular-cookies#1.3.14             cached git://github.com/angular/bower-angular-cookies.git#1.3.14
bower angular-cookies#1.3.14           validate 1.3.14 against git://github.com/angular/bower-angular-cookies.git#1.3.14
bower textAngular#~1.3.7                 cached git://github.com/fraywing/textAngular.git#1.3.11
bower textAngular#~1.3.7               validate 1.3.11 against git://github.com/fraywing/textAngular.git#~1.3.7
bower angular-sanitize#1.3.14            cached git://github.com/angular/bower-angular-sanitize.git#1.3.14
bower angular-sanitize#1.3.14          validate 1.3.14 against git://github.com/angular/bower-angular-sanitize.git#1.3.14
bower angular-translate#~2.6.1           cached git://github.com/PascalPrecht/bower-angular-translate.git#2.6.1
bower angular-translate#~2.6.1         validate 2.6.1 against git://github.com/PascalPrecht/bower-angular-translate.git#~2.6.1
bower angular-translate-loader-static-files#~2.6.1           cached git://github.com/PascalPrecht/bower-angular-translate-loader-s
tatic-files.git#2.6.1
bower angular-translate-loader-static-files#~2.6.1         validate 2.6.1 against git://github.com/PascalPrecht/bower-angular-tran
slate-loader-static-files.git#~2.6.1
bower angular-translate-loader-partial#~2.6.1                cached git://github.com/PascalPrecht/bower-angular-translate-loader-p
artial.git#2.6.1
bower angular-translate-loader-partial#~2.6.1              validate 2.6.1 against git://github.com/PascalPrecht/bower-angular-tran
slate-loader-partial.git#~2.6.1
bower angular#>=1 <1.3.0                                     cached git://github.com/angular/bower-angular.git#1.2.28
bower angular#>=1 <1.3.0                                   validate 1.2.28 against git://github.com/angular/bower-angular.git#>=1
<1.3.0
bower bootstrap-css-only#^3.0.x                              cached git://github.com/fyockm/bootstrap-css-only.git#3.3.4
bower bootstrap-css-only#^3.0.x                            validate 3.3.4 against git://github.com/fyockm/bootstrap-css-only.git#^
3.0.x
bower font-awesome#^4.0.x                                    cached git://github.com/FortAwesome/Font-Awesome.git#4.3.0
bower font-awesome#^4.0.x                                  validate 4.3.0 against git://github.com/FortAwesome/Font-Awesome.git#^4
.0.x
bower rangy#^1.2.0                                           cached git://github.com/timdown/rangy-release.git#1.2.3
bower rangy#^1.2.0                                         validate 1.2.3 against git://github.com/timdown/rangy-release.git#^1.2.
0
bower angular-translate-loader-static-files#~2.6.1          ECMDERR Failed to execute "git ls-remote --tags --heads git://github.c
om/PascalPrecht/bower-angular-translate-loader-static-files.git", exit code of #128

Additional error details:
fatal: unable to connect to github.com:
github.com[0: 192.30.252.128]: errno=No such file or directory

System info:
node version: 0.10.28
bower version: 1.3.12
OS: Microsoft Windows [Version 6.3.9600]
```

**Comment by ooxi** [comment]
Any updates on this issue?

**Comment by Zougi** [comment]
Hi, I just ran into this issue and solved it by creating a file ".bowerrc" at the root of my project,
with the following content:

{
  "proxy":"http://proxy:8080",
  "https-proxy":"http://proxy:8080"
}

**Comment by sheerun** [comment]
You can write write Pluggable Resolver to re-write git:// urls to https:// urls. http://bower.io/docs/pluggable-resolvers/

The second option is explained here: http://stackoverflow.com/questions/21705091/bower-behind-a-proxy

**Comment by Zougi** [comment]
or you can just read the doc as I did: http://bower.io/docs/config/

**Comment by sheerun** [comment]
@Zougi This issue is about `git://` protocol.

Not about `http://` or `https://` that `proxy` and `https-proxy` handle :)

**Comment by sheerun** [comment]
Oh, and yes, he forgot about additionally setting those configs, so you are right as well.
