### ISSUE TITLE
Postinstall command fails with ENOENT

### ISSUE THREAD

**Issue by xavdid** [bower/bower#1760]
I've got a `postinstall` script that runs a gulp task, but I'm trying to have said task not run in production. 

Trying to be clever, I get the following error: 

```
bower postinstall   if [ "$NODE_ENV" != production ]; then gulp bower; fi;
bower ENOENT        spawn ENOENT

Stack trace:
Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)

Console trace:
Error
    at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:82:37)
    at Logger.<anonymous> (/usr/local/lib/node_modules/bower/bin/bower:110:22)
    at Logger.emit (events.js:95:17)
    at Logger.emit (/usr/local/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/local/lib/node_modules/bower/lib/commands/index.js:45:20
    at _rejected (/usr/local/lib/node_modules/bower/node_modules/q/q.js:804:24)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:830:30
    at Promise.when (/usr/local/lib/node_modules/bower/node_modules/q/q.js:1064:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/node_modules/q/q.js:748:41)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:564:44
System info:
Bower version: 1.4.0
Node version: 0.10.32
OS: Darwin 14.1.0 x64
```

Changing the post install script to `gulp bower` runs without incident, but `"if [ \"$NODE_ENV\" != production ]; then gulp bower; fi;"` causes the shown error. 

Thanks much!

**Comment by Xavdidtheshadow** [comment]
So it seems like bower doesn't have access to the environment when it's being run? I put a sanity check in and got

```
bower postinstall   env is undefined
```

which is troubling

**Comment by sheerun** [comment]
I think postinstall script doesn't run as bash script, but is passed directly to spawn command.

Maybe we should change this behavior.

**Comment by Xavdidtheshadow** [comment]
Even if the behavior doesn't change, it'd be nice to have it have more clear documentation as for what is/isn't allowed.

**Comment by samccone** [comment]
@Xavdidtheshadow would love a PR to improve places where you think we are not clear

**Comment by danielstjules** [comment]
Is there any interest in allowing the hooks to be a bash script?

**Comment by sheerun** [comment]
I think we could ship it if someone sent a PR with tests.
