### ISSUE TITLE
EACCES (bower-github.yml) error on 1.4.1

### ISSUE THREAD

**Issue by aliemre** [bower/bower#1773]
After updating Bower to 1.4.1, I am getting the error below:
I am using MacOS X Mavericks.
````
Error: EACCES, permission denied '/Users/aliemre/.config/configstore/bower-github.yml'
You don't have access to this file.

    at Object.fs.openSync (evalmachine.<anonymous>:438:18)
    at Object.fs.readFileSync (evalmachine.<anonymous>:289:15)
    at Object.create.all.get (/usr/local/lib/node_modules/bower/node_modules/configstore/index.js:34:29)
    at Object.Configstore (/usr/local/lib/node_modules/bower/node_modules/configstore/index.js:27:44)
    at readCachedConfig (/usr/local/lib/node_modules/bower/lib/config.js:22:23)
    at defaultConfig (/usr/local/lib/node_modules/bower/lib/config.js:11:24)
    at Object.<anonymous> (/usr/local/lib/node_modules/bower/lib/index.js:40:32)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

Also, --allow-root option does not work...

**Comment by aliemre** [comment]
I solved the problem by changing owner of the file.
