### ISSUE TITLE
bower init fail ENOENT, open 'core/client/bower.json'

### ISSUE THREAD

**Issue by alivelee** [bower/bower#1779]
bower ENOENT        ENOENT, open 'core/client/bower.json'

Stack trace:
Error: ENOENT, open 'core/client/bower.json'
    at Error (native)

Console trace:
Error
    at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:82:37)
    at Logger.<anonymous> (/usr/local/lib/node_modules/bower/bin/bower:110:22)
    at Logger.emit (events.js:107:17)
    at Logger.emit (/usr/local/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/local/lib/node_modules/bower/lib/commands/index.js:45:20
    at _rejected (/usr/local/lib/node_modules/bower/node_modules/q/q.js:804:24)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:830:30
    at Promise.when (/usr/local/lib/node_modules/bower/node_modules/q/q.js:1064:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/node_modules/q/q.js:748:41)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:564:44
System info:
Bower version: 1.4.1
Node version: 0.12.2
OS: Darwin 14.3.0 x64

**Comment by alivelee** [comment]
Sorry,Make a Fool

**Comment by alivelee** [comment]
ignore the bower.json's location has change

**Comment by donnanicolas** [comment]
Sorry to ask, but i have the same problem, what's the solution
