### ISSUE TITLE
Error: EISDIR

### ISSUE THREAD

**Issue by btmdave** [bower/bower#1793]
On occasion (seemly random), I receive an error:
```
Stack trace:
Error: EISDIR, open '.bower-tmp/chosen_v1.4.1-5294-TI8xIb/docsupport/'
```
When doing `bower --allow-root update`.  I've deleted the `.bower-tmp` directory and also ran `bower --allow-root cache clean`.

After the cache clean, I received 4 warnings:

```
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at CleartextStream.EventEmitter.addListener (events.js:160:15)
    at CleartextStream.Readable.on (_stream_readable.js:689:33)
    at CleartextStream.EventEmitter.once (events.js:185:8)
    at Request.onResponse (/usr/local/lib/node_modules/bower/node_modules/request/request.js:625:25)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1688:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
    at CleartextStream.socketOnData [as ondata] (http.js:1583:20)
    at CleartextStream.read [as _read] (tls.js:511:12)
```

Which then ended again with 

```
Stack trace:
Error: EISDIR, open '.bower-tmp/chosen_v1.4.1-5386-MnJHCT/docsupport/'
```

```
System info:
Bower version: 1.2.8
Node version: 0.10.23
OS: Linux 3.5.0-44-generic x64
```

Any ideas what causes this/how to resolve?

**Comment by xanf** [comment]
hi @btmdave.
Is it happens every time? It looks like you've hit the same issue as described in https://github.com/joyent/node/issues/5346 but it's hard to debug it. If it reproduces every time, that will help a lot :)

**Comment by btmdave** [comment]
@xanf Yeah, it was, but I had since cleared it out and started fresh and no issues since.  If it comes back, I'll follow up here.

**Comment by jasnell** [comment]
I've closed the issue over in joyent/node due to complete lack of any activity or indication that it's still an issue. If your testing ends up showing that https://github.com/joyent/node/issues/5346 is still an issue and a factor in this, let me know and I'll re-open the issue.
