### ISSUE TITLE
Error: UNKNOWN write

### ISSUE THREAD

**Issue by john2x** [bower/bower#1815]
I get an error when I run the following on Ubuntu 14.04 using Vagrant.

```
$ node -v
v0.10.25
$ bower -v
1.4.1
$ bower install jquery underscore angular \
    angular-bootstrap angular-route checklist-model \
    angular-xeditable angular-material angular-cookies \
    angular-resource angular-django-rest-resource
...
...
...
bower install       angular-bootstrap#0.13.0
bower install       angular#1.4.0
bower install       angular-route#1.4.0
bower install       jquery#2.1.4
bower install       underscore#1.8.3
bower install       checklist-model#0.2.4
bower install       angular-xeditable#0.1.9
bower install       angular-cookies#1.4.0
bower install       angular-material#0.9.8
bower install       angular-resource#1.4.0
bower install       angular-django-rest-resource#1.0.3
bower install       angular-aria#1.4.0
bower install       angular-animate#1.4.0
bower UNKNOWN       UNKNOWN, write

Stack trace:
Error: UNKNOWN, write

Console trace:
Error
    at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:82:37)
    at Logger.<anonymous> (/usr/local/lib/node_modules/bower/bin/bower:110:22)
    at Logger.EventEmitter.emit (events.js:95:17)
    at Logger.emit (/usr/local/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/local/lib/node_modules/bower/lib/commands/index.js:45:20
    at _rejected (/usr/local/lib/node_modules/bower/node_modules/q/q.js:844:24)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:870:30
    at Promise.when (/usr/local/lib/node_modules/bower/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/node_modules/q/q.js:788:41)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:604:44
System info:
Bower version: 1.4.1
Node version: 0.10.25
OS: Linux 3.13.0-53-generic x64
```

Here's the generated `bower_components` directory

```
bower_components/
|-- angular
|   `-- .bower.json
|-- angular-animate
|   `-- .bower.json
|-- angular-aria
|   `-- .bower.json
|-- angular-bootstrap
|   `-- .bower.json
|-- angular-cookies
|   `-- .bower.json
|-- angular-django-rest-resource
|   `-- .bower.json
|-- angular-material
|   `-- .bower.json
|-- angular-resource
|   `-- .bower.json
|-- angular-route
|   `-- .bower.json
|-- angular-xeditable
|   `-- .bower.json
|-- checklist-model
|   `-- .bower.json
|-- jquery
|   `-- .bower.json
`-- underscore
    `-- .bower.json

13 directories, 13 files
```

**Comment by john2x** [comment]
It seems the problem might be something to do with Vagrant's synced folders, as I'm trying to install inside a synced folder. Installing outside the synced folder works fine.
