### ISSUE TITLE
EPERM, unlink... [Windows CMD Error]

### ISSUE THREAD

**Issue by DerekFoulk** [bower/bower#1835]
I am seeing this issue working in a test directory (it also happens in my project's repo)...

```
C:\Users\Derek\NPM_Test>bower install bootstrap
bower cached        git://github.com/twbs/bootstrap.git#3.0.0
bower validate      3.0.0 against git://github.com/twbs/bootstrap.git#*
bower new           version for git://github.com/twbs/bootstrap.git#*
bower resolve       git://github.com/twbs/bootstrap.git#*
bower download      https://github.com/twbs/bootstrap/archive/v3.3.5.tar.gz
bower retry         Download of https://github.com/twbs/bootstrap/archive/v3.3.5
.tar.gz failed, trying with git..
bower EPERM         EPERM, unlink 'C:\Users\Derek\AppData\Local\Temp\Derek-Delta
-Derek\bower\bootstrap-5924-36Qaha\archive.tar.gz'

Stack trace:
Error: EPERM, unlink 'C:\Users\Derek\AppData\Local\Temp\Derek-Delta-Derek\bower\
bootstrap-5924-36Qaha\archive.tar.gz'
    at Error (native)

Console trace:
Error
    at StandardRenderer.error (C:\Users\Derek\AppData\Roaming\npm\node_modules\b
ower\lib\renderers\StandardRenderer.js:82:37)
    at Logger.<anonymous> (C:\Users\Derek\AppData\Roaming\npm\node_modules\bower
\bin\bower:110:22)
    at Logger.emit (events.js:107:17)
    at Logger.emit (C:\Users\Derek\AppData\Roaming\npm\node_modules\bower\node_m
odules\bower-logger\lib\Logger.js:29:39)
    at C:\Users\Derek\AppData\Roaming\npm\node_modules\bower\lib\commands\index.
js:45:20
    at _rejected (C:\Users\Derek\AppData\Roaming\npm\node_modules\bower\node_mod
ules\q\q.js:844:24)
    at C:\Users\Derek\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js
:870:30
    at Promise.when (C:\Users\Derek\AppData\Roaming\npm\node_modules\bower\node_
modules\q\q.js:1122:31)
    at Promise.promise.promiseDispatch (C:\Users\Derek\AppData\Roaming\npm\node_
modules\bower\node_modules\q\q.js:788:41)
    at C:\Users\Derek\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js
:604:44
System info:
Bower version: 1.4.1
Node version: 0.12.5
OS: Windows_NT 6.1.7601 x64

C:\Users\Derek\NPM_Test>bower cache clean
bower deleted       Cached package hammerjs: C:\Users\Derek\AppData\Local\bower\
cache\packages\098ab2d554284f2f3f0b876f499afd3d\2.0.4
bower deleted       Cached package jquery-validation-unobtrusive: C:\Users\Derek
\AppData\Local\bower\cache\packages\88c510af4bbaa8a5dc68f01596f7ec90\3.2.2
bower deleted       Cached package bootstrap-touch-carousel: C:\Users\Derek\AppD
ata\Local\bower\cache\packages\3b1db860df1398c73a4ad1bde6ac26df\0.8.0
bower deleted       Cached package bootstrap: C:\Users\Derek\AppData\Local\bower
\cache\packages\76825ba06db421bbfbda0853e440b3f5\3.0.0
bower deleted       Cached package jquery: C:\Users\Derek\AppData\Local\bower\ca
che\packages\fe2fe255e91d251051d543998aa8327a\1.10.2
bower deleted       Cached package jquery-validation: C:\Users\Derek\AppData\Loc
al\bower\cache\packages\79e0df817430277c59fd1e41d1a36c2d\1.11.1

C:\Users\Derek\NPM_Test>bower install bootstrap --save
bower not-cached    git://github.com/twbs/bootstrap.git#*
bower resolve       git://github.com/twbs/bootstrap.git#*
bower download      https://github.com/twbs/bootstrap/archive/v3.3.5.tar.gz
bower retry         Download of https://github.com/twbs/bootstrap/archive/v3.3.5
.tar.gz failed, trying with git..
bower EPERM         EPERM, unlink 'C:\Users\Derek\AppData\Local\Temp\Derek-Delta
-Derek\bower\bootstrap-8236-TSKSeT\archive.tar.gz'

Stack trace:
Error: EPERM, unlink 'C:\Users\Derek\AppData\Local\Temp\Derek-Delta-Derek\bower\
bootstrap-8236-TSKSeT\archive.tar.gz'
    at Error (native)

Console trace:
Error
    at StandardRenderer.error (C:\Users\Derek\AppData\Roaming\npm\node_modules\b
ower\lib\renderers\StandardRenderer.js:82:37)
    at Logger.<anonymous> (C:\Users\Derek\AppData\Roaming\npm\node_modules\bower
\bin\bower:110:22)
    at Logger.emit (events.js:107:17)
    at Logger.emit (C:\Users\Derek\AppData\Roaming\npm\node_modules\bower\node_m
odules\bower-logger\lib\Logger.js:29:39)
    at C:\Users\Derek\AppData\Roaming\npm\node_modules\bower\lib\commands\index.
js:45:20
    at _rejected (C:\Users\Derek\AppData\Roaming\npm\node_modules\bower\node_mod
ules\q\q.js:844:24)
    at C:\Users\Derek\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js
:870:30
    at Promise.when (C:\Users\Derek\AppData\Roaming\npm\node_modules\bower\node_
modules\q\q.js:1122:31)
    at Promise.promise.promiseDispatch (C:\Users\Derek\AppData\Roaming\npm\node_
modules\bower\node_modules\q\q.js:788:41)
    at C:\Users\Derek\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js
:604:44
System info:
Bower version: 1.4.1
Node version: 0.12.5
OS: Windows_NT 6.1.7601 x64
```

**Comment by DerekFoulk** [comment]
I tried uninstalling and reinstalling bower, with no luck... I still can't install packages with bower :(

```
C:\Users\Derek\npmBowerTest>npm uninstall -g bower
unbuild bower@1.4.1

C:\Users\Derek\npmBowerTest>bower -v
'bower' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Derek\npmBowerTest>npm install -g bower
C:\Users\Derek\AppData\Roaming\npm\bower -> C:\Users\Derek\AppData\Roaming\npm\n
ode_modules\bower\bin\bower
bower@1.4.1 C:\Users\Derek\AppData\Roaming\npm\node_modules\bower
├── is-root@1.0.0
├── junk@1.0.1
├── stringify-object@1.0.1
├── user-home@1.1.1
├── chmodr@0.1.0
├── abbrev@1.0.7
├── archy@1.0.0
├── rimraf@2.4.0
├── graceful-fs@3.0.8
├── lru-cache@2.6.4
├── bower-logger@0.2.2
├── bower-endpoint-parser@0.2.2
├── lockfile@1.0.1
├── opn@1.0.2
├── retry@0.6.1
├── nopt@3.0.3
├── tmp@0.0.24
├── q@1.4.1
├── semver@2.3.2
├── fstream@1.0.7 (inherits@2.0.1)
├── request-progress@0.3.1 (throttleit@0.0.2)
├── chalk@1.0.0 (escape-string-regexp@1.0.3, ansi-styles@2.0.1, supports-color@1
.3.1, strip-ansi@2.0.1, has-ansi@1.0.3)
├── shell-quote@1.4.3 (array-reduce@0.0.0, array-map@0.0.0, array-filter@0.0.1,
jsonify@0.0.0)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── p-throttler@0.1.1 (q@0.9.7)
├── bower-json@0.4.0 (intersect@0.0.3, deep-extend@0.2.11, graceful-fs@2.0.3)
├── promptly@0.2.0 (read@1.0.6)
├── which@1.1.1 (is-absolute@0.1.7)
├── glob@4.5.3 (inherits@2.0.1, inflight@1.0.4, once@1.3.2, minimatch@2.0.8)
├── fstream-ignore@1.0.2 (inherits@2.0.1, minimatch@2.0.8)
├── insight@0.5.3 (object-assign@2.1.1, async@0.9.2, lodash.debounce@3.1.0, os-n
ame@1.0.3, tough-cookie@0.12.1)
├── tar-fs@1.6.0 (pump@1.0.0, tar-stream@1.2.1)
├── decompress-zip@0.1.0 (mkpath@0.1.0, touch@0.0.3, readable-stream@1.1.13, bin
ary@0.3.0)
├── github@0.2.4 (mime@1.3.4)
├── update-notifier@0.3.2 (is-npm@1.0.0, string-length@1.0.0, semver-diff@2.0.0,
 latest-version@1.0.1)
├── cardinal@0.4.4 (ansicolors@0.2.1, redeyed@0.4.4)
├── bower-registry-client@0.3.0 (graceful-fs@2.0.3, request-replay@0.2.0, rimraf
@2.2.8, lru-cache@2.3.1, mkdirp@0.3.5, async@0.2.10, request@2.51.0)
├── request@2.53.0 (caseless@0.9.0, aws-sign2@0.5.0, stringstream@0.0.4, forever
-agent@0.5.2, oauth-sign@0.6.0, tunnel-agent@0.4.0, isstream@0.1.2, json-stringi
fy-safe@5.0.1, qs@2.3.3, node-uuid@1.4.3, form-data@0.2.0, combined-stream@0.0.7
, bl@0.9.4, mime-types@2.0.14, http-signature@0.10.1, tough-cookie@2.0.0, hawk@2
.3.1)
├── mout@0.11.0
├── bower-config@0.6.1 (osenv@0.0.3, graceful-fs@2.0.3, optimist@0.6.1, mout@0.9
.1)
├── configstore@0.3.2 (object-assign@2.1.1, xdg-basedir@1.0.1, uuid@2.0.1, osenv
@0.1.2, js-yaml@3.3.1)
├── inquirer@0.8.0 (ansi-regex@1.1.1, figures@1.3.5, mute-stream@0.0.4, through@
2.3.7, readline2@0.1.1, chalk@0.5.1, lodash@2.4.2, cli-color@0.3.3, rx@2.5.3)
└── handlebars@2.0.0 (optimist@0.3.7, uglify-js@2.3.6)

C:\Users\Derek\npmBowerTest>dir
 Volume in drive C has no label.
 Volume Serial Number is A2A0-E677

 Directory of C:\Users\Derek\npmBowerTest

06/27/2015  04:17 PM    <DIR>          .
06/27/2015  04:17 PM    <DIR>          ..
06/27/2015  04:17 PM               277 package.json
               1 File(s)            277 bytes
               2 Dir(s)  63,762,010,112 bytes free

C:\Users\Derek\npmBowerTest>bower install jquery
bower cached        git://github.com/jquery/jquery.git#1.10.2
bower validate      1.10.2 against git://github.com/jquery/jquery.git#*
bower new           version for git://github.com/jquery/jquery.git#*
bower resolve       git://github.com/jquery/jquery.git#*
bower download      https://github.com/jquery/jquery/archive/2.1.4.tar.gz
bower retry         Download of https://github.com/jquery/jquery/archive/2.1.4.t
ar.gz failed, trying with git..
bower EPERM         EPERM, unlink 'C:\Users\Derek\AppData\Local\Temp\Derek-Delta
-Derek\bower\jquery-2984-8klsQZ\archive.tar.gz'

Stack trace:
Error: EPERM, unlink 'C:\Users\Derek\AppData\Local\Temp\Derek-Delta-Derek\bower\
jquery-2984-8klsQZ\archive.tar.gz'
    at Error (native)

Console trace:
Error
    at StandardRenderer.error (C:\Users\Derek\AppData\Roaming\npm\node_modules\b
ower\lib\renderers\StandardRenderer.js:82:37)
    at Logger.<anonymous> (C:\Users\Derek\AppData\Roaming\npm\node_modules\bower
\bin\bower:110:22)
    at Logger.emit (events.js:107:17)
    at Logger.emit (C:\Users\Derek\AppData\Roaming\npm\node_modules\bower\node_m
odules\bower-logger\lib\Logger.js:29:39)
    at C:\Users\Derek\AppData\Roaming\npm\node_modules\bower\lib\commands\index.
js:45:20
    at _rejected (C:\Users\Derek\AppData\Roaming\npm\node_modules\bower\node_mod
ules\q\q.js:844:24)
    at C:\Users\Derek\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js
:870:30
    at Promise.when (C:\Users\Derek\AppData\Roaming\npm\node_modules\bower\node_
modules\q\q.js:1122:31)
    at Promise.promise.promiseDispatch (C:\Users\Derek\AppData\Roaming\npm\node_
modules\bower\node_modules\q\q.js:788:41)
    at C:\Users\Derek\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js
:604:44
System info:
Bower version: 1.4.1
Node version: 0.12.5
OS: Windows_NT 6.1.7601 x64

C:\Users\Derek\npmBowerTest>
```

**Comment by sheerun** [comment]
Hey. I don't know how to reproduce this. Please clone bower and try to write a failing test. We run all tests on AppVeyor, so we'll know how to reproduce this and fix it. Thanks!
