### ISSUE TITLE
Underlying filesystem (NFS) errors cause bower to fail silently

### ISSUE THREAD

**Issue by dazwin** [bower/bower#1847]
When running bower install on a vagrant environment where the source directory was NFS mounted to the host, I consistently got an indeterminate set of packages left in an 'unpacked' state (e.g. I would see bower_components/angular/bower-angular-x.y.z). The exit code from bower install was zero.

Diagnosing the issue, I manually installed several bower components via the command line and came across the following error:
```
bower angular-mocks#*                     EBUSY EBUSY, unlink '/vagrant/myproject/.bower-tmp/angular-mocks-12849-Zdgw44/.nfs0000000003f3469600000015'

Stack trace:
Error: EBUSY, unlink '/vagrant/myproject/.bower-tmp/angular-mocks-12849-Zdgw44/.nfs0000000003f3469600000015'

Console trace:
Error
    at StandardRenderer.error (/usr/lib/node_modules/bower/lib/renderers/StandardRenderer.js:82:37)
    at Logger.<anonymous> (/usr/lib/node_modules/bower/bin/bower:110:22)
    at Logger.emit (events.js:95:17)
    at Logger.emit (/usr/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/lib/node_modules/bower/lib/commands/index.js:45:20
    at _rejected (/usr/lib/node_modules/bower/node_modules/q/q.js:844:24)
    at /usr/lib/node_modules/bower/node_modules/q/q.js:870:30
    at Promise.when (/usr/lib/node_modules/bower/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/bower/node_modules/q/q.js:788:41)
    at /usr/lib/node_modules/bower/node_modules/q/q.js:604:44
System info:
Bower version: 1.4.1
Node version: 0.10.39
OS: Linux 3.13.0-55-generic x64
```

After making sure that .bower-tmp, .bower-cache, and .bower-registry were no longer on an NFS-mounted directory, a regular bower install worked correctly.

So, it seems that "bower install" is not reporting underlying errors correctly, whereas "bower install [component...]" is.

**Comment by sheerun** [comment]
Thanks for reporting this. I don't have time to fix this, but PR by anyone is welcome.

**Comment by kerbs17** [comment]
I experienced the same issue.  Our source directories have been mounted on NFS for a long time without issue.  A recent change on our servers set the TMP_DIR to a nfs mounted directory and this is when we started seeing issue.  Setting TMP_DIR back to the system's local storage fixed the issue.

**Comment by sheerun** [comment]
Does Bower 1.5.x work for you? Could you post stack trace with `--verbose` flag on?

**Comment by kerbs17** [comment]
If I do `bower cache clean`, the first `bower install` results in the following error message:
```
bower angular-bootstrap#~0.13                         EBUSY EBUSY, unlink '/data_storage/linear/tmp/linear_frontend/bower/angular-bootstrap-22417-QrkxeU/.nfs000000001743a1e50000079f'

Stack trace:
Error: EBUSY, unlink '/data_storage/linear/tmp/linear_frontend/bower/angular-bootstrap-22417-QrkxeU/.nfs000000001743a1e50000079f'
From previous event:
    at PackageRepository._resolve (/usr/lib/node_modules/bower/lib/core/PackageRepository.js:185:6)
    at /usr/lib/node_modules/bower/lib/core/PackageRepository.js:77:29
From previous event:
    at /usr/lib/node_modules/bower/lib/core/PackageRepository.js:63:10
From previous event:
    at PackageRepository.fetch (/usr/lib/node_modules/bower/lib/core/PackageRepository.js:45:6)
    at Manager._fetch (/usr/lib/node_modules/bower/lib/core/Manager.js:299:51)
    at Array.forEach (native)
    at Manager.resolve (/usr/lib/node_modules/bower/lib/core/Manager.js:102:23)
    at Project._bootstrap (/usr/lib/node_modules/bower/lib/core/Project.js:542:6)
    at /usr/lib/node_modules/bower/lib/core/Project.js:79:21

Console trace:
Trace
    at StandardRenderer.error (/usr/lib/node_modules/bower/lib/renderers/StandardRenderer.js:82:17)
    at Logger.<anonymous> (/usr/lib/node_modules/bower/bin/bower:110:22)
    at Logger.emit (events.js:95:17)
    at Logger.emit (/usr/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/lib/node_modules/bower/lib/commands/index.js:40:20
    at _rejected (/usr/lib/node_modules/bower/node_modules/q/q.js:797:24)
    at /usr/lib/node_modules/bower/node_modules/q/q.js:823:30
    at Promise.when (/usr/lib/node_modules/bower/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/bower/node_modules/q/q.js:741:41)
    at /usr/lib/node_modules/bower/node_modules/q/q.js:557:44

System info:
Bower version: 1.3.12
Node version: 0.10.33
OS: Linux 2.6.32-504.3.3.el6.x86_64 x64
```

Then subsequent `bower install` runs yield no errors, but some of my dependencies are now inside the normal directory but a level deeper under a version number.

Ex: app/bower_components/angular-bootstrap/bootstrap-bower-0.13.4/ui-bootstrap.min.js
instead of just app/bower_components/angular-bootstrap/ui-bootstrap.min.js

I'll have to see if I can get the latest bower installed on this machine, do you suspect that this was fixed since 1.3.12?

**Comment by sheerun** [comment]
1.6.3 has `graceful-fs` on all system calls so I suspect it should work for you both.

Please let me know if you still experience this error on newest ower

**Comment by sheerun** [comment]
Given no feedback I guess it's fixed now. Anyway we'll update graceful-fs further to 4.x in next release
