### ISSUE TITLE
bower install - ENOENT No bower.json present

### ISSUE THREAD

**Issue by donnanicolas** [bower/bower#1849]
I'm having trouble with bower. I'm in the root of my project, where there is a bower.json file, but when I run `bower install` I get:
```
bower                           ENOENT No bower.json present
```

Here is the entire stack trace
```
bower                           ENOENT No bower.json present

Stack trace:
Error: No bower.json present
    at createError (/usr/local/lib/node_modules/bower/lib/util/createError.js:4:15)
    at /usr/local/lib/node_modules/bower/lib/core/Project.js:53:19
From previous event:
    at Project.install (/usr/local/lib/node_modules/bower/lib/core/Project.js:87:6)
    at install (/usr/local/lib/node_modules/bower/lib/commands/install.js:26:20)
    at /usr/local/lib/node_modules/bower/lib/commands/index.js:32:28

Console trace:
Error
    at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:82:37)
    at Logger.<anonymous> (/usr/local/lib/node_modules/bower/bin/bower:110:22)
    at Logger.emit (events.js:107:17)
    at Logger.emit (/usr/local/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/local/lib/node_modules/bower/lib/commands/index.js:45:20
    at _rejected (/usr/local/lib/node_modules/bower/node_modules/q/q.js:844:24)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:870:30
    at Promise.when (/usr/local/lib/node_modules/bower/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/node_modules/q/q.js:788:41)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:604:44
System info:
Bower version: 1.4.1
Node version: 0.12.0
OS: Darwin 14.4.0 x64
```

I've tried in another projects, also with bower.json with the same result.
If I run `bower install bower.json`it generates a core folder, with this contents:
```
core
└── client
    └── public
        └── bower_components
            ├── bower.json
            │   ├── LICENSE
            │   ├── README.md
            │   ├── app-states.html
            │   ├── app-states.js
            │   ├── bower.json
            │   ├── core.js
            │   └── src
            │       ├── app-state.html
            │       ├── app-states-component.html
            │       ├── app-states.html
            │       ├── core.js
            │       ├── place-holder.html
            │       ├── states-template.html
            │       └── view-registry.html
            ├── core-component-page
            │   ├── README.md
            │   ├── bowager-logo.png
            │   ├── bower.json
            │   ├── core-component-page.html
            │   ├── demo.html
            │   └── index.html
            ├── polymer
            │   ├── README.md
            │   ├── bower.json
            │   ├── docs
            │   │   └── index.html
            │   ├── explainer
            │   │   ├── data-bind.png
            │   │   ├── data-bind.vsdx
            │   │   └── samples.html
            │   ├── layout.html
            │   ├── polymer.html
            │   ├── polymer.js
            │   ├── polymer.min.js
            │   ├── src
            │   │   ├── lib
            │   │   │   ├── annotations
            │   │   │   │   ├── annotations.html
            │   │   │   │   └── demo
            │   │   │   │       └── app-chrome.html
            │   │   │   ├── array-observe.html
            │   │   │   ├── array-splice.html
            │   │   │   ├── async.html
            │   │   │   ├── base.html
            │   │   │   ├── bind
            │   │   │   │   ├── accessors.html
            │   │   │   │   ├── demo
            │   │   │   │   │   ├── app-chrome.html
            │   │   │   │   │   ├── app.html
            │   │   │   │   │   └── src
            │   │   │   │   │       ├── annotations-bind-demo.html
            │   │   │   │   │       └── bind-demo.html
            │   │   │   │   └── effects.html
            │   │   │   ├── case-map.html
            │   │   │   ├── collection.html
            │   │   │   ├── css-parse.html
            │   │   │   ├── debounce.html
            │   │   │   ├── dom-api.html
            │   │   │   ├── dom-module.html
            │   │   │   ├── event-api.html
            │   │   │   ├── expr
            │   │   │   │   ├── focus.html
            │   │   │   │   ├── gestures.html
            │   │   │   │   ├── log.html
            │   │   │   │   ├── sinspect.html
            │   │   │   │   ├── style-auditor.html
            │   │   │   │   └── style-protector.html
            │   │   │   ├── gestures.html
            │   │   │   ├── lang.html
            │   │   │   ├── module.html
            │   │   │   ├── polymer-bootstrap.html
            │   │   │   ├── resolve-url.html
            │   │   │   ├── settings.html
            │   │   │   ├── style-defaults.html
            │   │   │   ├── style-transformer.html
            │   │   │   ├── style-util.html
            │   │   │   ├── template
            │   │   │   │   ├── templatizer.html
            │   │   │   │   ├── x-array-selector.html
            │   │   │   │   ├── x-autobind.html
            │   │   │   │   ├── x-if.html
            │   │   │   │   ├── x-repeat.html
            │   │   │   │   └── x-template.html
            │   │   │   └── x-style.html
            │   │   ├── micro
            │   │   │   ├── attributes.html
            │   │   │   ├── behaviors.html
            │   │   │   ├── constructor.html
            │   │   │   ├── debouncer.html
            │   │   │   ├── extends.html
            │   │   │   ├── mixins.html
            │   │   │   ├── properties.html
            │   │   │   └── tag.html
            │   │   ├── mini
            │   │   │   ├── ready.html
            │   │   │   ├── shadow.html
            │   │   │   ├── shady.html
            │   │   │   └── template.html
            │   │   ├── polymer-lib.html
            │   │   └── standard
            │   │       ├── annotations.html
            │   │       ├── configure.html
            │   │       ├── effects.html
            │   │       ├── events.html
            │   │       ├── notify-path.html
            │   │       ├── resolveUrl.html
            │   │       ├── styling.html
            │   │       ├── utils.html
            │   │       └── x-styling.html
            │   └── test
            │       ├── assets
            │       │   ├── Beaker2.jpg
            │       │   └── test-style-path.html
            │       ├── compat
            │       │   ├── polymer-smoke-elements.html
            │       │   └── polymer-smoke-polyfill.html
            │       ├── runner.html
            │       ├── smoke
            │       │   ├── bind-smoke.html
            │       │   ├── custom-notify-smoke.html
            │       │   ├── elements-smoke.html
            │       │   ├── polymer-micro-smoke.html
            │       │   ├── polymer-mini-smoke.html
            │       │   ├── polymer-smoke.html
            │       │   ├── style-path-smoke.html
            │       │   ├── x-if.html
            │       │   └── x-repeat.html
            │       └── unit
            │           ├── async.html
            │           ├── attributes-elements.html
            │           ├── attributes.html
            │           ├── base.html
            │           ├── behaviors-elements.html
            │           ├── behaviors.html
            │           ├── bind-elements.html
            │           ├── bind.html
            │           ├── configure-elements.html
            │           ├── configure.html
            │           ├── css-parse.html
            │           ├── dynamic-import.html
            │           ├── dynamic-imports
            │           │   ├── dynamic-element.html
            │           │   ├── inner-element.html
            │           │   └── outer-element.html
            │           ├── gestures-elements.html
            │           ├── gestures.html
            │           ├── micro-elements.html
            │           ├── micro.html
            │           ├── notify-path-elements.html
            │           ├── notify-path.html
            │           ├── polymer-dom-elements.html
            │           ├── polymer-dom-shadow.html
            │           ├── polymer-dom.html
            │           ├── polymer-dom.js
            │           ├── ready-elements.html
            │           ├── ready-shadow.html
            │           ├── ready.html
            │           ├── ready.js
            │           ├── resolveurl.html
            │           ├── shady.html
            │           ├── styling-remote-elements.html
            │           ├── styling-remote-module-sheet.html
            │           ├── styling-remote-sheet.css
            │           ├── styling-remote.html
            │           ├── styling-scoped-elements.html
            │           ├── styling-scoped.html
            │           ├── sub
            │           │   └── resolveurl-elements.html
            │           ├── template
            │           │   └── x-template.html
            │           ├── template-elements.html
            │           ├── template.html
            │           ├── utils-content.html
            │           ├── utils-elements.html
            │           ├── utils.html
            │           ├── x-repeat-elements.html
            │           ├── x-repeat.html
            │           └── x-style.html
            └── webcomponentsjs
                ├── CustomElements.js
                ├── CustomElements.min.js
                ├── HTMLImports.js
                ├── HTMLImports.min.js
                ├── README.md
                ├── ShadowDOM.js
                ├── ShadowDOM.min.js
                ├── bower.json
                ├── build.log
                ├── package.json
                ├── webcomponents-lite.js
                ├── webcomponents-lite.min.js
                ├── webcomponents.js
                └── webcomponents.min.js

30 directories, 167 files
```

I don't know what to do
Thanks!

**Comment by lcardosozago** [comment]
I have the same problem.

**Comment by donnanicolas** [comment]
I downgraded to 1.3.12 and con work normally

**Comment by sheerun** [comment]
You're not supposed to call `bower install bower.json`, `bower install` is enough :)

You get this contents because there's package in registry named `bower.json` that points to git://github.com/Kalitte/app-states.git

**Comment by donnanicolas** [comment]
I call `bower install` and it doesn't work

**Comment by sheerun** [comment]
Could you provide steps to reproduce? From blank directory.

**Comment by ruvenss** [comment]
same problem here and I just call bower install

**Comment by kurtschlatzer** [comment]
Same issue

**Comment by ruvenss** [comment]
My solution, was to start a new ionic project from scratch then install bower and then copy my old www directory, then it did work :+1:

**Comment by changsijay** [comment]
same issue

**Comment by dcisco** [comment]
I am struggling with the bower.json file not found also.  I tried installing boer in a blank directory and that worked. I then moved my project into that directory and ran bower install and got the missing bower.json file. Chagsijay,, where do I find the .bowerrc file?

**Comment by cingoz** [comment]
try this :  bower init

**Comment by kushdilip** [comment]
`bower install bower.json` works.

**Comment by donnanicolas** [comment]
Sorry, but I keep having this issue. If I make a clean directory, run `bower init` it throws:

```
bower ENOENT        ENOENT: no such file or directory, open 'core/client/bower.json'
```
 after settings all the options.

I'm kind of stuck here, I've tried with bower 1.4.1 and 1.5.3.

Everything running smooth with 1.3.12

**Comment by Tarhan** [comment]
Main problem in such cases because of **.bowerrc** files in upper folders. When you execute **bower install** command before doing anything else it searchs **ALL** **.bowerrc** files starting from current folder up to system's root "/". After it found all config files it **concatenate** them into single config file.   
Usually it is desirable behavior. For example you might want to use globally configured registry location. In that case you just put **.bowerrc** in your parent "**My Projects**" folder.  
But one setting you must not ever save in any **.bowerrc**. It is "cwd" setting. At its description says here: https://github.com/bower/spec/blob/master/config.md#cwd ,you must not to set it in config file but only input it as part of scripts which executes bower. Sadly that description does not tell you side effects if you set "**cwd**" variable.  
Let's finish with example of project of author of issue (as I think). **bower.json** file along with **package.json** (with dev dependencies) located within **[project_path]/app** subfolder of project root. That **[project_path]/app** folder have **.bowerrc** with contents like this:
```
{
  "directory": "my_bower_components"
}
```
Its contents correct. But please notice that folder name for bower packages is not standard "**bower_components**".
Next, project have **.bowerrc** sitting inside project root folder (where you have main **app** folder and some meta information like readme file) with following content:
```
{
    "cwd": "app"
}
```
Let's see what happens when execute **bower install** from project root and from **[project_path]/app** subfolder (where you should execute it).  
If you execute command from project root. It will search all **.bowerrc** configs from current folder (which is project root) and goes up to "/". After that it have variable "cwd" (current working folder) equals "**app**", since it is relative path it converts it into absolute using current folder (where you have execute bower) as base folder. It will equal "**[project_path]/app**". At this point bower stopped searching **.bowerrc** files even inside that new **current working directory**. So despite it've executed correctly it will install packages into standard **bower_components** folder not into your **my_bower_components**.  
Next. If you execute command from that **[project_path]/app** folder. Bower found two **.bowerrc** files: one with "**directory**" variable and one in project's root with "**cwd**". After that it concatenate its content and evaluates it as it was single **[project_path]/app/.bowerrc**. Since that concatenated config evaluated from **[project_path]/app** folder then new **current working directory** will be "**[project_path]/app/app**". And of course there no **bower.json** file there. And you will receive error:
```
bower ENOENT        No bower.json present
```
My advice either delete **.bowerrc** files from upper folder if you have created them accidentally. Or edit all of them and remove "**cwd**" setting from them.

**Comment by DonAurelio** [comment]
donnanicolas, I had the same problem (ENOENT No bower.json present) it occur when I used "bower install bower.js" to create the bower_compenents folder. To solve that problem I removed the folder from static/bower_components (in a Django application ) and tried to install it again but used only the command "bower install" in the same folder of bower.json file. 

After that it works.

**Comment by sheerun** [comment]
So to recap one last time: `bower install bower.json` is NOT a correct comment. It installs package named "bower.json".

**What you want to use is just `bower install`.**
