### ISSUE TITLE
Issue with installing Bootstrap framework with bower

### ISSUE THREAD

**Issue by theartsnetwork** [bower/bower#1931]
when I tried $ bower install bootstrap from Angular app directory it givens me this 

$bower install bootstrap
/usr/local/lib/node_modules/bower/node_modules/insight/node_modules/configstore/index.js:46
				throw err;
				      ^
Error: EACCES, permission denied '/Users/username/.config/configstore/insight-bower.json'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (fs.js:502:18)
    at Object.fs.readFileSync (fs.js:354:15)
    at Object.create.all.get (/usr/local/lib/node_modules/bower/node_modules/insight/node_modules/configstore/index.js:27:26)
    at Object.Configstore (/usr/local/lib/node_modules/bower/node_modules/insight/node_modules/configstore/index.js:20:44)
    at new Insight (/usr/local/lib/node_modules/bower/node_modules/insight/lib/index.js:37:34)
    at ensureInsight (/usr/local/lib/node_modules/bower/lib/util/analytics.js:25:19)
    at Object.setup (/usr/local/lib/node_modules/bower/lib/util/analytics.js:41:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/bower/bin/bower:72:11)
    at Module._compile (module.js:460:26)

I tried sudo chown -R username /Users/username/.config/configstore/
and then $bower install bootstrap 

bower EACCES        EACCES, open '/Users/username/.cache/bower/registry/bower.herokuapp.com/lookup/bootstrap_ca4c5'

Stack trace:
Error: EACCES, open '/Users/username/.cache/bower/registry/bower.herokuapp.com/lookup/bootstrap_ca4c5'
    at Error (native)

Console trace:
Error
    at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:82:37)
    at Logger.<anonymous> (/usr/local/lib/node_modules/bower/bin/bower:110:22)
    at Logger.emit (events.js:107:17)
    at Logger.emit (/usr/local/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/local/lib/node_modules/bower/lib/commands/index.js:45:20
    at _rejected (/usr/local/lib/node_modules/bower/node_modules/q/q.js:844:24)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:870:30
    at Promise.when (/usr/local/lib/node_modules/bower/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/node_modules/q/q.js:788:41)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:604:44
System info:
Bower version: 1.5.3
Node version: 0.12.0
OS: Darwin 14.4.0 x64

**Comment by sheerun** [comment]
Maybe try `sudo chown -R username ~/.config ~/.cache`?

**Comment by theartsnetwork** [comment]
It seems it worked for Bootstrap download but again trowing the same error for JQuery & Angular-Bootstrap UI 

$ bower install bootstrap
bower cached        git://github.com/twbs/bootstrap.git#3.3.5
bower validate      3.3.5 against git://github.com/twbs/bootstrap.git#*
bower cached        git://github.com/jquery/jquery.git#2.1.4
bower validate      2.1.4 against git://github.com/jquery/jquery.git#>= 1.9.1
bower install       bootstrap#3.3.5
bower install       jquery#2.1.4
bower EACCES        EACCES: permission denied, mkdir '/Users/akshayjirage/AMDAweb ng/app/bower_components/bootstrap'

Stack trace:
/usr/local/lib/node_modules/bower/node_modules/fstream/lib/dir-writer.js:35:25
/usr/local/lib/node_modules/bower/node_modules/mkdirp/index.js:46:53
FSReqWrap.oncomplete (fs.js:82:15)

Console trace:
Error
    at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:82:37)
    at Logger.<anonymous> (/usr/local/lib/node_modules/bower/bin/bower:110:22)
    at emitOne (events.js:77:13)
    at Logger.emit (events.js:169:7)
    at Logger.emit (/usr/local/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/local/lib/node_modules/bower/lib/commands/index.js:45:20
    at _rejected (/usr/local/lib/node_modules/bower/node_modules/q/q.js:844:24)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:870:30
    at Promise.when (/usr/local/lib/node_modules/bower/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/node_modules/q/q.js:788:41)
System info:
Bower version: 1.5.3
Node version: 4.1.1
OS: Darwin 14.4.0 x64


$ bower install angular-bootstrap
bower cached        git://github.com/angular-ui/bootstrap-bower.git#0.13.4
bower validate      0.13.4 against git://github.com/angular-ui/bootstrap-bower.git#*
bower install       angular-bootstrap#0.13.4
bower EACCES        EACCES: permission denied, mkdir '/Users/akshayjirage/AMDAweb ng/app/bower_components/angular-bootstrap'

Stack trace:
/usr/local/lib/node_modules/bower/node_modules/fstream/lib/dir-writer.js:35:25
/usr/local/lib/node_modules/bower/node_modules/mkdirp/index.js:46:53
FSReqWrap.oncomplete (fs.js:82:15)

Console trace:
Error
    at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:82:37)
    at Logger.<anonymous> (/usr/local/lib/node_modules/bower/bin/bower:110:22)
    at emitOne (events.js:77:13)
    at Logger.emit (events.js:169:7)
    at Logger.emit (/usr/local/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/local/lib/node_modules/bower/lib/commands/index.js:45:20
    at _rejected (/usr/local/lib/node_modules/bower/node_modules/q/q.js:844:24)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:870:30
    at Promise.when (/usr/local/lib/node_modules/bower/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/node_modules/q/q.js:788:41)
System info:
Bower version: 1.5.3
Node version: 4.1.1
OS: Darwin 14.4.0 x64


Please let me know little more about why this happens also?

**Comment by sheerun** [comment]
What happens when you run:

```mkdir -p /Users/username/AMDAweb ng/app/bower_components/bootstrap```

**Comment by theartsnetwork** [comment]
No folder is created and still giving the same error 

$ mkdir -p /Users/username/AMDAweb ng/app/bower_components/bootstrap
My-MaBook-Pro:AMDAweb ng username$ bower install bootstrap
bower cached        git://github.com/twbs/bootstrap.git#3.3.5
bower validate      3.3.5 against git://github.com/twbs/bootstrap.git#*
bower cached        git://github.com/jquery/jquery.git#2.1.4
bower validate      2.1.4 against git://github.com/jquery/jquery.git#>= 1.9.1
bower install       bootstrap#3.3.5
bower install       jquery#2.1.4
bower EACCES        EACCES: permission denied, mkdir '/Users/username/AMDAweb ng/app/bower_components/bootstrap'

Stack trace:
/usr/local/lib/node_modules/bower/node_modules/fstream/lib/dir-writer.js:35:25
/usr/local/lib/node_modules/bower/node_modules/mkdirp/index.js:46:53
FSReqWrap.oncomplete (fs.js:82:15)

Console trace:
Error
    at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:82:37)
    at Logger.<anonymous> (/usr/local/lib/node_modules/bower/bin/bower:110:22)
    at emitOne (events.js:77:13)
    at Logger.emit (events.js:169:7)
    at Logger.emit (/usr/local/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/local/lib/node_modules/bower/lib/commands/index.js:45:20
    at _rejected (/usr/local/lib/node_modules/bower/node_modules/q/q.js:844:24)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:870:30
    at Promise.when (/usr/local/lib/node_modules/bower/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/node_modules/q/q.js:788:41)
System info:
Bower version: 1.5.3
Node version: 4.1.1
OS: Darwin 14.4.0 x64

**Comment by sheerun** [comment]
Then your permissions there are again wrong:

```
sudo chown -R $USER "/Users/username/AMDAweb ng/app"
```

**Comment by theartsnetwork** [comment]
It worked well. Thanks very much!

**Comment by ExchangeEffect** [comment]
I was able to install bower successfully on my ubuntu 14.04  using npm install -g bower However when I run the command bower ---version I get an error message "/usr/bin/env: node: No such file or directory" and show I did check the user rights like this -rwxr-xr-x  1 root root       27232 Mar 10 14:10 env SO I did try a grep command as a super user and for bower string and I got the following error root@jra-table:/# grep -rl ".bowerrc"
grep: proc/sysrq-trigger: Input/output error

**Comment by sheerun** [comment]
It's probably solved in troubleshoot section: https://github.com/bower/bower/wiki/Troubleshooting#ubuntu-installation
