### ISSUE TITLE
Bower init error: Unable to perform highlight.

### ISSUE THREAD

**Issue by xtratio** [bower/bower#1947]
Hi i have the same error: #841
I tried to init bower.json file.
After question "would you like to mark this package as private which prevents it from being accidentally published to the registry?" there is an error:

```
bower error         Unable to perform highlight. The code contained syntax errors: Line 6: Unexpected token ILLEGAL

Stack trace:
Error: Unable to perform highlight. The code contained syntax errors: Line 6: Unexpected token ILLEGAL
    at throwError (C:\Users\user\AppData\Roaming\npm\node_modules\bower\node_modules\cardinal\node_modules\redeyed\node_modules\esprima\esprima.js:116
1:21)
    at scanStringLiteral (C:\Users\user\AppData\Roaming\npm\node_modules\bower\node_modules\cardinal\node_modules\redeyed\node_modules\esprima\esprima
.js:944:13)
    at Object.advance (C:\Users\user\AppData\Roaming\npm\node_modules\bower\node_modules\cardinal\node_modules\redeyed\node_modules\esprima\esprima.js
:1077:20)
    at collectToken (C:\Users\user\AppData\Roaming\npm\node_modules\bower\node_modules\cardinal\node_modules\redeyed\node_modules\esprima\esprima.js:3
293:23)
    at lookahead (C:\Users\user\AppData\Roaming\npm\node_modules\bower\node_modules\cardinal\node_modules\redeyed\node_modules\esprima\esprima.js:1118
:18)
    at match (C:\Users\user\AppData\Roaming\npm\node_modules\bower\node_modules\cardinal\node_modules\redeyed\node_modules\esprima\esprima.js:1239:21)

    at parseArrayInitialiser (C:\Users\user\AppData\Roaming\npm\node_modules\bower\node_modules\cardinal\node_modules\redeyed\node_modules\esprima\esp
rima.js:1312:17)
    at parsePrimaryExpression (C:\Users\user\AppData\Roaming\npm\node_modules\bower\node_modules\cardinal\node_modules\redeyed\node_modules\esprima\es
prima.js:1552:20)
    at C:\Users\user\AppData\Roaming\npm\node_modules\bower\node_modules\cardinal\node_modules\redeyed\node_modules\esprima\esprima.js:3609:38
    at trackLeftHandSideExpressionAllowCall (C:\Users\user\AppData\Roaming\npm\node_modules\bower\node_modules\cardinal\node_modules\redeyed\node_modu
les\esprima\esprima.js:3504:61)

Console trace:
Error
    at StandardRenderer.error (C:\Users\user\AppData\Roaming\npm\node_modules\bower\lib\renderers\StandardRenderer.js:82:37)
    at Logger.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\bower\bin\bower:110:22)
    at Logger.EventEmitter.emit (events.js:95:17)
    at Logger.emit (C:\Users\user\AppData\Roaming\npm\node_modules\bower\node_modules\bower-logger\lib\Logger.js:29:39)
    at C:\Users\user\AppData\Roaming\npm\node_modules\bower\lib\commands\index.js:45:20
    at _rejected (C:\Users\user\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:844:24)
    at C:\Users\user\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:870:30
    at Promise.when (C:\Users\user\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:1122:31)
    at Promise.promise.promiseDispatch (C:\Users\user\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:788:41)
    at C:\Users\user\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:604:44
System info:
Bower version: 1.5.3
Node version: 0.10.28
OS: Windows_NT 6.1.7601 x64
```

**Comment by sheerun** [comment]
Can you try again with bower 1.6.2?

**Comment by xtratio** [comment]
I tried to update bower (npm install -g bower), and thought that I have the latest version.
But I had an older version nodejs and npm, and that did not allow me to install the latest version of bower.
I updated nodejs, npm.
After that was able to update bower to 1.6.2
Problem solved, thanks!

**Comment by fabest** [comment]
I have same error, but i can't update managers, help me please =(

'''
bower error         Unable to perform highlight. The code contained syntax errors: Line 4: Unexpected token ILLEGAL

Stack trace:
Error: Unable to perform highlight. The code contained syntax errors: Line 4: Unexpected token ILLEGAL
    at throwError (C:\Users\Beard\AppData\Roaming\npm\node_modules\bower\node_modules\cardinal\node_modules\redeyed\node_modules\esprima\esprima.js:1161:21)
    at scanStringLiteral (C:\Users\Beard\AppData\Roaming\npm\node_modules\bower\node_modules\cardinal\node_modules\redeyed\node_modules\esprima\esprima.js:944:13)
    at Object.advance (C:\Users\Beard\AppData\Roaming\npm\node_modules\bower\node_modules\cardinal\node_modules\redeyed\node_modules\esprima\esprima.js:1077:20)
    at collectToken (C:\Users\Beard\AppData\Roaming\npm\node_modules\bower\node_modules\cardinal\node_modules\redeyed\node_modules\esprima\esprima.js:3293:23)
    at lookahead (C:\Users\Beard\AppData\Roaming\npm\node_modules\bower\node_modules\cardinal\node_modules\redeyed\node_modules\esprima\esprima.js:1118:18)
    at parseAssignmentExpression (C:\Users\Beard\AppData\Roaming\npm\node_modules\bower\node_modules\cardinal\node_modules\redeyed\node_modules\esprima\esprima.js:1992:17)
    at C:\Users\Beard\AppData\Roaming\npm\node_modules\bower\node_modules\cardinal\node_modules\redeyed\node_modules\esprima\esprima.js:3609:38
    at parseObjectProperty (C:\Users\Beard\AppData\Roaming\npm\node_modules\bower\node_modules\cardinal\node_modules\redeyed\node_modules\esprima\esprima.js:1425:28)
    at C:\Users\Beard\AppData\Roaming\npm\node_modules\bower\node_modules\cardinal\node_modules\redeyed\node_modules\esprima\esprima.js:3609:38
    at parseObjectInitialiser (C:\Users\Beard\AppData\Roaming\npm\node_modules\bower\node_modules\cardinal\node_modules\redeyed\node_modules\esprima\esprima.js:1449:24)

Console trace:
Error
    at StandardRenderer.error (C:\Users\Beard\AppData\Roaming\npm\node_modules\bower\lib\renderers\StandardRenderer.js:83:37)
    at Logger.<anonymous> (C:\Users\Beard\AppData\Roaming\npm\node_modules\bower\bin\bower:116:30)
    at emitOne (events.js:90:13)
    at Logger.emit (events.js:182:7)
    at Logger.emit (C:\Users\Beard\AppData\Roaming\npm\node_modules\bower\node_modules\bower-logger\lib\Logger.js:29:39)
    at C:\Users\Beard\AppData\Roaming\npm\node_modules\bower\lib\commands\index.js:48:20
    at _rejected (C:\Users\Beard\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:844:24)
    at C:\Users\Beard\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:870:30
    at Promise.when (C:\Users\Beard\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:1122:31)
    at Promise.promise.promiseDispatch (C:\Users\Beard\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:788:41)
System info:
Bower version: 1.7.2
Node version: 5.5.0
OS: Windows_NT 10.0.10586 x64
'''

**Comment by xoorath** [comment]
Hey, I'm getting this issue on bower 1.8.0, with node v6.9.5 and npm 3.10.10


```
{lamb} bower init
 =====================Started:
? main file index.js
? keywords
? authors xoorath <jared@xoorath.com>
? license ISC
? homepage https://github.com/xoorath/miniature-disco
? set currently installed components as dependencies? Yes
? add commonly ignored files to ignore list? Yes
? would you like to mark this package as private which prevents it from being accidentally published to the reg? would you like to mark this package as private which prevents it from being accidentally published to the registry? No
bower error         Unable to perform highlight. The code contained syntax errors: Line 4: Unexpected token ILLEGAL

Stack trace:
Error: Unable to perform highlight. The code contained syntax errors: Line 4: Unexpected token ILLEGAL
    at throwError (C:\Users\xoorath\AppData\Roaming\npm\node_modules\bower\lib\node_modules\esprima\esprima.js:1161:21)
    at scanStringLiteral (C:\Users\xoorath\AppData\Roaming\npm\node_modules\bower\lib\node_modules\esprima\esprima.js:944:13)
    at Object.advance (C:\Users\xoorath\AppData\Roaming\npm\node_modules\bower\lib\node_modules\esprima\esprima.js:1077:20)
    at collectToken (C:\Users\xoorath\AppData\Roaming\npm\node_modules\bower\lib\node_modules\esprima\esprima.js:3293:23)
    at lookahead (C:\Users\xoorath\AppData\Roaming\npm\node_modules\bower\lib\node_modules\esprima\esprima.js:1118:18)
    at parseAssignmentExpression (C:\Users\xoorath\AppData\Roaming\npm\node_modules\bower\lib\node_modules\esprima\esprima.js:1992:17)
    at C:\Users\xoorath\AppData\Roaming\npm\node_modules\bower\lib\node_modules\esprima\esprima.js:3609:38
    at parseObjectProperty (C:\Users\xoorath\AppData\Roaming\npm\node_modules\bower\lib\node_modules\esprima\esprima.js:1425:28)
    at C:\Users\xoorath\AppData\Roaming\npm\node_modules\bower\lib\node_modules\esprima\esprima.js:3609:38
    at parseObjectInitialiser (C:\Users\xoorath\AppData\Roaming\npm\node_modules\bower\lib\node_modules\esprima\esprima.js:1449:24)

Console trace:
Error
    at StandardRenderer.error (C:\Users\xoorath\AppData\Roaming\npm\node_modules\bower\lib\renderers\StandardRenderer.js:81:37)
    at Logger.<anonymous> (C:\Users\xoorath\AppData\Roaming\npm\node_modules\bower\lib\bin\bower.js:110:26)
    at emitOne (events.js:96:13)
    at Logger.emit (events.js:188:7)
    at Logger.emit (C:\Users\xoorath\AppData\Roaming\npm\node_modules\bower\lib\node_modules\bower-logger\lib\Logger.js:29:39)
    at C:\Users\xoorath\AppData\Roaming\npm\node_modules\bower\lib\commands\index.js:48:20
    at _rejected (C:\Users\xoorath\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:844:24)
    at C:\Users\xoorath\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:870:30
    at Promise.when (C:\Users\xoorath\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:1122:31)
    at Promise.promise.promiseDispatch (C:\Users\xoorath\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:788:41)
System info:
Bower version: 1.8.0
Node version: 6.9.5
OS: Windows_NT 10.0.14393 x64
```
