### ISSUE TITLE
v1.6.2 .bowerrc registry.register.replace undefined 

### ISSUE THREAD

**Issue by anwalkers** [bower/bower#1950]
If the .bowerrc has the registry configuration element, bower fails on Windows.

<pre><code>$ bower
C:\Users\username\AppData\Roaming\npm\node_modules\bower\node_modules\bower-config\lib\Config.js:96
    config.registry.register = config.registry.register.replace(/\/+$/, '');
                                                       ^

TypeError: Cannot read property 'replace' of undefined
    at normalise (C:\Users\username\AppData\Roaming\npm\node_modules\bower\node_modules\bower-config\lib\Config.js:96:56)
    at Config.load (C:\Users\username\AppData\Roaming\npm\node_modules\bower\node_modules\bower-config\lib\Config.js:23:20)
    at readCachedConfig (C:\Users\username\AppData\Roaming\npm\node_modules\bower\lib\config.js:15:39)
    at defaultConfig (C:\Users\username\AppData\Roaming\npm\node_modules\bower\lib\config.js:11:12)
    at Object.<anonymous> (C:\Users\username\AppData\Roaming\npm\node_modules\bower\lib\index.js:40:32)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)</code></pre>

Working .bowerrc:

<pre><code>{
    "directory": "app/components"
}</code></pre>

Failing .bowerrc

<pre><code>{
    "directory": "app/components",
    "registry": {
        "search": [ "https://bower.herokuapp.com" ]
    }
}</code></pre>

**Comment by joscha** [comment]
We have the same problem, but on Linux, so it doesn't seem to be OS-related.

`.bowerrc`:

```json
{
  "directory" : "bower_components"
}
```

**Comment by rowanbeentje** [comment]
If you specify bower.search, also specifying bower.register and bower.publish values will act as a workaround, but the documentation doesn't seem to suggest these are all required if search is specified.

**Comment by sheerun** [comment]
Should be fixed in bower 1.6.3. Thanks for the report
