### ISSUE TITLE
Error: EACCES: permission denied for bower install bootstrap or anything else

### ISSUE THREAD

**Issue by Jojokats** [bower/bower#1978]
When typing bower install jquery --save (or even bootstrap, fontawesome...)
I get the following error:
Error: EACCES: permission denied, open '/Users/joannak/.config/configstore/insight-bower.json'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.create.all.get (/usr/local/lib/node_modules/bower/node_modules/insight/node_modules/configstore/index.js:27:26)
    at Object.Configstore (/usr/local/lib/node_modules/bower/node_modules/insight/node_modules/configstore/index.js:20:44)
    at new Insight (/usr/local/lib/node_modules/bower/node_modules/insight/lib/index.js:37:34)
    at ensureInsight (/usr/local/lib/node_modules/bower/lib/util/analytics.js:38:23)
    at Object.setup (/usr/local/lib/node_modules/bower/lib/util/analytics.js:55:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/bower/bin/bower:72:11)
    at Module._compile (module.js:435:26)

Can anyone please help to fix this. I'm on a mac.
I sudo npm install -g bower beforehand.

Thanks in advance!

**Comment by sspreitzer** [comment]
Hi @Jojokats. Have you checked which user you are using to run the command and if the user has access to the path?
It looks like a problem with your clients filesystem permissions rather a problem with bower.

**Comment by Jojokats** [comment]
@sspreitzer  Thanks for your feedback! You are right, it was permissions, but got it fixed. I used chmod and chown on my .config folder Recursively and everything is fine now!

**Comment by apwete** [comment]
@Jojokats Are you using OS 10.11.x (El Capitan)?  If so can you explain the process you used? I am to new to CMD/Terminal to grasp from your comment.

If not, I am using OS 10.11.x (El Capitan), and getting the same error. Any help?

Apple Support Page for this issue: [http://apple.stackexchange.com/questions/193368/what-is-the-rootless-feature-in-el-capitan-really?newreg=068dc403fea74a3eb1e434b955924023]

After following the instructions the issue remained.  I have yet to solve this issue.

Does anyone have the fix?

**Comment by Jojokats** [comment]
@apwete At the time I was on Yosemite  and I had a friend help me out cause I was going around in circles. What I did also was contact support at npm which the problem I think is related to them. The support team can give you instructions on what to do.

**Comment by nitrokevin** [comment]
I did `sudo chown -R $(whoami) ~/.config` and it fixed mine

**Comment by johnguilbertc** [comment]
# @nitrokevin Thanks Bro, this one solved mine!
