### ISSUE TITLE
Error installing package where using git@github.com:..

### ISSUE THREAD

**Issue by stiig** [bower/bower#1998]
I'm trying to install a package, but kept running into an error. Git config corrected according to the instruction does not help

```
bower install asscroll --save -V
bower not-cached    git://github.com/amazingSurge/jquery-asscroll.git#*
bower resolve       git://github.com/amazingSurge/jquery-asscroll.git#*
bower checkout      asscroll#master
bower resolved      git://github.com/amazingSurge/jquery-asscroll.git#d78770bb8a
bower not-cached    git@github.com:amazingSurge/easing.css.git#*
bower resolve       git@github.com:amazingSurge/easing.css.git#*
bower ECMDERR       Failed to execute "git ls-remote --tags --heads git@github.com:amazingSurge/easing.css.git", exit code of #128 Permission denied (publickey). fatal: Could not read from remote repository.  Please make sure you have the correct access rights and the repository exists.

Additional error details:
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Stack trace:
Error: Failed to execute "git ls-remote --tags --heads git@github.com:amazingSurge/easing.css.git", exit code of #128
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
    at createError (C:\Users\pc\AppData\Roaming\npm\node_modules\bower\lib\util\createError.js:4:15)
    at ChildProcess.<anonymous> (C:\Users\pc\AppData\Roaming\npm\node_modules\bower\lib\util\cmd.js:102:21)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
From previous event:
    at executeCmd (C:\Users\pc\AppData\Roaming\npm\node_modules\bower\lib\util\cmd.js:61:22)
    at PThrottler._processEntry (C:\Users\pc\AppData\Roaming\npm\node_modules\bower\node_modules\p-throttler\index.js:89:25)
    at Promise.apply (C:\Users\pc\AppData\Roaming\npm\node_modules\bower\node_modules\p-throttler\node_modules\q\q.js:1122:26)
    at Promise.promise.promiseDispatch (C:\Users\pc\AppData\Roaming\npm\node_modules\bower\node_modules\p-throttler\node_modules\q\q.js:752:41)
    at C:\Users\pc\AppData\Roaming\npm\node_modules\bower\node_modules\p-throttler\node_modules\q\q.js:1337:14
    at flush (C:\Users\pc\AppData\Roaming\npm\node_modules\bower\node_modules\p-throttler\node_modules\q\q.js:108:17)

Console trace:
Error
    at StandardRenderer.error (C:\Users\pc\AppData\Roaming\npm\node_modules\bower\lib\renderers\StandardRenderer.js:82:37)
    at Logger.<anonymous> (C:\Users\pc\AppData\Roaming\npm\node_modules\bower\bin\bower:110:22)
    at emitOne (events.js:77:13)
    at Logger.emit (events.js:169:7)
    at Logger.emit (C:\Users\pc\AppData\Roaming\npm\node_modules\bower\node_modules\bower-logger\lib\Logger.js:29:39)
    at C:\Users\pc\AppData\Roaming\npm\node_modules\bower\lib\commands\index.js:48:20
    at _rejected (C:\Users\pc\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:844:24)
    at C:\Users\pc\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:870:30
    at Promise.when (C:\Users\pc\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:1122:31)
    at Promise.promise.promiseDispatch (C:\Users\pc\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:788:41)
System info:
Bower version: 1.6.5
Node version: 5.0.0
OS: Windows_NT 6.1.7601 x64
```

Command to correct git
```
git config --global url."https://".insteadOf git://
```

`.gitconfig`
```
...
[url "https://"]
	insteadOf = git://

```
this didn't work

`.boverrc`, i don't use proxy
```
{
  "strict-ssl": false,
  "directory": "agrorders/static/vendor"
}
```

Please add feature - "Using only https"

**Comment by stiig** [comment]
It helped only the following command
```
git config --global url."https://github.com/".insteadOf git@github.com:
```

**Comment by faceleg** [comment]
Solved? Thanks for updating with the answer.

**Comment by stiig** [comment]
You can not do it at Bower level?

**Comment by faceleg** [comment]
This is not a bower issue, it is working as expected. See https://github.com/amazingSurge/jquery-asScroll/blob/master/bower.json#L14

**Comment by stiig** [comment]
Oh, right, sorry

**Comment by faceleg** [comment]
No not sorry! Happy to help isolate the cause. :)

**Comment by atulkale96** [comment]
please give me exact code for same problem
