### ISSUE TITLE
bower init - TypeError: Cannot read property 'substring' of undefined

### ISSUE THREAD

**Issue by kurbar** [bower/bower#2000]
I've been having issues with initialising bower in my projects. I've tried with 1.6.4 and 1.6.5 but both give the same issue.

```
$ bower init --config.interactive
bower error         Cannot read property 'substring' of undefined

Stack trace:
TypeError: Cannot read property 'substring' of undefined
    at Interface.rl._getCursorPos (C:\Users\Karl\AppData\Roaming\npm\node_modules\bower\node_modules\inquirer\node_modules\readline2\index.js:51:51)
    at ScreenManager.render (C:\Users\Karl\AppData\Roaming\npm\node_modules\bower\node_modules\inquirer\lib\utils\screen-manager.js:19:27)
    at Prompt.render (C:\Users\Karl\AppData\Roaming\npm\node_modules\bower\node_modules\inquirer\lib\prompts\input.js:75:15)
    at Prompt._run (C:\Users\Karl\AppData\Roaming\npm\node_modules\bower\node_modules\inquirer\lib\prompts\input.js:49:8)
    at Prompt.run (C:\Users\Karl\AppData\Roaming\npm\node_modules\bower\node_modules\inquirer\lib\prompts\base.js:57:8)
    at Object.<anonymous> (C:\Users\Karl\AppData\Roaming\npm\node_modules\bower\node_modules\inquirer\lib\ui\prompt.js:84:12)
    at module.exports (C:\Users\Karl\AppData\Roaming\npm\node_modules\bower\node_modules\inquirer\node_modules\run-async\index.js:15:21)
    at AnonymousObservable.__subscribe (C:\Users\Karl\AppData\Roaming\npm\node_modules\bower\node_modules\inquirer\lib\utils\utils.js:16:7)
    at AnonymousObservable.tryCatcher (C:\Users\Karl\AppData\Roaming\npm\node_modules\bower\node_modules\inquirer\node_modules\rx-lite\rx.lite.js:63:31)
    at setDisposable (C:\Users\Karl\AppData\Roaming\npm\node_modules\bower\node_modules\inquirer\node_modules\rx-lite\rx.lite.js:5741:44)

Console trace:
Error
    at StandardRenderer.error (C:\Users\Karl\AppData\Roaming\npm\node_modules\bower\lib\renderers\StandardRenderer.js:82:37)
    at Logger.<anonymous> (C:\Users\Karl\AppData\Roaming\npm\node_modules\bower\bin\bower:110:22)
    at Logger.emit (events.js:107:17)
    at Logger.emit (C:\Users\Karl\AppData\Roaming\npm\node_modules\bower\node_modules\bower-logger\lib\Logger.js:29:39)
    at C:\Users\Karl\AppData\Roaming\npm\node_modules\bower\lib\commands\index.js:48:20
    at _rejected (C:\Users\Karl\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:844:24)
    at C:\Users\Karl\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:870:30
    at Promise.when (C:\Users\Karl\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:1122:31)
    at Promise.promise.promiseDispatch (C:\Users\Karl\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:788:41)
    at C:\Users\Karl\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:604:44
System info:
Bower version: 1.6.4
Node version: 0.12.7
OS: Windows_NT 6.3.9600 x64
```

Is this a known issue or just me?

**Comment by DHNCarlos** [comment]
I updated NodeJS to `5.0.0` but hte issue persists.

**Comment by faceleg** [comment]
Could be a bug in readline2, could you open an issue there?

**Comment by ErmolaevaEkaterina** [comment]
I've got just the same problem. What line do you mean exactly?

**Comment by seethemhigh** [comment]
Does this issue persist on NodeJS `5.1.0`?
That might be an issue on the NodeJS side. Check this conversations out: https://github.com/SBoudrias/Inquirer.js/issues/272 and https://github.com/nodejs/node/issues/3006. The latter one sheds some light on how node command line apps work in Windows, and might be a solution to the problem. Are you running bower in cygwin or something similar?

**Comment by faceleg** [comment]
@DHNCarlos did you open an issue with readline2?

**Comment by pertrai1** [comment]
@DHNCarlos Did you follow up on the suggestion from @faceleg ? I took a look at the repo for readmine2 and does not look to be actively maintained so did not know if the issues are related to the project not staying up with the newer releases of NodeJS.

**Comment by CamronBute** [comment]
I am having this same problem

**Comment by daprezjer** [comment]
Ditto, I'm fairly new to bower, however.  Today on my Windows 10 Pro machine I:
- installed latest Git for Windows
- ran "npm install -g bower"
- ran "bower init" and received a "Register requires an interactive shell, you can manually force an interactive shell with --config.interactive" message
- ran "bower init --config.interactive" and received the same error as above.

 Let me know if there's any more information I can provide.

**Comment by kaiocb** [comment]
@daprezjer, can you tell us more about your environment too?
I performed some tests against:

>Windows 8.x 

>Bower 1.7.2/1.7.1/1.6.5/1.6.4

>Latest LTS 4.2.4 NodeJS

> Git 2.6.4 

`bower init` seems to be working.

**Comment by Infro** [comment]
Had similar problem, fixed it with some combination of switching to normal command prompt and not using config.interactive fixed

Bower version: 1.7.7
Node version: 5.5.0
OS: Windows_NT 6.1.7601 x64

**Comment by DHNCarlos** [comment]
@faceleg @pertrai1 Apologies for not getting back sooner. No I haven't created an issue on readline2 as of yet. Though for now I've resolved the issue by using Windows own Command Prompt and it seems to be working okay there. The issue might be with the interactive config that Gits MINGW64 terminal requires but in Windows Cmd the interactive config flag isn't needed and it seems to work okay.

**Comment by MFry** [comment]
Issue persists on windows 7 in git bash/MINGW64

    System info:
    Bower version: 1.7.9
    Node version: 6.2.0
    OS: Windows_NT 6.1.7601 x64

    $ git --version
    git version 2.7.0.windows.1

**Comment by qertis** [comment]
I have same bug 
```
Prefix the choice with ! to persist it to bower.json

bower                                                 error Cannot read property 'substring' of undefined

Stack trace:
TypeError: Cannot read property 'substring' of undefined
    at Interface.rl._getCursorPos (C:\Users\iavto\Desktop\polymer-starter-kit\node_modules\bower\lib\node_modules\readline2\index.js:51:51)
    at ScreenManager.render (C:\Users\iavto\Desktop\polymer-starter-kit\node_modules\bower\lib\node_modules\inquirer\lib\utils\screen-manager.js:19:27)
    at Prompt.render (C:\Users\iavto\Desktop\polymer-starter-kit\node_modules\bower\lib\node_modules\inquirer\lib\prompts\input.js:75:15)
    at Prompt._run (C:\Users\iavto\Desktop\polymer-starter-kit\node_modules\bower\lib\node_modules\inquirer\lib\prompts\input.js:49:8)
    at Prompt.run (C:\Users\iavto\Desktop\polymer-starter-kit\node_modules\bower\lib\node_modules\inquirer\lib\prompts\base.js:57:8)
    at Object.<anonymous> (C:\Users\iavto\Desktop\polymer-starter-kit\node_modules\bower\lib\node_modules\inquirer\lib\ui\prompt.js:84:12)
    at module.exports (C:\Users\iavto\Desktop\polymer-starter-kit\node_modules\bower\lib\node_modules\run-async\index.js:15:21)
    at AnonymousObservable.__subscribe (C:\Users\iavto\Desktop\polymer-starter-kit\node_modules\bower\lib\node_modules\inquirer\lib\utils\utils.js:16:7)
    at AnonymousObservable.tryCatcher (C:\Users\iavto\Desktop\polymer-starter-kit\node_modules\bower\lib\node_modules\rx-lite\rx.lite.js:63:31)
    at setDisposable (C:\Users\iavto\Desktop\polymer-starter-kit\node_modules\bower\lib\node_modules\rx-lite\rx.lite.js:5741:44)

Console trace:
Error
    at StandardRenderer.error (C:\Users\iavto\Desktop\polymer-starter-kit\node_modules\bower\lib\renderers\StandardRenderer.js:81:37)
    at Logger.<anonymous> (C:\Users\iavto\Desktop\polymer-starter-kit\node_modules\bower\lib\bin\bower.js:110:26)
    at emitOne (events.js:90:13)
    at Logger.emit (events.js:182:7)
    at Logger.emit (C:\Users\iavto\Desktop\polymer-starter-kit\node_modules\bower\lib\node_modules\bower-logger\lib\Logger.js:29:39)
    at C:\Users\iavto\Desktop\polymer-starter-kit\node_modules\bower\lib\commands\index.js:48:20
    at _rejected (C:\Users\iavto\Desktop\polymer-starter-kit\node_modules\bower\lib\node_modules\q\q.js:844:24)
    at C:\Users\iavto\Desktop\polymer-starter-kit\node_modules\bower\lib\node_modules\q\q.js:870:30
    at Promise.when (C:\Users\iavto\Desktop\polymer-starter-kit\node_modules\bower\lib\node_modules\q\q.js:1122:31)
    at Promise.promise.promiseDispatch (C:\Users\iavto\Desktop\polymer-starter-kit\node_modules\bower\lib\node_modules\q\q.js:788:41)
System info:
Bower version: 1.7.9
Node version: 5.5.0
OS: Windows_NT 10.0.10586 ia32
```

I create a new bower.json, change .bowerrc 
```
{
  "registry": "http://bower.herokuapp.com"
}
```
and exec ```bower init```. Resolve packet conflicts. Then all works.

**Comment by adolfoaugusto** [comment]
installing windows with bash git works good
follows the order, npm install -g bower, bower .... init and its dependencies.

**Comment by Daniel-Hug** [comment]
I came here from the related issue #802. This [workaround](https://github.com/bower/bower/issues/802#issuecomment-181073654) is presented:

> run bower init using CMD
>
> OR
>
> if you are using git bash follow these steps:
>
> 1. Uninstall existing GIT bash
> 2. Reinstall GIT bash
> 3. Set up during installation:
>    1. Select > Use Git form the Windows Command Prompt
>    1. Select > Checkout Windows-style, commit Unix-style line endings
>    1. Select > Use Windows' default console window

**Comment by musamamasood** [comment]
Getting same bug on Window 8. 

`Stack trace:
TypeError: Cannot read property 'substring' of undefined
    at Interface.rl._getCursorPos (C:\Users\masood.usama\AppData\Roaming\npm\node_modules\bower\lib\node_modules\readline2\index.js:51:51)
    at ScreenManager.render (C:\Users\masood.usama\AppData\Roaming\npm\node_modules\bower\lib\node_modules\inquirer\lib\utils\screen-manager.js:19:27)
    at Prompt.render (C:\Users\masood.usama\AppData\Roaming\npm\node_modules\bower\lib\node_modules\inquirer\lib\prompts\input.js:75:15)
    at Prompt._run (C:\Users\masood.usama\AppData\Roaming\npm\node_modules\bower\lib\node_modules\inquirer\lib\prompts\input.js:49:8)
    at Prompt.run (C:\Users\masood.usama\AppData\Roaming\npm\node_modules\bower\lib\node_modules\inquirer\lib\prompts\base.js:57:8)
    at Object.<anonymous> (C:\Users\masood.usama\AppData\Roaming\npm\node_modules\bower\lib\node_modules\inquirer\lib\ui\prompt.js:84:12)
    at module.exports (C:\Users\masood.usama\AppData\Roaming\npm\node_modules\bower\lib\node_modules\run-async\index.js:15:21)
    at AnonymousObservable.__subscribe (C:\Users\masood.usama\AppData\Roaming\npm\node_modules\bower\lib\node_modules\inquirer\lib\utils\utils.js:16:7)
    at AnonymousObservable.tryCatcher (C:\Users\masood.usama\AppData\Roaming\npm\node_modules\bower\lib\node_modules\rx-lite\rx.lite.js:63:31)
    at setDisposable (C:\Users\masood.usama\AppData\Roaming\npm\node_modules\bower\lib\node_modules\rx-lite\rx.lite.js:5741:44)

Console trace:
Error
    at StandardRenderer.error (C:\Users\masood.usama\AppData\Roaming\npm\node_modules\bower\lib\renderers\StandardRenderer.js:81:37)
    at Logger.<anonymous> (C:\Users\masood.usama\AppData\Roaming\npm\node_modules\bower\lib\bin\bower.js:110:26)
    at emitOne (events.js:77:13)
    at Logger.emit (events.js:169:7)
    at Logger.emit (C:\Users\masood.usama\AppData\Roaming\npm\node_modules\bower\lib\node_modules\bower-logger\lib\Logger.js:29:39)
    at C:\Users\masood.usama\AppData\Roaming\npm\node_modules\bower\lib\commands\index.js:48:20
    at _rejected (C:\Users\masood.usama\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:844:24)
    at C:\Users\masood.usama\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:870:30
    at Promise.when (C:\Users\masood.usama\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:1122:31)
    at Promise.promise.promiseDispatch (C:\Users\masood.usama\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:788:41)
System info:
Bower version: 1.8.0
Node version: 4.2.5
OS: Windows_NT 6.3.9600 x64`

**Comment by keanedawg** [comment]
I likewise got it to work simply by going to command prompt. No administrative privilege required.

**Comment by sheerun** [comment]
Bower is deprecated and don't encourage creating new packages anymore, so I'm closing this
