### ISSUE TITLE
Error while resolving bower dependencies in Mean app

### ISSUE THREAD

**Issue by guptakvgaurav** [bower/bower#2009]
I tried to set up my mean project through `mean-cli` and while resolving dependencies, bower gave me errors.
```
bower ENOENT        ENOENT: no such file or directory, stat '/home/gaurav/node_lab/mean_app1/MyFirstMeanApp/node_modules/meanio/resources/web-bootstrap.js'

Stack trace:
Error: ENOENT: no such file or directory, stat '/home/gaurav/node_lab/mean_app1/MyFirstMeanApp/node_modules/meanio/resources/web-bootstrap.js'
    at Error (native)

Console trace:
Error
    at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:82:37)
    at Logger.<anonymous> (/usr/local/lib/node_modules/bower/bin/bower:110:22)
    at emitOne (events.js:77:13)
    at Logger.emit (events.js:169:7)
    at Logger.emit (/usr/local/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/local/lib/node_modules/bower/lib/commands/index.js:48:20
    at _rejected (/usr/local/lib/node_modules/bower/node_modules/q/q.js:844:24)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:870:30
    at Promise.when (/usr/local/lib/node_modules/bower/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/node_modules/q/q.js:788:41)
System info:
Bower version: 1.6.5

Node version: 4.2.1
OS: Linux 3.13.0-35-generic x64
```

**Comment by faceleg** [comment]
Can you please post the bower.json?

**Comment by guptakvgaurav** [comment]
{
  "name": "mean",
  "dependencies": {
    "jquery": "latest",
    "angular": "latest",
    "angular-resource": "latest",
    "angular-cookies": "latest",
    "angular-mocks": "latest",
    "angular-route": "latest",
    "bootstrap": "latest",
    "angular-bootstrap": "latest",
    "angular-ui-router": "#master",
    "web-bootstrap": "./node_modules/meanio/resources/web-bootstrap.js",
    "angular-ui-select": "latest",
    "angular-sanitize": "latest"
  }
}

**Comment by faceleg** [comment]
`"web-bootstrap": "./node_modules/meanio/resources/web-bootstrap.js",`

Does  this exist?

**Comment by pertrai1** [comment]
@guptakvgaurav See the question from @faceleg above. It does look like the error is calling out not being able to find the path for `web-bootstrap`. Thank you.

**Comment by faceleg** [comment]
@guptakvgaurav closing for now. Please reopen if you feel this is an issue with Boer
