### ISSUE TITLE
Please update handlebars

### ISSUE THREAD

**Issue by plynchnlm** [bower/bower#2016]
Version 4.0.x of handlebars has an update for its version of uglify-js, to avoid this [vulnerability](https://nodesecurity.io/advisories/39).  (The current version in package.json is only "handlebars": "^2.0.0".)

FWIW, I attempted to update packages myself and submit a pull request, but even before I changed anything, I could not get the tests to pass (12 failures), and so I gave up.

**Comment by sheerun** [comment]
I think we don't use uglify from handlebars, but update won't hurt.. We need to know what are the breaking changes between handlebars 2.0.0 and 4.0.0. Hm?

**Comment by sheerun** [comment]
Yup, we don't use "min" option from handlebars.

**Comment by patrickkettner** [comment]
https://github.com/wycats/handlebars.js/blob/master/release-notes.md, specifically the "Compatibility notes" sections

**Comment by sheerun** [comment]
We use handlebars as so:

```
    cache[name] = Handlebars.compile(contents, {
        noEscape: !escape
    });
```

And I can't find docs for noEscape, though. We need to make sure we handle it. PR is welcome.

@plynchnlm What were the error messages in tests? What's your platform?

**Comment by plynchnlm** [comment]
My platform is RHEL 6.7.  BTW-- It is now 4.0.5 of handlebars that is needed to avoid another [vulnerability](https://nodesecurity.io/advisories/48).  After changing package.json to use 4.0.5, the errors messages (from the tests) are as below.  I was thinking someone familiar with the bower code would be better able to resolve them.

  1) StandardRenderer outputs help command log:
     RangeError: Invalid array length
      at Object.assignToHash (node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:759:22)
      at Object.compile (node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:113:27)
      at Object.compileChildren (node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:794:49)
      at Object.compile (node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:97:10)
      at Object.compileChildren (node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:794:49)
      at Object.compile (node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:97:10)
      at Object.compileChildren (node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:794:49)
      at Object.compile (node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:97:10)
      at compileInput (node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:516:53)
      at Object.ret [as std/help-generic.std] (node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:523:18)
  From previous event:
      at Object.exports.capture (test/helpers.js:253:30)
      at Context.<anonymous> (test/renderers/StandardRenderer.js:755:24)

  2) integration tests bower runs bower installation:
     Uncaught RangeError: Invalid array length
      at Object.assignToHash (node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:759:22)
      at Object.compile (node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:113:27)
      at Object.compileChildren (node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:794:49)
      at Object.compile (node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:97:10)
      at Object.compileChildren (node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:794:49)
      at Object.compile (node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:97:10)
      at compileInput (node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:516:53)
      at Object.ret [as std/help.std] (node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:523:18)
      at render (lib/util/template.js:20:27)
      at Object.render (lib/util/template.js:30:12)
  From previous event:
      at withLogger (lib/commands/index.js:41:10)
      at Object.command [as help] (lib/commands/index.js:20:16)
      at bin/bower:80:33

  3) integration tests bower "after all" hook for "runs bower installation":
     Error: expected '\u001b[2K\u001b[0G    \u001b[31m  2) runs bower installation\u001b[0m\n' to contain 'Usage:'
      at Assertion.assert (node_modules/expect.js/index.js:96:13)
      at Assertion.string.Assertion.contain (node_modules/expect.js/index.js:410:12)
      at Context.<anonymous> (test/commands/bower.js:28:25)

**Comment by sheerun** [comment]
We don't use uglify feature of handlebars so vulnerability doesn't affect us

**Comment by pertrai1** [comment]
@plynchnlm @sheerun If uglify is the main issue when it comes to the vulnerability and Bower does not use it, is this an open issue?

**Comment by sheerun** [comment]
I'm closing this because it doesn't affect us, but if someone manages to update handlebars, and sends a working PR, I'd accept it.
