### ISSUE TITLE
Bower crashes if .bowerrc is a directory

### ISSUE THREAD

**Issue by Wilfred** [bower/bower#2022]
Whilst users probably shouldn't be creating .bowerrc directories, it would be helpful if bower showed a friendly error.

```
$ mkdir .bowerrc
$ bower install jquery

fs.js:481
  var r = binding.read(fd, buffer, offset, length, position);
                  ^
Error: EISDIR, illegal operation on a directory
    at Object.fs.readSync (fs.js:481:19)
    at Object.fs.readFileSync (fs.js:315:28)
    at /users/is/whughes/node_modules/bower/node_modules/bower-config/lib/util/rc.js:87:27
    at Array.forEach (native)
    at json (/users/is/whughes/node_modules/bower/node_modules/bower-config/lib/util/rc.js:86:14)
    at rc (/users/is/whughes/node_modules/bower/node_modules/bower-config/lib/util/rc.js:31:13)
    at Config.load (/users/is/whughes/node_modules/bower/node_modules/bower-config/lib/Config.js:16:20)
    at readCachedConfig (/users/is/whughes/node_modules/bower/lib/config.js:15:39)
    at defaultConfig (/users/is/whughes/node_modules/bower/lib/config.js:11:12)
    at Object.<anonymous> (/users/is/whughes/node_modules/bower/lib/index.js:40:32)
```

**Comment by faceleg** [comment]
You're right, an error would be preferable to a crash - PR? :smiley:

**Comment by prometheansacrifice** [comment]
@faceleg  Looks like an issue in [bower-config] (https://www.npmjs.com/package/bower-config). Raise this issue there?
