### ISSUE TITLE
Crash during interactive resolve

### ISSUE THREAD

**Issue by simenheg** [bower/bower#2034]
Hi,

Bower 1.6.5 crashes on the interactive resolve prompt when I do `bower install` with the following `bower.json` file:

```json
{
  "name": "foo",
  "dependencies": {
    "jquery": "2.1.4",
    "ember": "1.13.4",
    "ember-data": "1.13.5",
    "ember-resolver": "0.1.18",
    "loader.js": "3.2.1",
    "ember-cli-shims": "ember-cli/ember-cli-shims#0.0.3",
    "ember-cli-test-loader": "ember-cli-test-loader#0.1.3",
    "ember-load-initializers": "ember-cli/ember-load-initializers#0.1.5",
    "ember-qunit": "0.4.9",
    "ember-qunit-notifications": "0.0.7",
    "qunit": "1.18.0",
    "modularized-normalize-scss": "3.0.3",
    "moment": "2.10.3",
    "ravenjs": "1.1.19",
    "jed": "1.1.0"
  }
}
```

The command crashes before you get any chance to enter input. The produced output is:

```
bower cached        git://github.com/ember-cli/ember-cli-shims.git#0.0.3
bower validate      0.0.3 against git://github.com/ember-cli/ember-cli-shims.git#0.0.3
bower cached        git://github.com/ember-cli/ember-load-initializers.git#0.1.5
bower validate      0.1.5 against git://github.com/ember-cli/ember-load-initializers.git#0.1.5
bower cached        git://github.com/components/ember.git#1.13.4
bower validate      1.13.4 against git://github.com/components/ember.git#1.13.4
bower cached        git://github.com/stefanpenner/loader.js.git#3.2.1
bower validate      3.2.1 against git://github.com/stefanpenner/loader.js.git#3.2.1
bower cached        git://github.com/components/ember.git#1.13.11
bower validate      1.13.11 against git://github.com/components/ember.git#>= 1.8.1 < 2.0.0
bower cached        git://github.com/stefanpenner/ember-jj-abrams-resolver.git#0.1.18
bower validate      0.1.18 against git://github.com/stefanpenner/ember-jj-abrams-resolver.git#0.1.18
bower cached        git://github.com/components/ember-data.git#1.13.5
bower validate      1.13.5 against git://github.com/components/ember-data.git#1.13.5
bower cached        git://github.com/ember-cli/ember-cli-test-loader.git#0.1.3
bower validate      0.1.3 against git://github.com/ember-cli/ember-cli-test-loader.git#0.1.3
bower cached        git://github.com/components/ember.git#2.2.0
bower validate      2.2.0 against git://github.com/components/ember.git#>=1.4
bower cached        git://github.com/components/ember.git#2.2.0
bower validate      2.2.0 against git://github.com/components/ember.git#> 1.5.0-beta.3
bower cached        git://github.com/rwjblue/ember-qunit-builds.git#0.4.9
bower validate      0.4.9 against git://github.com/rwjblue/ember-qunit-builds.git#0.4.9
bower cached        git://github.com/dockyard/ember-qunit-notifications.git#0.0.7
bower validate      0.0.7 against git://github.com/dockyard/ember-qunit-notifications.git#0.0.7
bower cached        git://github.com/getsentry/raven-js.git#1.1.19
bower validate      1.1.19 against git://github.com/getsentry/raven-js.git#1.1.19
bower cached        git://github.com/jquery/qunit.git#1.18.0
bower validate      1.18.0 against git://github.com/jquery/qunit.git#1.18.0
bower cached        git://github.com/dockyard/qunit-notifications.git#0.0.6
bower validate      0.0.6 against git://github.com/dockyard/qunit-notifications.git#~0.0.6

Unable to find a suitable version for qunit-notifications, please choose one:
    1) qunit-notifications#~0.0.6 which resolved to 0.0.6 and is required by ember-qunit-notifications#0.0.7
    2) qunit-notifications#~0.1.0 which resolved to 0.1.0 and is required by ember-qunit-notifications#0.1.0

Prefix the choice with ! to persist it to bower.json

? Answer bower error         Invalid regular expression: /.{1,0}/: numbers out of order in {} quantifier.

Stack trace:
SyntaxError: Invalid regular expression: /.{1,0}/: numbers out of order in {} quantifier.
    at new RegExp (native)
    at breakLines (/usr/local/lib/node_modules/bower/node_modules/inquirer/lib/utils/screen-manager.js:108:15)
    at ScreenManager.render (/usr/local/lib/node_modules/bower/node_modules/inquirer/lib/utils/screen-manager.js:55:22)
    at Prompt.render (/usr/local/lib/node_modules/bower/node_modules/inquirer/lib/prompts/input.js:75:15)
    at Prompt._run (/usr/local/lib/node_modules/bower/node_modules/inquirer/lib/prompts/input.js:49:8)
    at Prompt.run (/usr/local/lib/node_modules/bower/node_modules/inquirer/lib/prompts/base.js:57:8)
    at Object.<anonymous> (/usr/local/lib/node_modules/bower/node_modules/inquirer/lib/ui/prompt.js:84:12)
    at module.exports (/usr/local/lib/node_modules/bower/node_modules/inquirer/node_modules/run-async/index.js:15:21)
    at AnonymousObservable.__subscribe (/usr/local/lib/node_modules/bower/node_modules/inquirer/lib/utils/utils.js:16:7)
    at AnonymousObservable.tryCatcher (/usr/local/lib/node_modules/bower/node_modules/inquirer/node_modules/rx-lite/rx.lite.js:63:31)

Console trace:
Error
    at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:82:37)
    at Logger.<anonymous> (/usr/local/lib/node_modules/bower/bin/bower:110:22)
    at Logger.emit (events.js:107:17)
    at Logger.emit (/usr/local/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/local/lib/node_modules/bower/lib/commands/index.js:48:20
    at _rejected (/usr/local/lib/node_modules/bower/node_modules/q/q.js:844:24)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:870:30
    at Promise.when (/usr/local/lib/node_modules/bower/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/node_modules/q/q.js:788:41)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:604:44
System info:
Bower version: 1.6.5
Node version: 0.12.2
OS: Linux 4.1.0-1-amd64 x64
[?25h
```

**Comment by ThomasCrvsr** [comment]
What did you typed when Bower asked you which version you want to install ?

**Comment by simenheg** [comment]
It crashes before I get a chance to type anything.

**Comment by pertrai1** [comment]
@simenheg - Hey I took your `bower.json` file and ran the same as you did. I did not get any issues as you did. Can we take this step by step and have you run `bower install` again and see if it happens to you or if it was just a one time thing. If we find that it was not a one time thing we will go to the next steps. Thank you.

**Comment by visikov** [comment]
@simenheg @pertrai1 Running bower 1.6.5, not running into any issue with that bower file.

**Comment by simenheg** [comment]
Hm, indeed, I tried to reinstall bower, and now I'm also unable to reproduce the crash with the file that I provided.

**Comment by wu-lee** [comment]
I've just seen this exact error, whilst running bower in an Emacs shell buffer.  I think the issue is that cliWidth() returns 0, thus this creates a regex `.{1,0}`:

    var regex = new RegExp('.{1,' + cliWidth() + '}', 'g');

Which is what the error is reporting.  The solution would be to simply use the largest of 1 or cliWidth().

**Comment by wu-lee** [comment]
For example, I've patched it like this:

    --- screen-manager.js~	2016-01-27 17:02:22.000000000 +0000
    +++ screen-manager.js	2016-03-08 16:43:36.176366258 +0000
    @@ -105,7 +105,10 @@
     function breakLines(lines) {
       // Break lines who're longuer than the cli width so we can gracefully handle line
       // returns.
    -  var regex = new RegExp('.{1,' + cliWidth() + '}', 'g');
    +  var max = cliWidth();
    +  if (max < 1)
    +    max = 1;
    +  var regex = new RegExp('.{1,' + max + '}', 'g');
       return lines.map(function (line) {
         return stripAnsi(line).match(regex);
       });

**Comment by shirish87** [comment]
Just encountered this when using bash in a docker container and running `bower install <dep>` and a version conflict prompt appeared but didn't wait for input before crash.

```
Stack trace:
SyntaxError: Invalid regular expression: /.{1,0}/: numbers out of order in {} quantifier
    at RegExp (native)
    at breakLines (/var/www/app/node_modules/bower/lib/node_modules/inquirer/lib/utils/screen-manager.js:108:15)
    at ScreenManager.render (/var/www/app/node_modules/bower/lib/node_modules/inquirer/lib/utils/screen-manager.js:55:22)
    at Prompt.render (/var/www/app/node_modules/bower/lib/node_modules/inquirer/lib/prompts/input.js:75:15)
    at Prompt._run (/var/www/app/node_modules/bower/lib/node_modules/inquirer/lib/prompts/input.js:49:8)
    at Prompt.run (/var/www/app/node_modules/bower/lib/node_modules/inquirer/lib/prompts/base.js:57:8)
    at Object.<anonymous> (/var/www/app/node_modules/bower/lib/node_modules/inquirer/lib/ui/prompt.js:84:12)
    at module.exports (/var/www/app/node_modules/bower/lib/node_modules/run-async/index.js:15:21)
    at AnonymousObservable.__subscribe (/var/www/app/node_modules/bower/lib/node_modules/inquirer/lib/utils/utils.js:16:7)
    at AnonymousObservable.tryCatcher (/var/www/app/node_modules/bower/lib/node_modules/rx-lite/rx.lite.js:63:31)

Console trace:
Error
    at StandardRenderer.error (/var/www/app/node_modules/bower/lib/renderers/StandardRenderer.js:81:37)
    at Logger.<anonymous> (/var/www/app/node_modules/bower/lib/bin/bower.js:110:26)
    at emitOne (events.js:96:13)
    at Logger.emit (events.js:188:7)
    at Logger.emit (/var/www/app/node_modules/bower/lib/node_modules/bower-logger/lib/Logger.js:29:39)
    at /var/www/app/node_modules/bower/lib/commands/index.js:48:20
    at _rejected (/var/www/app/node_modules/bower/lib/node_modules/q/q.js:844:24)
    at /var/www/app/node_modules/bower/lib/node_modules/q/q.js:870:30
    at Promise.when (/var/www/app/node_modules/bower/lib/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/var/www/app/node_modules/bower/lib/node_modules/q/q.js:788:41)
System info:
Bower version: 1.8.0
Node version: 6.10.3
OS: Linux 4.8.0-45-generic x64
```
