### ISSUE TITLE
is something breaking all versions?

### ISSUE THREAD

**Issue by SSS2557** [bower/bower#2037]
bower bootstrap-daterangepicker#jquery-fix                                      error key must be a string or number. undefined

Stack trace:
TypeError: key must be a string or number. undefined
    at typeCheckKey (/Users/shastry/whatever/node_modules/bower/node_modules/lru-cache/lib/lru-cache.js:18:11)
    at LRUCache.get (/Users/shastry/whatever/node_modules/bower/node_modules/lru-cache/lib/lru-cache.js:227:3)
    at /Users/shastry/whatever/node_modules/bower/lib/core/resolvers/GitRemoteResolver.js:122:70
    at _fulfilled (/Users/shastry/whatever/node_modules/bower/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/shastry/whatever/node_modules/bower/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/shastry/whatever/node_modules/bower/node_modules/q/q.js:796:13)
    at /Users/shastry/whatever/node_modules/bower/node_modules/q/q.js:857:14
    at runSingle (/Users/shastry/whatever/node_modules/bower/node_modules/q/q.js:137:13)
    at flush (/Users/shastry/whatever/node_modules/bower/node_modules/q/q.js:125:13)
    at process._tickCallback (node.js:448:13)

Console trace:
Error
    at StandardRenderer.error (/Users/shastry/whatever/node_modules/bower/lib/renderers/StandardRenderer.js:82:37)
    at Logger.<anonymous> (/Users/whatever/whatever/node_modules/bower/bin/bower:110:22)
    at Logger.emit (events.js:95:17)
    at Logger.emit (/Users/whatever/whatever/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /Users/shastry/whatever/node_modules/bower/lib/commands/index.js:45:20
    at _rejected (/Users/shastry/whatever/node_modules/bower/node_modules/q/q.js:844:24)
    at /Users/shastry/whatever/node_modules/bower/node_modules/q/q.js:870:30
    at Promise.when (/Users/whatever/whatever/node_modules/bower/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/Users/shastry/whatever/node_modules/bower/node_modules/q/q.js:788:41)
    at /Users/shastry/whatever/node_modules/bower/node_modules/q/q.js:604:44
System info:
Bower version: 1.4.1
Node version: 0.10.38
OS: Darwin 14.5.0 x64

**Comment by SSS2557** [comment]
I tried different versions and its still the same. Unsure if its something from npm or bower.

Our builds are failing too and it seems like either a permission issue or some sort of an unnecessary validation introduced

**Comment by jrgm** [comment]
See also https://github.com/isaacs/node-lru-cache/issues/60

**Comment by jeoffreybakker** [comment]
As jrgm already mentioned it is related to a new version of lru-cache. 

But I think there is a error on line 122 of GitRemoteResolver.js 
```javascript
        if (shallowCloningSupported && !GitRemoteResolver._noShallow.get(this._host)) {
```
Should be changed to
```
        if (shallowCloningSupported && !GitRemoteResolver._noShallow.get(that._host)) {
```

this._host will always result in an undefined there.

**Comment by vladikoff** [comment]
Update to Bower 1.6.x or 1.5.4 or 1.4.2 to fix this issue.

**Comment by vladikoff** [comment]
@jeoffreybakker created https://github.com/bower/bower/pull/2040
