### ISSUE TITLE
AppVeyor/ Windows failing tests.

### ISSUE THREAD

**Issue by paulohp** [bower/bower#2050]
I've been working on those tests errors on Windows for awhile now and I want to ask help from someone.
The issue seems to be on the clean up of tmpDir. On OS X and Linux system it works fine, but on Windows seems to be leaved a old tmp file.

Error message:
```
1) GitHub .resolve should retry using the GitRemoteResolver mechanism if extraction failed:
Uncaught Error: Failed to execute "git clone file://C:\Users\progr\Workspace\bower\test\assets\package-a -b 0.1.0 --progress . --depth 1", exit code of #128
fatal: destination path '.' already exists and is not an empty directory.
 at createError (C:\Users\progr\Workspace\bower\lib\util\createError.js:4:15)
  at ChildProcess.<anonymous> (C:\Users\progr\Workspace\bower\lib\util\cmd.js:102:21)
  at maybeClose (internal/child_process.js:818:16)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
From previous event:
at executeCmd (C:\Users\progr\Workspace\bower\lib\util\cmd.js:61:22)
at PThrottler._processEntry (C:\Users\progr\Workspace\bower\node_modules\p-throttler\index.js:89:25)
at Promise.apply (C:\Users\progr\Workspace\bower\node_modules\p-throttler\node_modules\q\q.js:1122:26)
at Promise.promise.promiseDispatch (C:\Users\progr\Workspace\bower\node_modules\p-throttler\node_modules\q\q.js:752:41)
at C:\Users\progr\Workspace\bower\node_modules\p-throttler\node_modules\q\q.js:1337:14
at flush (C:\Users\progr\Workspace\bower\node_modules\p-throttler\node_modules\q\q.js:108:17)

2) util download handle server response 404:
Uncaught Error: expected [ 'package.tar.gz.4255e51e053e68daf5bbbac723db3f9c' ] to be empty
at Assertion.assert (C:\Users\progr\Workspace\bower\node_modules\expect.js\index.js:96:13)
at Assertion.empty (C:\Users\progr\Workspace\bower\node_modules\expect.js\index.js:201:10)
at Function.empty (C:\Users\progr\Workspace\bower\node_modules\expect.js\index.js:499:17)
at Object.downloadTest.expectError (C:\Users\progr\Workspace\bower\test\util\download.js:79:60)
at C:\Users\progr\Workspace\bower\test\util\download.js:30:22
From previous event:
at downloadTest (C:\Users\progr\Workspace\bower\test\util\download.js:26:14)
at Context.<anonymous> (C:\Users\progr\Workspace\bower\test\util\download.js:74:16)
at callFn (C:\Users\progr\Workspace\bower\node_modules\mocha\lib\runnable.js:286:21)
at Test.Runnable.run (C:\Users\progr\Workspace\bower\node_modules\mocha\lib\runnable.js:279:7)
at Runner.runTest (C:\Users\progr\Workspace\bower\node_modules\mocha\lib\runner.js:421:10)
at C:\Users\progr\Workspace\bower\node_modules\mocha\lib\runner.js:528:12
at next (C:\Users\progr\Workspace\bower\node_modules\mocha\lib\runner.js:341:14)
at C:\Users\progr\Workspace\bower\node_modules\mocha\lib\runner.js:351:7

3) util download handle network error:
Error: EPERM: operation not permitted, lstat 'C:\Users\progr\AppData\Local\Temp\bower-tests\ed3c9496\6f65648a-f954-425e-8d3f-dd42a6a44b90\package.tar.gz.4255e51e053e68daf5bbbac723db3f9c'
at Error (native)
at Object.fs.lstatSync (fs.js:887:18)
at chmodrSync (C:\Users\progr\Workspace\bower\node_modules\chmodr\chmodr.js:50:18)
at C:\Users\progr\Workspace\bower\node_modules\chmodr\chmodr.js:61:5
at Array.forEach (native)
at chmodrDirSync (C:\Users\progr\Workspace\bower\node_modules\chmodr\chmodr.js:60:21)
at Function.chmodrSync [as sync] (C:\Users\progr\Workspace\bower\node_modules\chmodr\chmodr.js:54:12)
at checkAndRetry (C:\Users\progr\Workspace\bower\lib\util\rimraf.js:31:20)
at Function.module.exports.sync (C:\Users\progr\Workspace\bower\lib\util\rimraf.js:44:16)
at TempDir.exports.TempDir.TempDir.prepare (C:\Users\progr\Workspace\bower\test\helpers.js:93:16)

4) "after all" hook for "handle network error":
Error: EPERM: operation not permitted, lstat 'C:\Users\progr\AppData\Local\Temp\bower-tests\ed3c9496\6f65648a-f954-425e-8d3f-dd42a6a44b90\package.tar.gz.4255e51e053e68daf5bbbac723db3f9c'
at Error (native)
at Object.fs.lstatSync (fs.js:887:18)
at chmodrSync (C:\Users\progr\Workspace\bower\node_modules\chmodr\chmodr.js:50:18)
at C:\Users\progr\Workspace\bower\node_modules\chmodr\chmodr.js:61:5
at Array.forEach (native)
```

I know that @sheerun was fighting against it and pointed a possible fix here: https://github.com/npm/fs-write-stream-atomic/pull/7 and I think that's the way.

If anyone here have experience dealing with Node.js and Windows, let me know and let smash this one. :facepunch:

**Comment by kunyan** [comment]
I think all 4 issue cause by tmp dir/file not be removed.

```shell
C:\Users\progr\AppData\Local\Temp\bower-tests\ed3c9496\6f65648a-f954-425e-8d3f-dd42a6a44b90\package.tar.gz.4255e51e053e68daf5bbbac723db3f9c'
```

**Comment by paulohp** [comment]
Closing since @sheerun fixed it here:

https://github.com/bower/bower/commit/bb7c02b07ba413fe32ac699d16710f735af56020
