### ISSUE TITLE
Error with "bower init"

### ISSUE THREAD

**Issue by fabest** [bower/bower#2153]
For last stage of initialization i've catching error. A can't solve it even when updating npm, node and bower to latest version. Help me please =(
Trying "bower init" after "npm init"
```
bower error         Unable to perform highlight. The code contained syntax errors: Line 4: Unexpected token ILLEGAL

Stack trace:
Error: Unable to perform highlight. The code contained syntax errors: Line 4: Unexpected token ILLEGAL
    at throwError (C:\Users\Beard\AppData\Roaming\npm\node_modules\bower\node_modules\cardinal\node_modules\redeyed\node_modules\esprima\esprima.js:1161:21)
    at scanStringLiteral (C:\Users\Beard\AppData\Roaming\npm\node_modules\bower\node_modules\cardinal\node_modules\redeyed\node_modules\esprima\esprima.js:944:13)
    at Object.advance (C:\Users\Beard\AppData\Roaming\npm\node_modules\bower\node_modules\cardinal\node_modules\redeyed\node_modules\esprima\esprima.js:1077:20)
    at collectToken (C:\Users\Beard\AppData\Roaming\npm\node_modules\bower\node_modules\cardinal\node_modules\redeyed\node_modules\esprima\esprima.js:3293:23)
    at lookahead (C:\Users\Beard\AppData\Roaming\npm\node_modules\bower\node_modules\cardinal\node_modules\redeyed\node_modules\esprima\esprima.js:1118:18)
    at parseAssignmentExpression (C:\Users\Beard\AppData\Roaming\npm\node_modules\bower\node_modules\cardinal\node_modules\redeyed\node_modules\esprima\esprima.js:1992:17)
    at C:\Users\Beard\AppData\Roaming\npm\node_modules\bower\node_modules\cardinal\node_modules\redeyed\node_modules\esprima\esprima.js:3609:38
    at parseObjectProperty (C:\Users\Beard\AppData\Roaming\npm\node_modules\bower\node_modules\cardinal\node_modules\redeyed\node_modules\esprima\esprima.js:1425:28)
    at C:\Users\Beard\AppData\Roaming\npm\node_modules\bower\node_modules\cardinal\node_modules\redeyed\node_modules\esprima\esprima.js:3609:38
    at parseObjectInitialiser (C:\Users\Beard\AppData\Roaming\npm\node_modules\bower\node_modules\cardinal\node_modules\redeyed\node_modules\esprima\esprima.js:1449:24)

Console trace:
Error
    at StandardRenderer.error (C:\Users\Beard\AppData\Roaming\npm\node_modules\bower\lib\renderers\StandardRenderer.js:83:37)
    at Logger.<anonymous> (C:\Users\Beard\AppData\Roaming\npm\node_modules\bower\bin\bower:116:30)
    at emitOne (events.js:90:13)
    at Logger.emit (events.js:182:7)
    at Logger.emit (C:\Users\Beard\AppData\Roaming\npm\node_modules\bower\node_modules\bower-logger\lib\Logger.js:29:39)
    at C:\Users\Beard\AppData\Roaming\npm\node_modules\bower\lib\commands\index.js:48:20
    at _rejected (C:\Users\Beard\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:844:24)
    at C:\Users\Beard\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:870:30
    at Promise.when (C:\Users\Beard\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:1122:31)
    at Promise.promise.promiseDispatch (C:\Users\Beard\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:788:41)
System info:
Bower version: 1.7.2
Node version: 5.5.0
OS: Windows_NT 10.0.10586 x64
```

**Comment by sheerun** [comment]
Please paste your bower.json and package.json

**Comment by fabest** [comment]
package.json
```
{
  "name": "fabest.github.io",
  "version": "1.0.0",
  "description": "��#\u0000 \u0000f\u0000a\u0000b\u0000e\u0000s\u0000t\u0000.\u0000g\u0000i\u0000t\u0000h\u0000u\u0000b\u0000.\u0000i\u0000o\u0000\r\u0000 \u0000",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/fabest/fabest.github.io.git"
  },
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/fabest/fabest.github.io/issues"
  },
  "homepage": "https://github.com/fabest/fabest.github.io#readme"
}
```
With this error bower.jason isn't creating

**Comment by sheerun** [comment]
your description contains zero bytes. remove them and you should be allright

**Comment by fabest** [comment]
Thank you sheerun! It's helped

**Comment by BenMann** [comment]
Alright, closing. :tada:
