### ISSUE TITLE
bower install --no-color[error]

### ISSUE THREAD

**Issue by westsince2001** [bower/bower#2182]
hi, i'm a new user to use yeoman build my app, i can not run my app on mac os(it can run on my win7).any one can help me? 

## My OS configure：
MacBookProForWest:yo dingjianfeng$  ```yo --version&&grunt --version && bower --version```
1.6.0
grunt-cli v0.1.13
grunt v0.4.5
1.7.7 
MacBookProForWest:yo dingjianfeng$ pwd
Users/dingjianfeng/Documents/workspace/wt-workbench/yo
MacBookProForWest:yo dingjianfeng$ ls
```Gruntfile.js		bower.json		package.json
README.md		bower_components	test
app			node_modules```
MacBookProForWest:yo dingjianfeng$ ```mvn clean install -DskipTests=true -X```
##  After the mvn cmd executed:
```
...more ....
dist.git#2.2.0
bower jquery#1.9.1 - 2                  validate 2.2.0 against git://github.com/jquery/jquery-dist.git#1.9.1 - 2
bower                                  ECONFLICT Unable to find suitable version for angular
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 48.652 s
[INFO] Finished at: 2016-02-19T13:08:32+08:00
[INFO] Final Memory: 14M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.trecloux:yeoman-maven-plugin:0.5:build (default) on project wt-workbench: Error during : bower install --no-color: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.trecloux:yeoman-maven-plugin:0.5:build (default) on project wt-workbench: Error during : bower install --no-color
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error during : bower install --no-color
	at com.github.trecloux.yeoman.YeomanMojo.executeCommand(YeomanMojo.java:129)
	at com.github.trecloux.yeoman.YeomanMojo.logAndExecuteCommand(YeomanMojo.java:110)
	at com.github.trecloux.yeoman.YeomanMojo.bowerInstall(YeomanMojo.java:91)
	at com.github.trecloux.yeoman.YeomanMojo.execute(YeomanMojo.java:69)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:377)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:160)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:147)
	at com.github.trecloux.yeoman.YeomanMojo.executeCommand(YeomanMojo.java:127)
	... 25 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by sheerun** [comment]
"Unable to find suitable version for angular".

Maybe try to force angular version by putting `"resolutions": { "angular": "x.x.x" }}` in bower.json.

**Comment by westsince2001** [comment]
@sheerun  Tks~~~

**Comment by BenMann** [comment]
I take it that it solved your problem?
I'll assume yes and close for now. Just yell at me here if I'm wrong :cake:
