### ISSUE TITLE
bower EPERM

### ISSUE THREAD

**Issue by DmitrySokol** [bower/bower#2190]
`bower install jquery`  - bug  bower EPERM ........ Prompt, please, how to overcome ???

```
boss@boss-MS-7971:/media/data/repo[master]$ bower install jquery
bower cached        git://github.com/jquery/jquery-dist.git#2.2.1
bower validate      2.2.1 against git://github.com/jquery/jquery-dist.git#*
bower install       jquery#2.2.1
bower EPERM         EPERM: operation not permitted, chmod '/media/data/repo/bower_components/jquery/.bower.json'

Stack trace:
/home/boss/.nvm/versions/node/v5.7.0/lib/node_modules/bower/lib/node_modules/fstream/lib/writer.js:306:21

FSReqWrap.oncomplete (fs.js:82:15)

Console trace:
Error
    at StandardRenderer.error (/home/boss/.nvm/versions/node/v5.7.0/lib/node_modules/bower/lib/renderers/StandardRenderer.js:83:37)
    at Logger.<anonymous> (/home/boss/.nvm/versions/node/v5.7.0/lib/node_modules/bower/lib/bin/bower.js:110:26)
    at emitOne (events.js:90:13)
    at Logger.emit (events.js:182:7)
    at Logger.emit (/home/boss/.nvm/versions/node/v5.7.0/lib/node_modules/bower/lib/node_modules/bower-logger/lib/Logger.js:29:39)
    at /home/boss/.nvm/versions/node/v5.7.0/lib/node_modules/bower/lib/commands/index.js:48:20
    at _rejected (/home/boss/.nvm/versions/node/v5.7.0/lib/node_modules/bower/lib/node_modules/q/q.js:844:24)
    at /home/boss/.nvm/versions/node/v5.7.0/lib/node_modules/bower/lib/node_modules/q/q.js:870:30
    at Promise.when (/home/boss/.nvm/versions/node/v5.7.0/lib/node_modules/bower/lib/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/home/boss/.nvm/versions/node/v5.7.0/lib/node_modules/bower/lib/node_modules/q/q.js:788:41)

System info:

Bower version: 1.7.7
Node version: 5.7.0
OS: Ubuntu 14.04
```

**Comment by faceleg** [comment]
From the stack trace it appears that bower `/media/data/repo/bower_components/jquery/.bower.json` has incorrect permissions.

For future reference, these questions are better asked on stackoverflow.com
