### ISSUE TITLE
Bower update return me invalid-meta The "name" is recommended to be lowercase, can contain digits, dots, dashes

### ISSUE THREAD

**Issue by ssuhat** [bower/bower#2242]
I've tried to remove my installed last package that make my bower like that. But still no luck. 

Looks like when I'm install my last package it I mistakenly paste an tab character:

`bower install     <space  #tab>          angular-input-stars-directive`

Now every time I bower update it always return me this error even on my other project:

`bower invalid-meta The "name" is recommended to be lowercase, can contain digits, dots, dashes`

I've tried `bower cache clean` and reinstall the bower but still no luck.

Is there anyway can fix this?

Thanks

**Comment by sheerun** [comment]
maybe remove bower_components?

**Comment by ssuhat** [comment]
@sheerun So i need to remove bower_components on every project I have?.

**Comment by sheerun** [comment]
did it help?

**Comment by Siafu** [comment]
Having the same issue, no removing the bower_components folder did not help.

**Comment by ssuhat** [comment]
@sheerun  no its not working

**Comment by bruno-farias** [comment]
+1

**Comment by ssuhat** [comment]
renaming bower.json name without space solve the problem. 
  {
        "name": "without-space",
        // your dependencies
   }

**Comment by adrienrn** [comment]
Leaving some feedbacks for others encountering this bug.

Updating from `1.7.2 -> 1.7.9` and having my package named `madhouse/messenger` hosted in a private (bitbucket).

```
{
  "name": "madhouse/messenger",
  ...
}
```

I was unable to run `bower install` anymore. Bower was just printing this warning and just exits right after that:

```
vagrant@ubuntu:/vagrant/sites/osclass/oc-content/plugins/madhouse_messenger$ bower install
bower                     invalid-meta The "name" is recommended to be lowercase, can contain digits, dots, dashes
```

As suggested above, **clearing the `bower_components/` folder fixed it.** :)

**Comment by Gaurav-jsm** [comment]
This is just warning from bower. open your bower.json file and rename the "name" tag to get rid of this. It is recommended to have lowercase and digit. Special characters allowed are dot and dash.

**Comment by sumit1606** [comment]
Its just a warning,it can be easily avoided by changing the name of the file according to the bower instructions. eg make it lower case

**Comment by migueloop** [comment]
Clearing bower_components folder didn´t help me either...

**Comment by slavikgreen** [comment]
i have {"name": "gfgAdminPanel"} , where is the dots???? Cleaning bower_components folder doesn't help((

**Comment by dardub** [comment]
If this is just a warning, why does it abort install? This is breaking a legacy application.

**Comment by dardub** [comment]
@slavikgreen It can't have and capitalization anymore...

**Comment by JammerCoder** [comment]
I have received the same error " bower invalid-meta The "name".... 
- I have changed the name into lowercase then run the command again
> bower install

- just give that blank response, is that normal? I know it's not

**Comment by PavanRaj999** [comment]
<b> TRY THIS </b>
bower install --verbose --force

**Comment by RuiBaiaoFrost** [comment]
Removing the bower_components folder did it for me. Thanks

**Comment by AeonFr** [comment]
I have this issue while running `bower init` and `bower install X`.

I don't have a bower components folder nor a bower.json file in my project.

Using version 1.8.8 (I literally just installed it for the first time)

**Comment by AeonFr** [comment]
And in case it's any use, this is the output of `bower install --verbose --force`:

```
fcano@EKS-815 C:\xampp\htdocs\ae++
$ bower install croppie --verbose --force
bower EINVALID      Name must be lowercase, can contain digits, dots, dashes, "@" or spaces

Stack trace:
Error: Name must be lowercase, can contain digits, dots, dashes, "@" or spaces
    at createError (C:\Users\fcano\AppData\Roaming\npm\node_modules\bower\lib\node_modules\bower-json\lib\util\createError.js:2:15)
    at validate (C:\Users\fcano\AppData\Roaming\npm\node_modules\bower\lib\node_modules\bower-json\lib\json.js:215:15)
    at Function.parse (C:\Users\fcano\AppData\Roaming\npm\node_modules\bower\lib\node_modules\bower-json\lib\json.js:115:9)
    at C:\Users\fcano\AppData\Roaming\npm\node_modules\bower\lib\util\readJson.js:38:35
From previous event:
    at Project._readJson (C:\Users\fcano\AppData\Roaming\npm\node_modules\bower\lib\core\Project.js:719:10)
    at Project._analyse (C:\Users\fcano\AppData\Roaming\npm\node_modules\bower\lib\core\Project.js:577:14)
    at Project.install (C:\Users\fcano\AppData\Roaming\npm\node_modules\bower\lib\core\Project.js:44:17)
    at install (C:\Users\fcano\AppData\Roaming\npm\node_modules\bower\lib\commands\install.js:29:20)
    at C:\Users\fcano\AppData\Roaming\npm\node_modules\bower\lib\commands\index.js:33:28
From previous event:
    at withLogger (C:\Users\fcano\AppData\Roaming\npm\node_modules\bower\lib\commands\index.js:40:14)
    at Function.runFromArgv [as line] (C:\Users\fcano\AppData\Roaming\npm\node_modules\bower\lib\commands\index.js:30:16)
    at Object.<anonymous> (C:\Users\fcano\AppData\Roaming\npm\node_modules\bower\lib\bin\bower.js:83:26)
    at Module._compile (internal/modules/cjs/loader.js:723:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)

Console trace:
Error
    at StandardRenderer.error (C:\Users\fcano\AppData\Roaming\npm\node_modules\bower\lib\renderers\StandardRenderer.js:88:37)
    at Logger.<anonymous> (C:\Users\fcano\AppData\Roaming\npm\node_modules\bower\lib\bin\bower.js:113:30)
    at Logger.emit (events.js:189:13)
    at Logger.emit (C:\Users\fcano\AppData\Roaming\npm\node_modules\bower\lib\node_modules\bower-logger\lib\Logger.js:29:39)
    at C:\Users\fcano\AppData\Roaming\npm\node_modules\bower\lib\commands\index.js:49:24
    at _rejected (C:\Users\fcano\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:864:24)
    at C:\Users\fcano\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:890:30
    at Promise.when (C:\Users\fcano\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:1142:31)
    at Promise.promise.promiseDispatch (C:\Users\fcano\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:808:41)
    at C:\Users\fcano\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:624:44
System info:
Bower version: 1.8.8
Node version: 11.4.0
OS: Windows_NT 10.0.17134 x64
```

**Comment by AeonFr** [comment]
**Update**: Using the command in a different folder worked fine. My current repo had a `Bower_components` folder (notice the first uppercase) and I removed it before running `bower init`.

Even though, the error persisted. I don't know if this might be related to Windows saving the old folder in some kind of "cache" or something.

**Comment by webgoon** [comment]
I put put a  "cwd": "~/.path",  This was giving me an issue removed that line and it worked like a charm again.
