### ISSUE TITLE
bower: unable to get local issuer certificate

### ISSUE THREAD

**Issue by chfw** [bower/bower#2246]
Hi all,

I am having a intermittent problem with bower. When I run 'bower install' as jenkins user, I run into this problem. **But when I run as my own user account, all is fine**. I need it to work under jenkins not mine. Could you please help me find where the silly problem is?

bower angular-chart.js#~0.8.6UNABLE_TO_GET_ISSUER_CERT_LOCALLY Request to https://bower.herokuapp.com/packages/angular-chart.js failed: unable to get local issuer certificate

`Stack trace:
Error: Request to https://bower.herokuapp.com/packages/angular-chart.js failed: unable to get local issuer certificate
    at createError (/usr/lib/node_modules/bower/lib/node_modules/bower-registry-client/lib/util/createError.js:2:15)
    at Request._callback (/usr/lib/node_modules/bower/lib/node_modules/bower-registry-client/lib/lookup.js:97:29)
    at self.callback (/usr/lib/node_modules/bower/lib/node_modules/request/request.js:198:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.request.emit (/usr/lib/node_modules/bower/lib/node_modules/request-replay/index.js:69:33)
    at Request.onRequestError (/usr/lib/node_modules/bower/lib/node_modules/request/request.js:820:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at TLSSocket.socketErrorListener (_http_client.js:256:9)
From previous event:
    at PackageRepository.fetch (/usr/lib/node_modules/bower/lib/core/PackageRepository.js:46:6)
    at Manager._fetch (/usr/lib/node_modules/bower/lib/core/Manager.js:323:51)
    at Array.forEach (native)
    at Manager.resolve (/usr/lib/node_modules/bower/lib/core/Manager.js:116:23)
    at Project._bootstrap (/usr/lib/node_modules/bower/lib/core/Project.js:544:6)
    at /usr/lib/node_modules/bower/lib/core/Project.js:75:21

Console trace:
Error
    at StandardRenderer.error (/usr/lib/node_modules/bower/lib/renderers/StandardRenderer.js:81:37)
    at Logger.<anonymous> (/usr/lib/node_modules/bower/lib/bin/bower.js:110:26)
    at emitOne (events.js:77:13)
    at Logger.emit (events.js:169:7)
    at Logger.emit (/usr/lib/node_modules/bower/lib/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/lib/node_modules/bower/lib/commands/index.js:48:20
    at _rejected (/usr/lib/node_modules/bower/lib/node_modules/q/q.js:844:24)
    at /usr/lib/node_modules/bower/lib/node_modules/q/q.js:870:30
    at Promise.when (/usr/lib/node_modules/bower/lib/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/bower/lib/node_modules/q/q.js:788:41)
System info:
Bower version: 1.7.9
Node version: 4.4.2
OS: Linux 3.10.0-229.el7.x86_64 x64
Build step 'Execute shell' marked build as failure`

Br,

jaska

**Comment by chfw** [comment]
The problem is gone in the second day. Strange!
