### ISSUE TITLE
`bower cache` throws uncaught RangeError if no argument is supplied

### ISSUE THREAD

**Issue by romellem** [bower/bower#2264]
Running `bower cache` throws an uncaught error on my machine (Mac OS X 10.10.5). I am running the latest version, `1.7.9`, and node is running `v5.10.1`. 

```
$ bower --version
1.7.9

$ node --version
v5.10.1

$ bower cache --verbose
/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:155
                throw e;
                ^

RangeError: Invalid array length
    at Object.assignToHash (/usr/local/lib/node_modules/bower/lib/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:759:22)
    at Object.compile (/usr/local/lib/node_modules/bower/lib/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:113:27)
    at Object.compileChildren (/usr/local/lib/node_modules/bower/lib/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:794:49)
    at Object.compile (/usr/local/lib/node_modules/bower/lib/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:97:10)
    at Object.compileChildren (/usr/local/lib/node_modules/bower/lib/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:794:49)
    at Object.compile (/usr/local/lib/node_modules/bower/lib/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:97:10)
    at compileInput (/usr/local/lib/node_modules/bower/lib/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:516:53)
    at Object.ret [as std/help-cache.std] (/usr/local/lib/node_modules/bower/lib/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:523:18)
    at render (/usr/local/lib/node_modules/bower/lib/util/template.js:20:27)
    at Object.render (/usr/local/lib/node_modules/bower/lib/util/template.js:30:12)
From previous event:
    at withLogger (/usr/local/lib/node_modules/bower/lib/commands/index.js:41:10)
    at Object.runApi [as help] (/usr/local/lib/node_modules/bower/lib/commands/index.js:17:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/bower/lib/bin/bower.js:79:29)
```

This was done in a directory where I ran `bower init` but had not installed any dependencies yet. Other bower commands are working normally (`init`, `install`, `cleanup`, etc.).

**Comment by ptitgraig** [comment]
`bower cache` is expecting an argument:
http://bower.io/docs/api/#cache
I believe the behavior is normal. Maybe we should set a proper error message indeed.

**Comment by BenMann** [comment]
Would be nice to have a better error message here indeed.

**Comment by rajzshkr** [comment]
@BenMann we had this info message earlier. But after handlebar upgrade this is not working as expected. There is a small typo error in template. I gave a PR and it is working as expected.

```
> bower cache

Usage:

    bower cache <command> [<args>] [<options>]
Commands:

    clean                   Clean cached packages
    list                    List cached packages  
```

**Comment by BenMann** [comment]
Closed via https://github.com/bower/bower/pull/2270.

**Comment by tarranjones** [comment]
@BenMann i am still getting this error. 

I am using 
Bower v1.7.9
Npm v3.10.3
Node v6.3.1
