### ISSUE TITLE
TypeError: Path must be a string. Received ['/tmp/user/bower/angular-clipboard']

### ISSUE THREAD

**Issue by altanom** [bower/bower#2332]
Hey guys

I was updated version of node@4.4.7 and bower@1.7.9. Then i have a problem when bower install.

What's happening i need little explain here.

 - Bower version not updated after <code>npm install bower@1.7.9</code> then still 1.2.7
 - Why this error appear?

Here is error. I do not find error like this. <code>angular-clipboard</code> is just an example and other libs are same.

<code>
Stack trace:
</code>
<code>
TypeError: Path must be a string. Received [ '/tmp/user/bower/angular-clipboard-12451-bjTP6F',
  [Function: _cleanupCallback] ]
    at assertPath (path.js:8:11)
    at Object.posix.join (path.js:479:5)
    at GitHubResolver.GitResolver._cleanup (/home/tsend/npm-global/lib/node_modules/bower/lib/core/resolvers/GitResolver.js:185:26)
    at /home/tsend/npm-global/lib/node_modules/bower/lib/core/resolvers/GitResolver.js:74:25
    at Promise.apply (/home/tsend/npm-global/lib/node_modules/bower/node_modules/q/q.js:1122:26)
    at Promise.promise.promiseDispatch (/home/tsend/npm-global/lib/node_modules/bower/node_modules/q/q.js:752:41)
    at /home/tsend/npm-global/lib/node_modules/bower/node_modules/q/q.js:1337:14
    at flush (/home/tsend/npm-global/lib/node_modules/bower/node_modules/q/q.js:108:17)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
</code>
<code>
Console trace:
</code>
<code>
Trace
    at StandardRenderer.error (/home/tsend/npm-global/lib/node_modules/bower/lib/renderers/StandardRenderer.js:74:17)
    at Logger.<anonymous> (/home/tsend/npm-global/lib/node_modules/bower/bin/bower:109:18)
    at emitOne (events.js:77:13)
    at Logger.emit (events.js:169:7)
    at Logger.emit (/home/tsend/npm-global/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /home/tsend/npm-global/lib/node_modules/bower/lib/commands/install.js:27:16
    at _rejected (/home/tsend/npm-global/lib/node_modules/bower/node_modules/q/q.js:808:24)
    at /home/tsend/npm-global/lib/node_modules/bower/node_modules/q/q.js:834:30
    at Promise.when (/home/tsend/npm-global/lib/node_modules/bower/node_modules/q/q.js:1079:31)
    at Promise.promise.promiseDispatch (/home/tsend/npm-global/lib/node_modules/bower/node_modules/q/q.js:752:41)
</code>
<code>
System info:
</code>
<code>
Bower version: 1.2.7
</code>
<code>
Node version: 4.4.7
</code>
<code>
OS: Linux 3.16.0-77-generic x64
</code>

**Comment by kunyan** [comment]
@altanom 
You should install bower global 
```shell
sudo npm install -g bower
```

please updated bower and try again, the error might be disappear

**Comment by altanom** [comment]
@kunyan i have installed bower global. Do you have any idea? 
<code>
sudo npm install -g bower
</code>
<code>
/usr/local/bin/bower -> /usr/local/lib/node_modules/bower/bin/bower
</code>
<code>
/usr/local/lib
</code>
<code>
└── bower@1.7.9 
</code>
<code>

</code>
<code>
bower --version
1.2.7
</code>

**Comment by kunyan** [comment]
```shell
which bower
```


or 

/usr/local/bin/bower --version

**Comment by altanom** [comment]
/usr/local/bin/bower --version
1.7.9
bower --version
1.2.7

What is difference between bower or /usr/local/bin/bower?

**Comment by kunyan** [comment]
well, it is env PATH problem.

please check your path in .bashrc or .bash_profile.


anyway, it is not a bower issue. could you please try to reproduce the second issue with latest bower?

**Comment by altanom** [comment]
Okay i will try. Thanks a lot @kunyan
