### ISSUE TITLE
Error in when trying to install foundation using command line.

### ISSUE THREAD

**Issue by sushilkumaraitian** [bower/bower#2334]
Getting Following error when trying to install foundation framework on my computer.

C:\Users\sushil\AppData\Roaming\npm\node_modules\bower\lib\node_modules\configst
ore\index.js:70
                                throw err;
                                ^

Error: EPERM: operation not permitted, rename 'C:\Users\sushil.config\configsto
re\bower-github.json.1828266031' -> 'C:\Users\sushil.config\configstore\bower-g
ithub.json'
    at Error (native)
    at Object.fs.renameSync (fs.js:681:18)
    at Function.writeFileSync [as sync](C:UserssushilAppDataRoamingnpmnod
e_modulesbowerlibnode_moduleswrite-file-atomicindex.js:39:8)
    at Object.create.all.set (C:\Users\sushil\AppData\Roaming\npm\node_modules\b
ower\lib\node_modules\configstore\index.js:63:21)
    at Object.Configstore (C:\Users\sushil\AppData\Roaming\npm\node_modules\bowe
r\lib\node_modules\configstore\index.js:28:11)
    at readCachedConfig (C:\Users\sushil\AppData\Roaming\npm\node_modules\bower\
lib\config.js:19:23)
    at defaultConfig (C:\Users\sushil\AppData\Roaming\npm\node_modules\bower\lib
\config.js:11:12)
    at Object.<anonymous> (C:\Users\sushil\AppData\Roaming\npm\node_modules\bowe
r\lib\index.js:16:32)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by sheerun** [comment]
This should be fixed in newest bower as we upgraded write-file-atomic that used to mess up permissions. To solve this issue, you need to properly chown configstore directories.

https://github.com/npm/write-file-atomic/pull/13
