### ISSUE TITLE
bower link error str.trim is not a function

### ISSUE THREAD

**Issue by dvlmemnoch** [bower/bower#2350]
When using the command
`bower link <name>`

I received this error:
```
bower                            error str.trim is not a function

Stack trace:
TypeError: str.trim is not a function
    at trim (C:\Users\b888jxs\AppData\Roaming\npm\node_modules\bower\lib\node_modules\bower-endpoint-parser\index.js:115:22)
    at Object.json2decomposed (C:\Users\b888jxs\AppData\Roaming\npm\node_modules\bower\lib\node_modules\bower-endpoint-parser\index.js:48:13)
    at Project.<anonymous> (C:\Users\b888jxs\AppData\Roaming\npm\node_modules\bower\lib\core\Project.js:794:35)
    at C:\Users\b888jxs\AppData\Roaming\npm\node_modules\bower\lib\node_modules\mout\object\forOwn.js:12:27
    at exec (C:\Users\b888jxs\AppData\Roaming\npm\node_modules\bower\lib\node_modules\mout\object\forIn.js:71:19)
    at forIn (C:\Users\b888jxs\AppData\Roaming\npm\node_modules\bower\lib\node_modules\mout\object\forIn.js:38:17)
    at Object.forOwn (C:\Users\b888jxs\AppData\Roaming\npm\node_modules\bower\lib\node_modules\mout\object\forOwn.js:10:9)
    at Project._restoreNode (C:\Users\b888jxs\AppData\Roaming\npm\node_modules\bower\lib\core\Project.js:792:17)
    at Project.<anonymous> (C:\Users\b888jxs\AppData\Roaming\npm\node_modules\bower\lib\core\Project.js:504:14)
    at C:\Users\b888jxs\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:1229:26

Console trace:
Error
    at StandardRenderer.error (C:\Users\b888jxs\AppData\Roaming\npm\node_modules\bower\lib\renderers\StandardRenderer.js:81:37)
    at Logger.<anonymous> (C:\Users\b888jxs\AppData\Roaming\npm\node_modules\bower\lib\bin\bower.js:110:26)
    at emitOne (events.js:77:13)
    at Logger.emit (events.js:169:7)
    at Logger.emit (C:\Users\b888jxs\AppData\Roaming\npm\node_modules\bower\lib\node_modules\bower-logger\lib\Logger.js:29:39)
    at C:\Users\b888jxs\AppData\Roaming\npm\node_modules\bower\lib\commands\index.js:48:20
    at _rejected (C:\Users\b888jxs\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:844:24)
    at C:\Users\b888jxs\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:870:30
    at Promise.when (C:\Users\b888jxs\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:1122:31)
    at Promise.promise.promiseDispatch (C:\Users\b888jxs\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:788:41)
System info:
Bower version: 1.7.9
Node version: 4.4.5
OS: Windows_NT 6.1.7601 x64
```

It looks like it was failing due to an Integer being passed and trying to do a .trim() on it was causing it to fail. I converted `str` to a string object and the link command worked.

**Comment by kunyan** [comment]
@dvlmemnoch it seems some version of dependencies is Integer when you try to link it.

as you know, all version in bower.json or package.json should be String, not Integer

**Comment by BenMann** [comment]
So if an int was passed as package name that's expected huh?
We coooould account for the case, but it seems very obvious as it is JSON. Closing for now, 'lemme know if there's more.
