### ISSUE TITLE
bower cache clear fails: Invalid array length

### ISSUE THREAD

**Issue by sorgloomer** [bower/bower#2377]
Using Windows 10 1511

**Output of `bower -v && npm -v && node -v`:**

```
C:\_temp\bowwer>bower --version && node --version && npm --version
1.7.9
v6.7.0
3.10.3
```

**Steps to reproduce the issue:**
1. Use windows, nodejs, bower
2. Install something in a random folder `bower install angular`
3. Run `bower cache clear`

```
C:\_temp\bowwer>bower install angular
bower angular#*                 cached https://github.com/angular/bower-angular.git#1.5.8
bower angular#*               validate 1.5.8 against https://github.com/angular/bower-angular.git#*

C:\_temp\bowwer>bower cache clear
C:\Users\tamas.hegedus\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:155
                throw e;
                ^

RangeError: Invalid array length
    at Object.assignToHash (C:\Users\tamas.hegedus\AppData\Roaming\npm\node_modules\bower\lib\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:759:22)
    at Object.compile (C:\Users\tamas.hegedus\AppData\Roaming\npm\node_modules\bower\lib\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:113:27)
    at Object.compileChildren (C:\Users\tamas.hegedus\AppData\Roaming\npm\node_modules\bower\lib\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:794:49)
    at Object.compile (C:\Users\tamas.hegedus\AppData\Roaming\npm\node_modules\bower\lib\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:97:10)
    at Object.compileChildren (C:\Users\tamas.hegedus\AppData\Roaming\npm\node_modules\bower\lib\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:794:49)
    at Object.compile (C:\Users\tamas.hegedus\AppData\Roaming\npm\node_modules\bower\lib\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:97:10)
    at compileInput (C:\Users\tamas.hegedus\AppData\Roaming\npm\node_modules\bower\lib\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:516:53)
    at Object.ret [as std/help-cache.std] (C:\Users\tamas.hegedus\AppData\Roaming\npm\node_modules\bower\lib\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:523:18)
    at render (C:\Users\tamas.hegedus\AppData\Roaming\npm\node_modules\bower\lib\util\template.js:20:27)
    at Object.render (C:\Users\tamas.hegedus\AppData\Roaming\npm\node_modules\bower\lib\util\template.js:30:12)
```

**Comment by sorgloomer** [comment]
Sry turned out to be a duplicate of https://github.com/bower/bower/issues/2290

**Comment by sorgloomer** [comment]
Or maybe not, the help states that cache IS a valid command

**Comment by sheerun** [comment]
It is indeed a duplicate as valid command is `clean`, not `clear`
