### ISSUE TITLE
Inconsistant behavior of CLI vs programmatic API (aka broken programmatic API)

### ISSUE THREAD

**Issue by fpauser** [bower/bower#2387]
Example:

__CLI__
`bower install mrdoob/three.js#r82 --save`
* installs three.js to `<bower_components_dir>/three.js`
* creates an entry `"three.js": "mrdoob/three.js#r82"` in the `bower.json`

__Programmatic API__
`bower.commands.install('mrdoob/three.js', 'r82', {save: true})`

Results in:
```
Error: Tag/branch r82 does not exist
    at createError (<project_dir>/node_modules/bower/lib/util/createError.js:4:15)
    at <project_dir>/node_modules/bower/lib/core/resolvers/GitResolver.js:183:15
    at <project_dir>/node_modules/bower/lib/node_modules/q/q.js:1229:26
    at _fulfilled (<project_dir>/node_modules/bower/lib/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (<project_dir>/node_modules/bower/lib/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (<project_dir>/node_modules/bower/lib/node_modules/q/q.js:796:13)
    at <project_dir>/node_modules/bower/lib/node_modules/q/q.js:556:49
    at runSingle (<project_dir>/node_modules/bower/lib/node_modules/q/q.js:137:13)
    at flush (<project_dir>/node_modules/bower/lib/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Node version used: 6.9.1
Bower version: 1.8.0

**Comment by sheerun** [comment]
Can you write failing test for it?
