### ISSUE TITLE
A Issue install bower with command lines

### ISSUE THREAD

**Issue by brandonpowell** [bower/bower#2414]
I'm still a beginner in command lines so can you explain with details for me

I keep running into this problem. I uninstalled and reinstalled bower. Nothing is working. I have tried this method `sudo chown -R $USER:$GROUP ~/.npm` `sudo chown -R $USER:$GROUP ~/.config`

<blockquote>alexlaw$ bower
/usr/local/lib/node_modules/bower/lib/node_modules/configstore/index.js:54
throw err;^</blockquote> 

<blockquote>Error: EACCES: permission denied, open '/Users/alexlaw/.config/configstore/bower-github.json' You don't have access to this file.</blockquote> 

    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.get (/usr/local/lib/node_modules/bower/lib/node_modules/configstore/index.js:35:26)
        at Object.Configstore (/usr/local/lib/node_modules/bower/lib/node_modules/configstore/index.js:28:44)
        at readCachedConfig (/usr/local/lib/node_modules/bower/lib/config.js:19:23)
        at defaultConfig (/usr/local/lib/node_modules/bower/lib/config.js:11:12)
        at Object.<anonymous> (/usr/local/lib/node_modules/bower/lib/index.js:16:32)
        at Module._compile (module.js:556:32)
        at Object.Module._extensions..js (module.js:565:10)

**Comment by rajzshkr** [comment]
#2262 can you check this issue

**Comment by thinkxl** [comment]
Closing as this is not a Bower issue.
