### ISSUE TITLE
Wep App Generator jQuery not Installed

### ISSUE THREAD

**Issue by pcabrera83** [bower/bower#2415]
Hi, I'm a first time user of Yeoman and I'm receiving this error message. Can you guys help?

```
bower not-cached    https://github.com/jquery/jquery-dist.git#~2.1.1
bower resolve       https://github.com/jquery/jquery-dist.git#~2.1.1
bower ECMDERR       Failed to execute "git ls-remote --tags --heads https://github.com/jquery/jquery-dist.git", exit code of #1 xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

Additional error details:
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
bower not-cached    https://github.com/jquery/jquery-dist.git#~2.1.1
bower resolve       https://github.com/jquery/jquery-dist.git#~2.1.1
bower not-cached    https://github.com/mochajs/mocha.git#*
bower resolve       https://github.com/mochajs/mocha.git#*
bower not-cached    https://github.com/chaijs/chai.git#*
bower resolve       https://github.com/chaijs/chai.git#*
bower ECMDERR       Failed to execute "git ls-remote --tags --heads https://github.com/jquery/jquery-dist.git", exit code of #1 xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

Additional error details:
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Error: jquery is not installed. Try running `bower install` or remove the component from your bower.json file.
    at /usr/local/lib/node_modules/generator-webapp/node_modules/wiredep/wiredep.js:30:56
    at /usr/local/lib/node_modules/generator-webapp/node_modules/wiredep/lib/detect-dependencies.js:149:29
    at /usr/local/lib/node_modules/generator-webapp/node_modules/wiredep/node_modules/lodash/lodash.js:4944:15
    at baseForOwn (/usr/local/lib/node_modules/generator-webapp/node_modules/wiredep/node_modules/lodash/lodash.js:3001:24)
    at /usr/local/lib/node_modules/generator-webapp/node_modules/wiredep/node_modules/lodash/lodash.js:4913:18
    at Function.forEach (/usr/local/lib/node_modules/generator-webapp/node_modules/wiredep/node_modules/lodash/lodash.js:9359:14)
    at detectDependencies (/usr/local/lib/node_modules/generator-webapp/node_modules/wiredep/lib/detect-dependencies.js:34:7)
    at wiredep (/usr/local/lib/node_modules/generator-webapp/node_modules/wiredep/wiredep.js:70:39)
    at constructor.end (/usr/local/lib/node_modules/generator-webapp/app/index.js:316:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-webapp/node_modules/yeoman-generator/lib/base.js:439:23)

```

**Comment by thinkxl** [comment]
Hey @pcabrera83, we need more info to determine if this is a bower issue, please take a look at [Report a Bug](https://github.com/bower/bower/wiki/Report-a-Bug), and follow the steps listed in there.

**Comment by thinkxl** [comment]
It doesn't seem to be bower related, closing the issue for now.
