### ISSUE TITLE
Bower does not register public projects hosted on GitLab.com

### ISSUE THREAD

**Issue by danidemi** [bower/bower#2416]
**Output of `bower -v && npm -v && node -v`:**

```
1.7.9
3.5.2
v4.2.6
```

**Additional environment details (proxy, private registry, etc.):**

Direct Internet connection, no proxy.

**Steps to reproduce the issue:**

1. I created a public project called "jscamera" on GitLab.com, here's the URL: <https://gitlab.com/tech-gap-italia-open-source/jscamera>
2. The repository URL is: <git@gitlab.com:tech-gap-italia-open-source/jscamera.git>
3. `git clone git@gitlab.com:tech-gap-italia-open-source/jscamera.git`
4. `cd jscamera`
3. I tried to register the project in bower with the following command `bower register jscamera git@gitlab.com:tech-gap-italia-open-source/jscamera.git -V`

**Describe the results you received:**

	bower jscamera#*               resolve git@gitlab.com:tech-gap-italia-open-source/jscamera.git#*
	bower jscamera#*              checkout 0.0.1
	bower jscamera#*              resolved git@gitlab.com:tech-gap-italia-open-source/jscamera.git#0.0.1
	? Registering a package will make it installable via the registry (https://bower.herokuapp.com), continue? Yes
	bower jscamera                register git@gitlab.com:tech-gap-italia-open-source/jscamera.git
	bower                       EINVFORMAT Invalid URL format

	Stack trace:
	Error: Invalid URL format
	    at createError (/usr/local/lib/node_modules/bower/lib/node_modules/bower-registry-client/lib/util/createError.js:2:15)
	    at Request._callback (/usr/local/lib/node_modules/bower/lib/node_modules/bower-registry-client/lib/register.js:43:29)
	    at Request.self.callback (/usr/local/lib/node_modules/bower/lib/node_modules/request/request.js:198:22)
	    at emitTwo (events.js:87:13)
	    at Request.emit (events.js:172:7)
	    at Request.<anonymous> (/usr/local/lib/node_modules/bower/lib/node_modules/request/request.js:1035:10)
	    at emitOne (events.js:82:20)
	    at Request.emit (events.js:169:7)
	    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/bower/lib/node_modules/request/request.js:962:12)
	    at emitNone (events.js:72:20)
	From previous event:
	    at /usr/local/lib/node_modules/bower/lib/commands/register.js:65:18
	From previous event:
	    at register (/usr/local/lib/node_modules/bower/lib/commands/register.js:51:6)
	    at /usr/local/lib/node_modules/bower/lib/commands/index.js:33:28
	From previous event:
	    at withLogger (/usr/local/lib/node_modules/bower/lib/commands/index.js:40:14)
	    at Function.runFromArgv [as line] (/usr/local/lib/node_modules/bower/lib/commands/index.js:30:16)
	    at Object.<anonymous> (/usr/local/lib/node_modules/bower/lib/bin/bower.js:83:26)

	Console trace:
	Error
	    at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:81:37)
	    at Logger.<anonymous> (/usr/local/lib/node_modules/bower/lib/bin/bower.js:110:26)
	    at emitOne (events.js:77:13)
	    at Logger.emit (events.js:169:7)
	    at Logger.emit (/usr/local/lib/node_modules/bower/lib/node_modules/bower-logger/lib/Logger.js:29:39)
	    at /usr/local/lib/node_modules/bower/lib/commands/index.js:48:20
	    at _rejected (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:844:24)
	    at /usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:870:30
	    at Promise.when (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:1122:31)
	    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:788:41)
	System info:
	Bower version: 1.7.9
	Node version: 4.2.6
	OS: Linux 4.4.0-53-generic x64

**Describe the results you expected:**

I would expect the project to be correctly registered in bower.

**Additional information:**

It works flawlessly if I use the `https://` version of the repository URL, as... 
    
    bower register jscamera https://gitlab.com/tech-gap-italia-open-source/jscamera.git

**Comment by stevevanhooser** [comment]
See http://stackoverflow.com/questions/15669091/bower-install-using-only-https

and http://lifesforlearning.com/bower-https/

It seems that the https version works in more settings

**Comment by thinkxl** [comment]
ping @danidemi. Could you try with @stevevanhooser's links?

**Comment by sheerun** [comment]
This issue got stale, and Bower doesn't accept new packages for registration anymore
