### ISSUE TITLE
Error: ENOENT: no such file or directory, rename 

### ISSUE THREAD

**Issue by SergeyJyravlev** [bower/bower#2439]
Hello!  I getting this error after "bower install" command. I do not understand the reason for the error. 
Bower version: 1.7.0
Node version: 5.11.0
OS: Darwin 15.4.0 x64
npm 3.8.6

```
Stack trace:
Error: ENOENT: no such file or directory, rename '/var/folders/d7/s72zc1ln0bs4nrn0fyl4vtk80000gn/T/sergei/bower/026259d742971fc066175fd810f60c76-18143-Xp1qT1' -> '/Users/user/.cache/bower/packages/15bd3af750c8e7d2914c33055d99c01e/5.2.0'
    at Error (native)

Console trace:
Error
    at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:82:37)
    at Logger.<anonymous> (/usr/local/lib/node_modules/bower/bin/bower:110:22)
    at emitOne (events.js:90:13)
    at Logger.emit (events.js:182:7)
    at Logger.emit (/usr/local/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/local/lib/node_modules/bower/lib/commands/index.js:68:20
    at _rejected (/usr/local/lib/node_modules/bower/node_modules/q/q.js:844:24)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:870:30
    at Promise.when (/usr/local/lib/node_modules/bower/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/node_modules/q/q.js:788:41)

```

**Comment by SergeyJyravlev** [comment]
Solvet. 
I added in .bowerrc  
```
"storage" : {
"packages" : ".bower-cache",
"registry" : ".bower-registry"
},
```

**Comment by thinkxl** [comment]
glad you figured it out. closing it.
