### ISSUE TITLE
ignoreDependencies make bower crashes

### ISSUE THREAD

**Issue by josselinbuils** [bower/bower#2441]
Hello, I have an issue when using the ignoreDependencies option in .bowerrc.

**Output of `bower -v && npm -v && node -v`:**

```
1.8.0
3.10.10
v6.9.5
```

**Additional environment details (proxy, private registry, etc.):**
I use a proxy and a private registry in addition to the official one.

**Steps to reproduce the issue:**

1. Add ignoredDependencies field inside .bowerrc and fill it with a dependency
2. Run a bower install
3. Run a bower install --force

**Describe the results you received:**

```
usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:155
                throw e;
                ^

TypeError: Cannot read property '_release' of undefined
    at StandardRenderer._tree2archy (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:439:47)
    at Array.map (native)
    at StandardRenderer._tree2archy (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:491:49)
    at StandardRenderer.<anonymous> (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:161:24)
    at /usr/local/lib/node_modules/bower/lib/node_modules/mout/object/forOwn.js:12:27
    at exec (/usr/local/lib/node_modules/bower/lib/node_modules/mout/object/forIn.js:71:19)
    at forIn (/usr/local/lib/node_modules/bower/lib/node_modules/mout/object/forIn.js:38:17)
    at Object.forOwn (/usr/local/lib/node_modules/bower/lib/node_modules/mout/object/forOwn.js:10:9)
    at StandardRenderer._install (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:149:17)
    at StandardRenderer.end (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:50:21)
```

It seems that bower considers that the dependency that has been put inside ignoreDependencies is installed and it crashed when trying to retrieve the installed version.

**Describe the results you expected:**
No crash.

**Additional information:**
The dependency that I put inside ignoreDependencies is a sub-dependency of one of my dependencies (not sure if it is very clear... :x).

Thank you for your work :)

**Comment by josselinbuils** [comment]
The issue seems to be there:
```
function handleLogger(logger, renderer) {
    logger
    .on('end', function (data) {
        if (!bower.config.silent && !bower.config.quiet) {
            renderer.end(data);
        }
    })
[...]
}
```

The missing property is not true even if it should for the uninstalled modules.

**Comment by thinkxl** [comment]
Could you share your `.bowerrc` please, I'll try to reproduce it.
