### ISSUE TITLE
Bower does not install ANYTHING.

### ISSUE THREAD

**Issue by etimoyoita** [bower/bower#2455]
I try to install new packages:

`bower install summernote --allow-root`

and I get:

```bower EACCES        EACCES: permission denied, open '/Users/EtimEsuOyoIta/.cache/bower/registry/bower.herokuapp.com/lookup/summernote_dfd8d'

Stack trace:
Error: EACCES: permission denied, open '/Users/EtimEsuOyoIta/.cache/bower/registry/bower.herokuapp.com/lookup/summernote_dfd8d'
    at Error (native)

Console trace:
Error
    at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:81:37)
    at Logger.<anonymous> (/usr/local/lib/node_modules/bower/lib/bin/bower.js:110:26)
    at emitOne (events.js:96:13)
    at Logger.emit (events.js:188:7)
    at Logger.emit (/usr/local/lib/node_modules/bower/lib/node_modules/bower-logger/lib/Logger.js:29:39)```
Help please. Thanks.

**Comment by sheerun** [comment]
Either remove cache directory or run with sudo

**Comment by golokeshpatra45** [comment]
Please help me with this - 

root@debian:/home/golokesh/Hygieia/UI# bower update
bower ESUDO         Cannot be run with sudo

Additional error details:
Since bower is a user command, there is no need to execute it with superuser permissions.
If you're having permission errors when using bower without sudo, please spend a few minutes learning more about how your system should work and make any necessary repairs.

http://www.joyent.com/blog/installing-node-and-npm
https://gist.github.com/isaacs/579814

**Comment by golokeshpatra45** [comment]
follow up to my previous question,  I have found out the solution to it ....

I am on a Debian VM Machine

I just copied the whole repo to my desktop where I didn't require any kind of access issues and voila, it worked .

bower install worked successfully,

The problem I was facing previously was -

**Stack trace:
/usr/lib/node_modules/bower/lib/node_modules/fstream/lib/dir-writer.js:35:25
/usr/lib/node_modules/bower/lib/node_modules/mkdirp/index.js:46:53
FSReqWrap.oncomplete (fs.js:114:15)

Console trace:
Error
at StandardRenderer.error (/usr/lib/node_modules/bower/lib/renderers/StandardRenderer.js:81:37)
at Logger. (/usr/lib/node_modules/bower/lib/bin/bower.js:110:26)
at emitOne (events.js:96:13)
at Logger.emit (events.js:191:7)
at Logger.emit (/usr/lib/node_modules/bower/lib/node_modules/bower-logger/lib/Logger.js:29:39)
at /usr/lib/node_modules/bower/lib/commands/index.js:48:20
at _rejected (/usr/lib/node_modules/bower/lib/node_modules/q/q.js:844:24)
at /usr/lib/node_modules/bower/lib/node_modules/q/q.js:870:30
at Promise.when (/usr/lib/node_modules/bower/lib/node_modules/q/q.js:1122:31)
at Promise.promise.promiseDispatch (/usr/lib/node_modules/bower/lib/node_modules/q/q.js:788:41)
System info:
Bower version: 1.8.0
Node version: 7.10.0
OS: Linux 3.16.0-4-amd64 x64**

I hope it solves the issue, else we will have to look for some other solution.

**Comment by wookoouk** [comment]
Could you please clarify where you moved it to and from. It would be good to know the difference to help diognose the issue.

With the little I know so far I would say:

There were permission issues with the location you were previously trying run bower in.
when running with root you would need to do `bower install --allow-root` (not having `--allow-root` would cause the second error you mentioned.

**Comment by sheerun** [comment]
Closing for no reply
