### ISSUE TITLE
I can't make dirs with dependencies.

### ISSUE THREAD

**Issue by Catalinul95** [bower/bower#2461]
```JSON
bower cached        https://github.com/twbs/bootstrap.git#3.3.7
bower validate      3.3.7 against https://github.com/twbs/bootstrap.git#*
bower cached        https://github.com/jquery/jquery-dist.git#3.2.1
bower validate      3.2.1 against https://github.com/jquery/jquery-dist.git#1.9.1 - 3
bower install       bootstrap#3.3.7
bower install       jquery#3.2.1
bower EPROTO        EPROTO: protocol error, mkdir '/home/Sites/web/nodekb/public/bower_components/bootstrap'

Stack trace:
/usr/lib/node_modules/bower/lib/node_modules/fstream/lib/dir-writer.js:35:25
/usr/lib/node_modules/bower/lib/node_modules/mkdirp/index.js:46:53
FSReqWrap.oncomplete (fs.js:123:15)

Console trace:
Error
    at StandardRenderer.error (/usr/lib/node_modules/bower/lib/renderers/StandardRenderer.js:81:37)
    at Logger.<anonymous> (/usr/lib/node_modules/bower/lib/bin/bower.js:110:26)
    at emitOne (events.js:96:13)
    at Logger.emit (events.js:188:7)
    at Logger.emit (/usr/lib/node_modules/bower/lib/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/lib/node_modules/bower/lib/commands/index.js:48:20
    at _rejected (/usr/lib/node_modules/bower/lib/node_modules/q/q.js:844:24)
    at /usr/lib/node_modules/bower/lib/node_modules/q/q.js:870:30
    at Promise.when (/usr/lib/node_modules/bower/lib/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/bower/lib/node_modules/q/q.js:788:41)
System info:
Bower version: 1.8.0
Node version: 6.10.2
OS: Linux 4.4.0-66-generic x64

```

This is what I get, I gave no idea why I can't make it work.. I used --allow-root too.I tried with sudo, no chance.

**Comment by thinkxl** [comment]
Hey @Catalinul95, I'm closing this as there isn't enough info for us to try to reproduce it. Take a look at https://github.com/bower/bower/wiki/Report-a-Bug on how to properly report a bug and open a new issue if you still have problems.
