### ISSUE TITLE
why can't I download  bower even though I have node ,npm and git

### ISSUE THREAD

**Issue by shamratevil** [bower/bower#2472]
**Mohammads-MacBook-Pro:~ mohammadhossain$ cd documents
Mohammads-MacBook-Pro:documents mohammadhossain$ cd confusion
Mohammads-MacBook-Pro:confusion mohammadhossain$ bower install
/usr/local/lib/node_modules/bower/lib/node_modules/configstore/index.js:54
				throw err;
				^

Error: EACCES: permission denied, open '/Users/mohammadhossain/.config/configstore/bower-github.json'
You don't have access to this file.

    at Object.fs.openSync (fs.js:651:18)
    at Object.fs.readFileSync (fs.js:553:33)
    at Configstore.get (/usr/local/lib/node_modules/bower/lib/node_modules/configstore/index.js:35:26)
    at Configstore (/usr/local/lib/node_modules/bower/lib/node_modules/configstore/index.js:28:44)
    at readCachedConfig (/usr/local/lib/node_modules/bower/lib/config.js:19:23)
    at defaultConfig (/usr/local/lib/node_modules/bower/lib/config.js:11:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/bower/lib/index.js:16:32)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)**
-----
Any help will be appreciated 

-->

**Output of `bower -v && npm -v && node -v`:**

```
(paste your output here)
```

**Additional environment details (proxy, private registry, etc.):**

**Steps to reproduce the issue:**

1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information:**

**Comment by thinkxl** [comment]
Closing this as this is not a Bower issue, please check your permissions.
