### ISSUE TITLE
npm install bower is failing to fetch bower from registry

### ISSUE THREAD

**Issue by rallj** [bower/bower#2481]
'npm install bower' started failing 2017-09-14.  This had been working before.

# BUG REPORT
$ npm install bower
npm http GET https://registry.npmjs.org/bower
npm http 200 https://registry.npmjs.org/bower
npm ERR! Error: failed to fetch from registry: bower
npm ERR!     at RegClient.<anonymous> (/usr/lib/node_modules/npm-registry-client/lib/get.js:140:18)
npm ERR!     at cb (/usr/lib/node_modules/npm-registry-client/lib/request.js:32:9)
npm ERR!     at RegClient.<anonymous> (/usr/lib/node_modules/npm-registry-client/lib/request.js:107:16)
npm ERR!     at cb (/usr/lib/node_modules/npm-registry-client/lib/request.js:132:9)
npm ERR!     at RegClient.<anonymous> (/usr/lib/node_modules/npm-registry-client/lib/request.js:305:12)
npm ERR!     at Request._callback (/usr/lib/node_modules/npm-registry-client/lib/request.js:212:65)
npm ERR!     at Request.self.callback (/usr/lib/node_modules/request/index.js:148:22)
npm ERR!     at Request.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/lib/node_modules/request/index.js:891:14)
npm ERR!     at Request.emit (events.js:117:20)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.10.0-514.26.2.el7.x86_64
npm ERR! command "node" "/usr/bin/npm" "install" "bower"
npm ERR! cwd /home/rallj/bower
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.3.6
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/rallj/bower/npm-debug.log
npm ERR! not ok code 0
$

**Comment by rallj** [comment]
Looks like I was using an old version of node.
