### ISSUE TITLE
  EXDEV EXDEV: cross-device link not permitted

### ISSUE THREAD

**Issue by sanset** [bower/bower#2500]
**Output of `bower -v && npm -v && node -v`:**

```

**bower update giving the following error**
 
bower     EXDEV EXDEV: cross-device link not permitted, link 'C:\Users\sandip_sethuram\AppData\Local\bower\cache\packages\edd5e0bada0be7bf86448414367e0022\v3.0.0\test\test-fixture-symlink.html' -> 'D:\ReTEM_17.3.0.0\ReTEMUI\bower_components\test-fixture\test-fixture.html'


Stack trace:
C:\Users\sandip_sethuram\AppData\Roaming\npm\node_modules\bower\lib\node_modules\fstream\lib\link-writer.js:76:26
FSReqWrap.oncomplete (fs.js:117:15)

Console trace:
Error
    at StandardRenderer.error (C:\Users\sandip_sethuram\AppData\Roaming\npm\node_modules\bower\lib\renderers\StandardRenderer.js:81:37)
    at Logger.<anonymous> (C:\Users\sandip_sethuram\AppData\Roaming\npm\node_modules\bower\lib\bin\bower.js:110:26)
    at emitOne (events.js:96:13)
    at Logger.emit (events.js:188:7)
    at Logger.emit (C:\Users\sandip_sethuram\AppData\Roaming\npm\node_modules\bower\lib\node_modules\bower-logger\lib\Logger.js:29:39)
    at C:\Users\sandip_sethuram\AppData\Roaming\npm\node_modules\bower\lib\commands\index.js:48:20
    at _rejected (C:\Users\sandip_sethuram\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:844:24)
    at C:\Users\sandip_sethuram\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:870:30
    at Promise.when (C:\Users\sandip_sethuram\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:1122:31)
    at Promise.promise.promiseDispatch (C:\Users\sandip_sethuram\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:788:41)
System info:
Bower version: 1.8.2
Node version: 6.2.2
OS: Windows_NT 6.3.9600 x64
```

**Additional environment details (proxy, private registry, etc.):**

running bower within the organization via proxy. 

**Steps to reproduce the issue:**

1. run **bower update**
2.
3.

**Describe the results you received:**

EXTDEV error

**Describe the results you expected:**

to successfully download all the bower components without failing

**Additional information:**

_bower needs to download the components from internet and as well as a local git_

**Comment by sheerun** [comment]
this is issue with yout filesystem that doesn't support cross-device links, there's no workaround, just store all files on one disk or change bower's cache directory to be on disk D (it's possible to set in global .bowerrc configuration).
