### ISSUE TITLE
bower 1.8.12 build failure

### ISSUE THREAD

**Issue by chenrui333** [bower/bower#2592]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>test failure</summary>

```
$ /usr/local/Cellar/bower/1.8.12/bin/bower
internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module 'bower-logger'
Require stack:
- /usr/local/Cellar/bower/1.8.12/libexec/lib/node_modules/bower/lib/bin/bower.js
- /usr/local/Cellar/bower/1.8.12/libexec/lib/node_modules/bower/bin/bower
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/Cellar/bower/1.8.12/libexec/lib/node_modules/bower/lib/bin/bower.js:5:14)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/Cellar/bower/1.8.12/libexec/lib/node_modules/bower/lib/bin/bower.js',
    '/usr/local/Cellar/bower/1.8.12/libexec/lib/node_modules/bower/bin/bower'
  ]
}
```

</details>

Full build log is in here, https://github.com/Homebrew/homebrew-core/runs/1723283963
relates to https://github.com/Homebrew/homebrew-core/pull/69280

**Comment by chenrui333** [comment]
I think it relates to [this commit](https://github.com/bower/bower/commit/41126ec03e53e208315d77ec2ece63d008967062#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519), is there any convenient installation script to use?

**Comment by sheerun** [comment]
Running `yarn` should be sufficient

**Comment by chenrui333** [comment]
Hi @sheerun, I will give `yarn` a try. Another thing, I found is the `1.8.12` is not marked as `latest release`, is there any reason for that? Thanks!

**Comment by sheerun** [comment]
it just doesn't have release notes
