### ISSUE TITLE
All usage of Bower fails with "Arguments to path.join must be strings"

### ISSUE THREAD

**Issue by henrycatalinismith** [bower/bower#270]
I've just installed bower 0.7.0 with `npm install .` and the following `package.json`:

```
{                                                                                                                           
  "name": "experiment",
  "version": "0.0.0",
  "dependencies": {
    "bower": "0.7.0"
  }
}
```

I'm running bower with `./node_modules/.bin/bower`, and the command always fails with the following error message:

```
path.js:360
        throw new TypeError('Arguments to path.join must be strings');
              ^
TypeError: Arguments to path.join must be strings
    at path.js:360:15
    at Array.filter (native)
    at Object.exports.join (path.js:358:36)
    at Object.<anonymous> (/home/h2s/src/tdd-js-experiment/node_modules/bower/lib/core/config.js:41:22)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
```

I've looked into the code in question, and the line causing the error looks like this:

```
var localFile = path.join(this.cwd, '.bowerrc');
```

The problem is that `this.cwd` is undefined when that line executes. Does this sound like my system might be misconfigured in some way?

For what it's worth, I reproduced the issue with version 0.6.0, and when doing a global installation with `sudo npm install -g bower`.

**Comment by dragosrususv** [comment]
@iredmedia : that fixed it, thank you
