### ISSUE TITLE
Error: spawn ENOENT when attempting to install package

### ISSUE THREAD

**Issue by sholtomaud** [bower/bower#307]
Just installed bower on OSX. 

Ran the following command from terminal: 
$ bower -v
0.8.5

then:
$ bower install jquery

/usr/local/lib/node_modules/bower/node_modules/tmp/lib/tmp.js:219
    throw err;
          ^
Error: spawn ENOENT
    at errnoException (child_process.js:945:11)
    at Process.ChildProcess._handle.onexit (child_process.js:736:34)

**Comment by webdesignberlin** [comment]
Same Problem here on Windows 7.

```sh
C:\Users\webdesignberlin\Documents\projects\blubb (master)
λ bower cache clean

C:\Users\webdesignberlin\Documents\projects\blubb  (master)
λ bower cache list

C:\Users\webdesignberlin\Documents\projects\blubb  (master)
λ bower install
bower not-cached    https://github.com/kenwheeler/slick.git#~1.4.1
bower resolve       https://github.com/kenwheeler/slick.git#~1.4.1
bower not-cached    git://github.com/twbs/bootstrap-sass.git#~3.3.3
bower resolve       git://github.com/twbs/bootstrap-sass.git#~3.3.3
bower not-cached    git://github.com/jquery/jquery.git#~2.1.3
bower resolve       git://github.com/jquery/jquery.git#~2.1.3
bower not-cached    git://github.com/gcusnieux/jquery-qrcode.git#*
bower resolve       git://github.com/gcusnieux/jquery-qrcode.git#*
bower ENOENT        spawn ENOENT

Stack trace:
Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)

Console trace:
Trace
    at StandardRenderer.error (C:\Program Files (x86)\nodejs\node_modules\bower\lib\renderers\StandardRenderer.js:82:17)
    at Logger.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\bower\bin\bower:110:22)
    at Logger.emit (events.js:95:17)
    at Logger.emit (C:\Program Files (x86)\nodejs\node_modules\bower\node_modules\bower-logger\lib\Logger.js:29:39)
    at C:\Program Files (x86)\nodejs\node_modules\bower\lib\commands\index.js:40:20
    at _rejected (C:\Program Files (x86)\nodejs\node_modules\bower\node_modules\q\q.js:797:24)
    at C:\Program Files (x86)\nodejs\node_modules\bower\node_modules\q\q.js:823:30
    at Promise.when (C:\Program Files (x86)\nodejs\node_modules\bower\node_modules\q\q.js:1035:31)
    at Promise.promise.promiseDispatch (C:\Program Files (x86)\nodejs\node_modules\bower\node_modules\q\q.js:741:41)
    at C:\Program Files (x86)\nodejs\node_modules\bower\node_modules\q\q.js:557:44

System info:
Bower version: 1.3.12
Node version: 0.10.33
OS: Windows_NT 6.1.7601 x64

**Comment by webdesignberlin** [comment]
Oha, sorry. Update Node to 0.12 stable fix it... shame on me.

**Comment by ERSUSHIL007** [comment]
I have the same problem while bower install command

bower not-cached    https://github.com/twbs/bootstrap.git#*
bower resolve       https://github.com/twbs/bootstrap.git#*
bower not-cached    https://github.com/angular/bower-angular.git#*
bower resolve       https://github.com/angular/bower-angular.git#*
bower ENOENT        spawn git ENOENT

Stack trace:
Error: spawn git ENOENT
    at _errnoException (util.js:1031:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

Console trace:
Error
    at StandardRenderer.error (C:\Users\READER\AppData\Roaming\npm\node_modules\bower\lib\renderers\StandardRenderer.js:88:37)
    at Logger.<anonymous> (C:\Users\READER\AppData\Roaming\npm\node_modules\bower\lib\bin\bower.js:113:30)
    at Logger.emit (events.js:159:13)
    at Logger.emit (C:\Users\READER\AppData\Roaming\npm\node_modules\bower\lib\node_modules\bower-logger\lib\Logger.js:29:39)
    at C:\Users\READER\AppData\Roaming\npm\node_modules\bower\lib\commands\index.js:49:24
    at _rejected (C:\Users\READER\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:864:24)
    at C:\Users\READER\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:890:30
    at Promise.when (C:\Users\READER\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:1142:31)
    at Promise.promise.promiseDispatch (C:\Users\READER\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:808:41)
    at C:\Users\READER\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:624:44
System info:
Bower version: 1.8.4
Node version: 9.2.0
OS: Windows_NT 10.0.16299 x64
