### ISSUE TITLE
Error: spawn ENOENT

### ISSUE THREAD

**Issue by codylindley** [bower/bower#339]
Bower install has pretty much stop working for me.

node 0.10.1/npm 1.2.15, bower 0.8.5

I've npm removed it, added it back, and tried using the clear cache command. When I use install or info I get the same results.

/usr/local/lib/node_modules/bower/node_modules/tmp/lib/tmp.js:219
throw err;
^
Error: spawn ENOENT
at errnoException (child_process.js:945:11)
at Process.ChildProcess._handle.onexit (child_process.js:736:34)

**Comment by krysalead** [comment]
Got the same issue with post install script. I will check the solution provided

**Comment by ijlalkhanzada** [comment]
when i run cordova-splash command this error to come.
events.js:72
throw er; // Unhandled 'error' event
^
Error: spawn ENOENT
at errnoException (child_process.js:980:11)
at Process.ChildProcess._handle.onexit (child_process.js:771:34)

**Comment by frontenddeveloping** [comment]
Use cygwin console:

>
$ bower install kendo-ui-core
bower kendo-ui-core#*       not-cached git://github.com/kendo-labs/bower-kendo-ui.git#*
bower kendo-ui-core#*          resolve git://github.com/kendo-labs/bower-kendo-ui.git#*
bower kendo-ui-core#*           ENOENT spawn git ENOENT

>Stack trace:
Error: spawn git ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:474:9)
    at process._tickCallback (node.js:388:17)

>Console trace:
Error
    at StandardRenderer.error (C:\Users\apinchuk\AppData\Roaming\npm\node_modules\bower\lib\renderers\StandardRenderer.js:83:37)
    at Logger.<anonymous> (C:\Users\apinchuk\AppData\Roaming\npm\node_modules\bower\bin\bower:116:30)
    at emitOne (events.js:77:13)
    at Logger.emit (events.js:169:7)
    at Logger.emit (C:\Users\apinchuk\AppData\Roaming\npm\node_modules\bower\node_modules\bower-logger\lib\Logger.js:29:39)
    at C:\Users\apinchuk\AppData\Roaming\npm\node_modules\bower\lib\commands\index.js:48:20
    at _rejected (C:\Users\apinchuk\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:844:24)
    at C:\Users\apinchuk\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:870:30
    at Promise.when (C:\Users\apinchuk\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:1122:31)
    at Promise.promise.promiseDispatch (C:\Users\apinchuk\AppData\Roaming\npm\node_modules\bower\node_modules\q\q.js:788:41)
System info:
Bower version: 1.7.2
Node version: 5.4.1
OS: Windows_NT 10.0.10586 x64

**Comment by MartijnHols** [comment]
Had the same issue, reporting my solution since this is the top result on Google (sorry subscribers); turns out you must have the executable (`.exe`) somewhere in the path, having a shortcut such as `git.cmd` does not work properly in Node.
