### ISSUE TITLE
tmp.js throws error

### ISSUE THREAD

**Issue by engpetarmarinov** [bower/bower#552]
I have nodejs v0.10.11, npm 1.2.30
I'm trying to install bower on kubuntu 13.04 like so:

`sudo npm install -g bower`

and I'm getting these warinings:

```
/usr/bin/bower -> /usr/lib/node_modules/bower/bin/bower
npm WARN package.json github-url-from-git@1.1.1 No repository field.
npm WARN package.json assert-plus@0.1.2 No repository field.
npm WARN package.json ctype@0.5.2 No repository field.
```

`bower -v //0.9.2`

When I'm trying to do :

`bower install`

I get:

```
/usr/lib/node_modules/bower/node_modules/tmp/lib/tmp.js:260
  throw err;
        ^
TypeError: Arguments to path.join must be strings
    at path.js:360:15
    at Array.filter (native)
    at Object.exports.join (path.js:358:36)
    at Package.generateResourceId (/usr/lib/node_modules/bower/lib/core/package.js:857:23)
    at null.<anonymous> (/usr/lib/node_modules/bower/lib/core/package.js:178:10)
    at Request._callback (/usr/lib/node_modules/bower/lib/core/source.js:38:9)
    at Request.self.callback (/usr/lib/node_modules/bower/node_modules/request/main.js:122:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/usr/lib/node_modules/bower/node_modules/request/main.js:655:16)
    at Request.EventEmitter.emit (events.js:117:20)

```

**Comment by jweyrich** [comment]
Also see https://github.com/bower/bower/issues/558#issuecomment-69043953.
