### ISSUE TITLE
Can't install component from a tar.gz url

### ISSUE THREAD

**Issue by craig-jennings** [bower/bower#619]
I'm trying to install bootstrap through specifying a tar.gz url and I keep getting an `EISDIR` error:

```
$ bower install https://github.com/twitter/bootstrap/archive/v2.3.2.tar.gz
bower v2.3.2.tar.gz#*       not-cached https://github.com/twitter/bootstrap/archive/v2.3.2.tar.gz#*
bower v2.3.2.tar.gz#*          resolve https://github.com/twitter/bootstrap/archive/v2.3.2.tar.gz#*
bower v2.3.2.tar.gz#*         download https://github.com/twitter/bootstrap/archive/v2.3.2.tar.gz
bower v2.3.2.tar.gz#*          extract v2.3.2.tar.gz
bower v2.3.2.tar.gz#*           EISDIR EISDIR, open 'C:\Users\<private>\AppData\Local\Temp\bower\v2.3.2.tar.gz-MIsbQI'

Stack trace:
Error: EISDIR, open 'C:\Users\<private>\AppData\Local\Temp\bower\v2.3.2.tar.gz-MIsbQI'

Console trace:
Trace
    at StandardRenderer.error (c:\Users\<private>\AppData\Roaming\npm\node_modules\bower-canary\lib\renderers\StandardRenderer.js:66:17)
    at EventEmitter.updateNotifier.packageName (c:\Users\<private>\AppData\Roaming\npm\node_modules\bower-canary\bin\bower:108:18)
    at EventEmitter.emit (events.js:95:17)
    at c:\Users\<private>\AppData\Roaming\npm\node_modules\bower-canary\lib\commands\install.js:27:17
    at _rejected (c:\Users\<private>\AppData\Roaming\npm\node_modules\bower-canary\node_modules\q\q.js:713:24)
    at c:\Users\<private>\AppData\Roaming\npm\node_modules\bower-canary\node_modules\q\q.js:739:30
    at Promise.when (c:\Users\<private>\AppData\Roaming\npm\node_modules\bower-canary\node_modules\q\q.js:979:31)
    at Promise.promise.promiseDispatch (c:\Users\<private>\AppData\Roaming\npm\node_modules\bower-canary\node_modules\q\q.js:661:41)
    at c:\Users\<private>\AppData\Roaming\npm\node_modules\bower-canary\node_modules\q\q.js:543:44
    at flush (c:\Users\<private>\AppData\Roaming\npm\node_modules\bower-canary\node_modules\q\q.js:106:17)
```

```
$ bower -v
1.0.0-alpha.6
```

I was under the impression that tar.gz urls were supported in the rewrite of bower. Is that wrong?

**Comment by nekojira** [comment]
I incurred in this issue with bower 1.4.1 while including libraries that don't have a bower.json in their repository - but I resolved it prepending 'git+' like so:
    "jquery-oembed" : "git+https://github.com/nfl/jquery-oembed-all#master"
I thought of mentioning it here in case someone bumps in the same issue
