### ISSUE TITLE
fail in bower install

### ISSUE THREAD

**Issue by alizdavoodi** [bower/bower#696]
when use bower install this Error show up !

bower EACCES        EACCES, unlink '/Users/alireza/.cache/bower/registry/bower.herokuapp.com/lookup/angular'

Stack trace:
Error: EACCES, unlink '/Users/alireza/.cache/bower/registry/bower.herokuapp.com/lookup/angular'

Console trace:
Trace
    at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:69:17)
    at Logger.updateNotifier.packageName (/usr/local/lib/node_modules/bower/bin/bower:113:18)
    at Logger.EventEmitter.emit (events.js:95:17)
    at Logger.emit (/usr/local/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/local/lib/node_modules/bower/lib/commands/install.js:25:16
    at _rejected (/usr/local/lib/node_modules/bower/node_modules/q/q.js:713:24)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:739:30
    at Promise.when (/usr/local/lib/node_modules/bower/node_modules/q/q.js:979:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/node_modules/q/q.js:661:41)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:543:44

System info:
Bower version: 1.0.3
Node version: 0.10.15
OS: Darwin 12.4.0 x64

**Comment by osalama7** [comment]
Fixed a similar issue using bower clean cache and running chown -R /pathtofolder on paths that result errors along the way of installing bower packages

**Comment by Artadys** [comment]
I have the same error You cannot use the new command inside an ember-cli project.

my ember-cli: 2.6.1
node: 4.4.5
os: darwin x64

**Comment by walwyde** [comment]
it says bower: command not found.
after running $ sudo bower cache clean --allow-root.. please help!

**Comment by walwyde** [comment]
> try sudo npm install -g bower

THIS IS A PERFECT SOLUTION, THANKS A LOT.
I MEAN ONE TOUCH......
