### ISSUE TITLE
retry git commands on network error

### ISSUE THREAD

**Issue by davidmaxwaterman** [bower/bower#774]
http retries were implemented, but not for git commands that hit the network..example error :

```
bower font-awesome#~3.2.1               ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/FortAwesome/Font-Awesome.git", exit code of #128

Additional error details:
fatal: unable to connect to github.com:
github.com: System error

Stack trace:
Error: Failed to execute "git ls-remote --tags --heads git://github.com/FortAwesome/Font-Awesome.git", exit code of #128
    at createError (/usr/lib/node_modules/bower/lib/util/createError.js:4:15)
    at ChildProcess.<anonymous> (/usr/lib/node_modules/bower/lib/util/cmd.js:92:21)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:735:16)
    at Socket.<anonymous> (child_process.js:948:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)

Console trace:
Trace
    at StandardRenderer.error (/usr/lib/node_modules/bower/lib/renderers/StandardRenderer.js:70:17)
    at Logger.updateNotifier.packageName (/usr/lib/node_modules/bower/bin/bower:113:18)
    at Logger.EventEmitter.emit (events.js:95:17)
    at Logger.emit (/usr/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/lib/node_modules/bower/lib/commands/install.js:25:16
    at _rejected (/usr/lib/node_modules/bower/node_modules/q/q.js:713:24)
    at /usr/lib/node_modules/bower/node_modules/q/q.js:739:30
    at Promise.when (/usr/lib/node_modules/bower/node_modules/q/q.js:979:31)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/bower/node_modules/q/q.js:661:41)
    at /usr/lib/node_modules/bower/node_modules/q/q.js:543:44

System info:
Bower version: 1.1.2
Node version: 0.10.15
OS: Linux 3.8.0-27-generic x64

```

**Comment by sheerun** [comment]
This can be implemented as [Pluggable Resolver](http://bower.io/docs/pluggable-resolvers/) that overwrites Bower's native one.

**Comment by davidmaxwaterman** [comment]
(I missed the message on 6 Dec, 2013[!], but I've moved out of the environment where I was getting persistent network errors, so I can't reproduce the problem any more, reliably anyway).
