### ISSUE TITLE
Bower init fails either in interactive or non interactive in 1.2.7 in CYGWIN

### ISSUE THREAD

**Issue by edmondop** [bower/bower#904]
``` shell
me@Info06 /cygdrive/c/dev/simple
$ bower init
bower ENOINT        Register requires an interactive shell
```

Then if I try interactive mode

``` shell
me@Info06 /cygdrive/c/dev/simple
$ bower init --config.interactive
[?] name: (simpe)
C:\Users\porcu.GOTTEXBROKERS\AppData\Roaming\npm\node_modules\bower\node_modules\tmp\lib\tmp.js:261
  throw err;
        ^
Error: read ENOTCONN
    at errnoException (net.js:878:11)
    at Socket._read (net.js:389:21)
    at Socket.Readable.read (_stream_readable.js:294:10)
    at Socket.read (net.js:291:43)
    at new Socket (net.js:185:10)
    at process.stdin (node.js:660:19)
    at Object.Interface.createInterface (C:\Users\porcu.GOTTEXBROKERS\AppData\Roaming\npm\node_modules\bower\node_modules\inquirer\lib\utils\readline.js:31:43)
    at Object.inquirer.prompt (C:\Users\porcu.GOTTEXBROKERS\AppData\Roaming\npm\node_modules\bower\node_modules\inquirer\lib\inquirer.js:50:40)
    at StandardRenderer.prompt (C:\Users\porcu.GOTTEXBROKERS\AppData\Roaming\npm\node_modules\bower\lib\renderers\StandardRenderer.js:109:14)
    at Logger.updateNotifier.packageName (C:\Users\porcu.GOTTEXBROKERS\AppData\Roaming\npm\node_modules\bower\bin\bower:120:14)
```

**Comment by error500** [comment]
Doesn't wor in mintty 2.0.3 on windows also. I had to run it in cmd
