### ISSUE TITLE
bower `error Maximum call stack size exceeded`

### ISSUE THREAD

**Issue by funnythingz** [bower/bower#917]
![](http://gyazo.com/099673e135148007698e8a9c80c32141.png)

``` sh
% bower install https://github.com/funnythingz/qflipper.git
bower qflipper#*                cached https://github.com/funnythingz/qflipper.git#1.2.0
bower qflipper#*              validate 1.2.0 against https://github.com/funnythingz/qflipper.git#*
bower                            error Maximum call stack size exceeded

Stack trace:
N/A

Console trace:
Trace
    at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:74:17)
    at Logger.updateNotifier.packageName (/usr/local/lib/node_modules/bower/bin/bower:109:18)
    at Logger.EventEmitter.emit (events.js:95:17)
    at Logger.emit (/usr/local/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/local/lib/node_modules/bower/lib/commands/install.js:27:16
    at _rejected (/usr/local/lib/node_modules/bower/node_modules/q/q.js:808:24)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:834:30
    at Promise.when (/usr/local/lib/node_modules/bower/node_modules/q/q.js:1079:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/node_modules/q/q.js:752:41)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:574:44

System info:
Bower version: 1.2.7
Node version: 0.10.17
OS: Darwin 12.5.0 x64
```

repository: https://github.com/funnythingz/qflipper

**Comment by coultonluke** [comment]
I'm getting this error too, I've just installed the Nuget package `install-package Bower` from https://www.nuget.org/packages/Bower/ is it because this is outdated?
