### ISSUE TITLE
random ENOTEMPTY in Travis run

### ISSUE THREAD

**Issue by nexik** [bower/bower#933]
I use this command to install bower in travis

```
(npm install -g bower grunt-cli; npm install; bower install)
```

randomly I get this error:

```
bower ENOTEMPTY     ENOTEMPTY, rename '/tmp/travis/bower/angular-8465-xIRvRU'
Stack trace:
Error: ENOTEMPTY, rename '/tmp/travis/bower/angular-8465-xIRvRU'
Console trace:
Trace
    at StandardRenderer.error (/home/travis/.nvm/v0.10.12/lib/node_modules/bower/lib/renderers/StandardRenderer.js:74:17)
    at Logger.updateNotifier.packageName (/home/travis/.nvm/v0.10.12/lib/node_modules/bower/bin/bower:109:18)
    at Logger.EventEmitter.emit (events.js:95:17)
    at Logger.emit (/home/travis/.nvm/v0.10.12/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /home/travis/.nvm/v0.10.12/lib/node_modules/bower/lib/commands/install.js:27:16
    at _rejected (/home/travis/.nvm/v0.10.12/lib/node_modules/bower/node_modules/q/q.js:808:24)
    at /home/travis/.nvm/v0.10.12/lib/node_modules/bower/node_modules/q/q.js:834:30
    at Promise.when (/home/travis/.nvm/v0.10.12/lib/node_modules/bower/node_modules/q/q.js:1079:31)
    at Promise.promise.promiseDispatch (/home/travis/.nvm/v0.10.12/lib/node_modules/bower/node_modules/q/q.js:752:41)
    at /home/travis/.nvm/v0.10.12/lib/node_modules/bower/node_modules/q/q.js:574:44
```

**Comment by adrianchen19888** [comment]
:+1:

**Comment by waynejuckts** [comment]
I could install all packages in my Node project without -g parameter. And that causes the issue for me. Same issue you are all describing. So i reinstallt bower with -g and all is working fine for me

**Comment by sheerun** [comment]
This thread got really messy. If someone still experiences any issues, please open another issues with steps to reproduce. Thank you!
